from django.urls import path
from django.views.generic import RedirectView
from .views import (
    saas_dashboard_view, saas_login_view, saas_logout_view, saas_performance_view, 
    saas_logs_view, saas_tenant_detail_view, saas_update_user_view,
    saas_tenant_files_view, saas_file_browser_view, saas_file_serve_view,
    saas_reset_user_password_view, saas_reset_user_sessions_view, saas_email_config_view, saas_test_email_view,
    saas_toggle_maintenance_view, saas_backups_view, saas_create_backup_view,
    saas_delete_backup_view, saas_download_backup_view, saas_restore_backup_view,
    saas_processes_view, saas_terminal_view, saas_terminal_exec_view,
    saas_explorer_view, api_explorer_browse, api_explorer_read,
    api_explorer_save, api_explorer_delete, saas_system_lock_view,
    saas_system_logout_view, saas_global_config_view, saas_firewall_view,
    api_tenant_file_status, saas_force_tenant_password_change_view,
    saas_knowledge_center_view, saas_knowledge_category_action_view, saas_knowledge_resource_action_view,
    saas_create_tenant_view, saas_tenants_manage_view, saas_toggle_tenant_visibility_view,
    saas_toggle_tenant_active_view, saas_tenant_data_summary_view, saas_tenant_data_explorer_view,
    saas_update_voeu_action_view, saas_update_prospect_action_view, saas_reset_prospect_action_view,
    saas_update_due_paiement_action_view, saas_update_paiement_action_view, saas_bulk_delete_action_view,
    saas_audit_logs_view, saas_clear_tenant_logs_view, saas_tenant_sync_pedagogical_data_view,
    api_tenants_pedagogical_sync_list_view, api_master_formations_list_view,
    api_tenant_formations_list_view, api_tenant_delete_formation_view,
    api_tenant_delete_specialite_view,
    saas_export_prospects_view
)

app_name = 'saas_admin_app'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='saas_admin_app:saas_login', permanent=False)),
    path('login/', saas_login_view, name='saas_login'),
    path('logout/', saas_logout_view, name='saas_logout'),
    path('dashboard/', saas_dashboard_view, name='saas_dashboard'),
    path('tenants/', saas_tenants_manage_view, name='saas_tenants_manage'),
    path('tenant-data-summary/', saas_tenant_data_summary_view, name='saas_tenant_data_summary'),
    path('tenant/<int:tenant_id>/data-explorer/', saas_tenant_data_explorer_view, name='saas_tenant_data_explorer'),
    path('tenant/create/', saas_create_tenant_view, name='saas_create_tenant'),
    path('performance/', saas_performance_view, name='saas_performance'),
    path('processes/', saas_processes_view, name='saas_processes'),
    path('terminal/', saas_terminal_view, name='saas_terminal'),
    path('api/terminal/exec/', saas_terminal_exec_view, name='saas_terminal_exec'),
    path('system-lock/', saas_system_lock_view, name='saas_system_lock'),
    path('system-logout/', saas_system_logout_view, name='saas_system_logout'),
    path('explorer/', saas_explorer_view, name='saas_explorer'),
    path('api/explorer/browse/', api_explorer_browse, name='api_explorer_browse'),
    path('api/explorer/read/', api_explorer_read, name='api_explorer_read'),
    path('api/explorer/save/', api_explorer_save, name='api_explorer_save'),
    path('api/explorer/delete/', api_explorer_delete, name='api_explorer_delete'),
    path('logs/', saas_logs_view, name='saas_logs'),
    path('backups/', saas_backups_view, name='saas_backups'),
    path('backups/create/', saas_create_backup_view, name='saas_create_backup'),
    path('backups/<int:backup_id>/restore/', saas_restore_backup_view, name='saas_restore_backup'),
    path('backups/<int:backup_id>/delete/', saas_delete_backup_view, name='saas_delete_backup'),
    path('backups/<int:backup_id>/download/', saas_download_backup_view, name='saas_download_backup'),
    path('tenant/<int:tenant_id>/', saas_tenant_detail_view, name='saas_tenant_detail'),
    path('tenant/<int:tenant_id>/files/', saas_tenant_files_view, name='saas_tenant_files'),
    path('api/tenant/<int:tenant_id>/user/<int:user_id>/update/', saas_update_user_view, name='saas_update_user'),
    path('api/tenant/<int:tenant_id>/user/<int:user_id>/reset-password/', saas_reset_user_password_view, name='saas_reset_user_password'),
    path('api/tenant/<int:tenant_id>/user/<int:user_id>/reset-sessions/', saas_reset_user_sessions_view, name='saas_reset_user_sessions'),
    path('api/tenant/<int:tenant_id>/force-password-change/', saas_force_tenant_password_change_view, name='saas_force_tenant_password_change'),
    path('api/tenant/<int:tenant_id>/files/browse/', saas_file_browser_view, name='saas_file_browser'),
    path('api/tenant/<int:tenant_id>/file-status/', api_tenant_file_status, name='api_tenant_file_status'),
    path('api/tenant/<int:tenant_id>/files/serve/<path:file_path>', saas_file_serve_view, name='saas_file_serve'),
    path('settings/email/', saas_email_config_view, name='saas_email_config'),
    path('api/settings/email/test/', saas_test_email_view, name='saas_test_email'),
    path('api/settings/maintenance/toggle/', saas_toggle_maintenance_view, name='saas_toggle_maintenance'),
    path('settings/global/', saas_global_config_view, name='saas_global_config'),
    path('firewall/', saas_firewall_view, name='saas_firewall'),
    path('knowledge-center/', saas_knowledge_center_view, name='saas_knowledge_center'),
    path('api/knowledge-center/category/action/', saas_knowledge_category_action_view, name='saas_knowledge_category_action'),
    path('api/knowledge-center/resource/action/', saas_knowledge_resource_action_view, name='saas_knowledge_resource_action'),
    path('api/tenant/<int:tenant_id>/toggle-visibility/', saas_toggle_tenant_visibility_view, name='saas_toggle_tenant_visibility'),
    path('api/tenant/<int:tenant_id>/toggle-active/', saas_toggle_tenant_active_view, name='saas_toggle_tenant_active'),
    path('api/tenant/<int:tenant_id>/voeu/<int:voeu_id>/update/', saas_update_voeu_action_view, name='saas_update_voeu_action'),
    path('api/tenant/<int:tenant_id>/prospect/<int:prospect_id>/update/', saas_update_prospect_action_view, name='saas_update_prospect_action'),
    path('api/tenant/<int:tenant_id>/prospect/<int:prospect_id>/reset/', saas_reset_prospect_action_view, name='saas_reset_prospect_action'),
    path('api/tenant/<int:tenant_id>/due-paiement/<int:dp_id>/update/', saas_update_due_paiement_action_view, name='saas_update_due_paiement_action'),
    path('api/tenant/<int:tenant_id>/paiement/<int:p_id>/update/', saas_update_paiement_action_view, name='saas_update_paiement_action'),
    path('api/tenant/<int:tenant_id>/bulk-delete/', saas_bulk_delete_action_view, name='saas_bulk_delete_action'),
    path('audit-logs/', saas_audit_logs_view, name='saas_audit_logs'),
    path('api/tenant/<int:tenant_id>/sync-pedagogical-data/', saas_tenant_sync_pedagogical_data_view, name='saas_tenant_sync_pedagogical_data'),
    path('api/tenants/pedagogical-sync-list/', api_tenants_pedagogical_sync_list_view, name='api_tenants_pedagogical_sync_list'),
    path('api/master/formations/', api_master_formations_list_view, name='api_master_formations_list'),
    path('api/tenant/<int:tenant_id>/formations/', api_tenant_formations_list_view, name='api_tenant_formations_list'),
    path('api/tenant/<int:tenant_id>/formation/delete/', api_tenant_delete_formation_view, name='api_tenant_delete_formation'),
    path('api/tenant/<int:tenant_id>/specialite/delete/', api_tenant_delete_specialite_view, name='api_tenant_delete_specialite'),
    path('tenant/<int:tenant_id>/prospects/export/', saas_export_prospects_view, name='saas_export_prospects'),
]
