# Generated by Django 5.1.4 on 2025-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorieComptable',
        ),
    ]
