import sys
with open('templates/tenant_folder/budget/my_campaigns.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
new_lines.append('{% extends "tenant_folder/base.html" %}\n')
new_lines.append('{% load static %}\n')
new_lines.append('{% block title %}Référentiel des Postes Budgétaires | {{ tenant.nom }}{% endblock %}\n\n')
new_lines.append('{% block content %}\n')
new_lines.append('<style>\n')
new_lines.extend(lines[63:138])
new_lines.append('</style>\n\n')
new_lines.append('<div class="main-content">\n')
new_lines.append('    <div class="page-content bg-light">\n')
new_lines.append('        <div class="container-fluid">\n')
new_lines.append('            {% include \'tenant_folder/direction_navbar.html\' %}\n')
new_lines.append('            <div class="row mb-4">\n')
new_lines.append('                <div class="col-12">\n')
new_lines.append('                    <div class="d-flex justify-content-between align-items-center bg-white p-4 rounded-4 shadow-sm border border-light">\n')
new_lines.append('                        <div class="d-flex align-items-center">\n')
new_lines.append('                            <div class="bg-info bg-opacity-10 rounded-circle p-3 me-3 text-info">\n')
new_lines.append('                                <i class="ri-list-settings-line fs-3"></i>\n')
new_lines.append('                            </div>\n')
new_lines.append('                            <div>\n')
new_lines.append('                                <h4 class="fs-18 fw-bold text-dark mb-1">Référentiel des Postes Budgétaires</h4>\n')
new_lines.append('                                <p class="text-muted mb-0 fs-13">Liste des centres de coûts et revenus configurés</p>\n')
new_lines.append('                            </div>\n')
new_lines.append('                        </div>\n')
new_lines.append('                    </div>\n')
new_lines.append('                </div>\n')
new_lines.append('            </div>\n\n')

new_lines.append('            <div class="row">\n')
new_lines.append('                <div class="col-12 bg-white rounded-4 shadow-sm p-4">\n')
new_lines.append('                    <div class="row">\n')
new_lines.extend(lines[258:432])
new_lines.append('                    </div>\n')
new_lines.append('                </div>\n')
new_lines.append('            </div>\n')
new_lines.append('        </div>\n')
new_lines.append('    </div>\n')
new_lines.append('</div>\n')
new_lines.append('{% endblock %}\n\n')
new_lines.append('{% block extra_js %}\n')
new_lines.extend(lines[442:465])
new_lines.append('{% endblock %}\n')

with open('templates/tenant_folder/budget/budget_posts.html', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
