# Generated by Django 5.1.4 on 2026-01-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_stage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stagiaire',
        ),
    ]
