# Generated by Django 5.1.4 on 2026-01-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0002_initial'),
        ('t_formations', '0004_alter_programmeformation_unique_together'),
        ('t_groupe', '0001_initial'),
        ('t_stage', '0002_delete_stagiaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conseil', models.DateField()),
                ('observations_generales', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conseil de Validation',
                'verbose_name_plural': 'Conseils de Validation',
            },
        ),
        migrations.CreateModel(
            name='FocusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('thematique', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_groups', to='t_formations.formateurs')),
            ],
            options={
                'verbose_name': 'Focus Group',
                'verbose_name_plural': 'Focus Groups',
            },
        ),
        migrations.CreateModel(
            name='SeanceFocusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateTimeField()),
                ('duree_heures', models.DecimalField(decimal_places=2, default=3.0, help_text='Durée en heures (ex: 3.5)', max_digits=4)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('focus_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='t_stage.focusgroup')),
            ],
            options={
                'verbose_name': 'Séance Focus Group',
                'verbose_name_plural': 'Séances Focus Groups',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=500)),
                ('problematique', models.TextField(blank=True, null=True)),
                ('plan_previsionnel', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('taux_avancement', models.IntegerField(default=0, help_text="Taux d'avancement global (0-100%)")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soutenu', 'Soutenu'), ('ajourne', 'Ajourné'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encadrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_encadres', to='t_formations.formateurs')),
                ('etudiant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages_clore', to='t_crm.prospets')),
                ('etudiant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_associes', to='t_crm.prospets')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='t_groupe.groupe')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.AddField(
            model_name='focusgroup',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='focus_groups_membership', to='t_stage.stage'),
        ),
        migrations.CreateModel(
            name='PresentationProgressive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.IntegerField(choices=[(1, '1ère Présentation (25-35%)'), (2, '2ème Présentation (65-75%)'), (3, '3ème Présentation / Soutenance à blanc (~90%)')])),
                ('date_presentation', models.DateField()),
                ('taux_avancement_declare', models.IntegerField(help_text="Taux d'avancement déclaré par le stagiaire")),
                ('observations', models.TextField(blank=True, null=True)),
                ('corrections_exigees', models.TextField(blank=True, null=True)),
                ('delai_correction', models.DateField(blank=True, help_text='Délai maximum pour réaliser les corrections (ex: 15 jours)', null=True)),
                ('validee', models.BooleanField(default=False, help_text="Cocher si la présentation est validée par l'encadrant")),
                ('examinateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinateur_presentations', to='t_formations.formateurs')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='t_stage.stage')),
            ],
            options={
                'verbose_name': 'Présentation Progressive',
                'verbose_name_plural': 'Présentations Progressives',
                'unique_together': {('stage', 'etape')},
            },
        ),
        migrations.CreateModel(
            name='DecisionConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('soutenable', 'Soutenable (Lancement de la soutenance officielle)'), ('ajourne', 'Ajourné (Délai supplémentaire de 2 mois)')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('taux_final', models.IntegerField(help_text="Taux d'achèvement final constaté (95-100%)")),
                ('conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='t_stage.conseilvalidation')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_conseil', to='t_stage.stage')),
            ],
            options={
                'verbose_name': 'Décision de Conseil',
                'verbose_name_plural': 'Décisions de Conseil',
                'unique_together': {('conseil', 'stage')},
            },
        ),
    ]
