# Generated by Django 5.1.4 on 2026-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_initial'),
        ('t_stage', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='etudiant1',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='etudiant2',
        ),
        migrations.AddField(
            model_name='stage',
            name='etudiants',
            field=models.ManyToManyField(related_name='stages', to='t_crm.prospets'),
        ),
    ]
