# Generated by Django 5.1.4 on 2026-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_stage', '0004_remove_stage_etudiant1_remove_stage_etudiant2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancefocusgroup',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='seances_discussion', to='t_stage.stage'),
        ),
    ]
