# Generated by Django 5.1.4 on 2026-06-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0022_prospets_password'),
        ('t_formations', '0012_modules_plan_cours'),
        ('t_groupe', '0006_groupe_admissible_stage'),
        ('t_stage', '0005_seancefocusgroup_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_ponderee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_stage', to='t_crm.prospets')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_stage', to='t_groupe.groupe')),
            ],
            options={
                'verbose_name': 'Bulletin Examen Final (Stage)',
                'verbose_name_plural': 'Bulletins Examens Finaux (Stage)',
                'unique_together': {('groupe', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='NoteBulletinStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, help_text='Note sur 20', null=True)),
                ('coefficient', models.IntegerField(default=1)),
                ('valeur_ponderee', models.FloatField(blank=True, help_text='Note * Coefficient', null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_stage.bulletinstage')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules')),
            ],
            options={
                'verbose_name': 'Note Examen Final (Stage)',
                'verbose_name_plural': 'Notes Examens Finaux (Stage)',
                'unique_together': {('bulletin', 'module')},
            },
        ),
    ]
