# Generated by Django 5.1.4 on 2026-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_stage', '0006_bulletinstage_notebulletinstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='organisme_accueil',
            field=models.CharField(blank=True, help_text='Entreprise ou organisme accueillant les stagiaires', max_length=255, null=True),
        ),
    ]
