# Generated by Django 5.1.4 on 2026-06-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0002_alter_documenttemplate_template_type'),
        ('t_stage', '0007_stage_organisme_accueil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageDocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_info', models.CharField(help_text="Cible de l'impression (Ex: Tout le binôme, ou Nom de l'étudiant)", max_length=255)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pdf_editor.documentgeneration')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_history', to='t_stage.stage')),
            ],
            options={
                'ordering': ['-date_generation'],
            },
        ),
    ]
