# Generated by Django 5.1.4 on 2026-06-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_stage', '0008_stagedocumenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilvalidation',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10),
        ),
    ]
