# Generated by Django 5.1.4 on 2026-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_stage', '0009_conseilvalidation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilvalidation',
            name='focus_groups',
            field=models.ManyToManyField(blank=True, related_name='conseils_validation', to='t_stage.focusgroup'),
        ),
        migrations.AddField(
            model_name='conseilvalidation',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='conseils_validation', to='t_stage.stage'),
        ),
    ]
