# Generated by Django 5.1.4 on 2026-01-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('standard', 'Standard'), ('rachat_credit', 'Rachat de Crédit')], default='standard', max_length=50, verbose_name='Type de Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='associe_app.globalpaymentcategory')),
            ],
            options={
                'verbose_name': 'Global Payment category',
                'verbose_name_plural': 'Global Payment categories',
            },
        ),
        migrations.CreateModel(
            name='GlobalDepensesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='associe_app.globaldepensescategory')),
                ('payment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depense_categories', to='associe_app.globalpaymentcategory')),
            ],
            options={
                'verbose_name': 'Global Depense category',
                'verbose_name_plural': 'Global Depenses categories',
            },
        ),
    ]
