# Generated by Django 5.1.4 on 2026-02-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostesBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depense_categories', models.ManyToManyField(blank=True, related_name='postes_budgetaires', to='associe_app.globaldepensescategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_postes', to='associe_app.postesbudgetaire')),
                ('payment_categories', models.ManyToManyField(blank=True, related_name='postes_budgetaires', to='associe_app.globalpaymentcategory')),
            ],
            options={
                'verbose_name': 'Poste Budgetaire',
                'verbose_name_plural': 'Postes Budgetaires',
            },
        ),
    ]
