# Generated by Django 5.1.4 on 2026-02-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0002_postesbudgetaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='postesbudgetaire',
            name='type',
            field=models.CharField(choices=[('depense', 'Dépense'), ('recette', 'Recette'), ('mixte', 'Mixte')], default='mixte', max_length=20),
        ),
    ]
