# Generated by Django 5.1.4 on 2026-02-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0003_postesbudgetaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postesbudgetaire',
            name='type',
            field=models.CharField(choices=[('depense', 'Dépense'), ('recette', 'Recette')], default='depense', max_length=20),
        ),
    ]
