# Generated by Django 5.1.4 on 2026-02-16 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0004_alter_postesbudgetaire_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne Budgétaire',
                'verbose_name_plural': 'Campagnes Budgétaires',
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.IntegerField(help_text='ID of the Entreprise in the tenant schema')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='associe_app.budgetcampaign')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='app.institut')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='associe_app.postesbudgetaire')),
            ],
            options={
                'verbose_name': 'Ligne Budgétaire',
                'verbose_name_plural': 'Lignes Budgétaires',
                'unique_together': {('campaign', 'poste', 'institut', 'entreprise_id')},
            },
        ),
    ]
