# Generated by Django 5.1.4 on 2026-02-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0005_budgetcampaign_budgetline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('campaign', 'poste', 'institut')},
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='entreprise_id',
        ),
    ]
