# Generated by Django 5.1.4 on 2026-02-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0006_alter_budgetline_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('campaign', 'institut')},
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='poste',
        ),
    ]
