# Generated by Django 5.1.4 on 2026-02-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0007_alter_budgetline_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='associe_app.budgetcampaign')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_details', to='app.institut')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_details', to='associe_app.postesbudgetaire')),
            ],
            options={
                'verbose_name': 'Détail Budget',
                'verbose_name_plural': 'Détails Budget',
                'unique_together': {('campaign', 'institut', 'poste', 'entreprise_id')},
            },
        ),
    ]
