# Generated by Django 5.1.4 on 2026-02-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0008_budgetlinedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='statut',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20),
        ),
    ]
