# Generated by Django 5.1.4 on 2026-02-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0009_budgetline_commentaire_budgetline_statut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetlinedetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetlinedetail',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_details', to='associe_app.globalpaymentcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetlinedetail',
            unique_together={('campaign', 'institut', 'poste', 'payment_category', 'entreprise_id')},
        ),
    ]
