# Generated by Django 5.1.4 on 2026-02-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0010_alter_budgetlinedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire Admin')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='associe_app.budgetcampaign')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='app.institut')),
            ],
            options={
                'verbose_name': 'Demande de Rallonge',
                'verbose_name_plural': 'Demandes de Rallonge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetExtensionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.IntegerField(help_text='ID of the Entreprise in tenant schema')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant Actuel')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nouveau Montant')),
                ('payment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associe_app.globalpaymentcategory')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associe_app.postesbudgetaire')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='associe_app.budgetextensionrequest')),
            ],
            options={
                'verbose_name': 'Détail Rallonge',
                'verbose_name_plural': 'Détails Rallonge',
            },
        ),
    ]
