# Generated by Django 5.1.4 on 2026-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0011_budgetextensionrequest_budgetextensionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlinedetail',
            name='t1_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='budgetlinedetail',
            name='t2_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='budgetlinedetail',
            name='t3_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='budgetlinedetail',
            name='t4_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
