# Generated by Django 5.1.4 on 2026-03-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0012_budgetlinedetail_t1_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Payment Type',
                'verbose_name_plural': 'Global Payment Types',
            },
        ),
        migrations.AddField(
            model_name='globalpaymentcategory',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_categories', to='associe_app.globalpaymenttype', verbose_name='Type de paiement'),
        ),
    ]
