# Generated by Django 5.1.4 on 2026-03-06 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0013_globalpaymenttype_globalpaymentcategory_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpaymentcategory',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='globalpaymenttype',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_types', to='associe_app.globalpaymentcategory', verbose_name='Catégorie de paiement'),
        ),
    ]
