# Generated by Django 5.1.4 on 2026-03-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0014_remove_globalpaymentcategory_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpaymenttype',
            name='payment_category',
        ),
        migrations.AddField(
            model_name='globalpaymenttype',
            name='payment_categories',
            field=models.ManyToManyField(blank=True, related_name='payment_types', to='associe_app.globalpaymentcategory', verbose_name='Catégories de paiement'),
        ),
    ]
