# Generated by Django 5.1.4 on 2026-03-09 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('associe_app', '0015_remove_globalpaymenttype_payment_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetlinedetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetextensionitem',
            name='depense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associe_app.globaldepensescategory'),
        ),
        migrations.AddField(
            model_name='budgetlinedetail',
            name='depense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_details', to='associe_app.globaldepensescategory'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetlinedetail',
            unique_together={('campaign', 'institut', 'poste', 'payment_category', 'depense_category', 'entreprise_id')},
        ),
    ]
