# Generated by Django 5.1.4 on 2026-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0016_alter_budgetlinedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcampaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
