# Generated by Django 5.1.4 on 2026-03-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0017_budgetcampaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postesbudgetaire',
            name='order',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
