# Generated by Django 5.1.4 on 2026-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0018_postesbudgetaire_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldepensescategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalpaymentcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
