# Generated by Django 5.1.4 on 2026-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0019_globaldepensescategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcampaign',
            name='target_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Objectif Dépenses (Global)'),
        ),
        migrations.AddField(
            model_name='budgetcampaign',
            name='target_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Objectif Recettes (Global)'),
        ),
    ]
