# Generated by Django 5.1.4 on 2026-07-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0021_saasnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='statut',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pre_validated', 'Pré-validé'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20),
        ),
    ]
