# Generated by Django 5.1.4 on 2026-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associe_app', '0022_alter_budgetline_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcampaign',
            name='target_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Objectif Dépenses (Global)'),
        ),
        migrations.AlterField(
            model_name='budgetcampaign',
            name='target_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Objectif Recettes (Global)'),
        ),
        migrations.AlterField(
            model_name='budgetextensionitem',
            name='old_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Montant Actuel'),
        ),
        migrations.AlterField(
            model_name='budgetextensionitem',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nouveau Montant'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetlinedetail',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
