# Generated by Django 5.1.4 on 2026-01-12 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institut_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin', models.DateField(null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('has_essai', models.BooleanField(blank=True, null=True)),
                ('periode_essai', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_essei', models.CharField(blank=True, choices=[('m', 'Mois'), ('a', 'Années')], default='m', max_length=100, null=True)),
                ('observations', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('civilite', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mme', 'Mme'), ('mlle', 'Mlle')], max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('prenom_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('cin', models.CharField(blank=True, max_length=255, null=True)),
                ('nin', models.CharField(blank=True, max_length=255, null=True)),
                ('secu', models.CharField(blank=True, max_length=255, null=True)),
                ('situation_familiale', models.CharField(blank=True, choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf(ve)')], max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_contract', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('etat', models.CharField(blank=True, choices=[('en cours', "En cours d'activité"), ('demission', 'Démissionnaire')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employes',
            },
        ),
        migrations.CreateModel(
            name='LigneFicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='CategoriesContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.CharField(choices=[('active', 'Activé'), ('disabled', 'Désactivé')], default='active', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entite_legal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise')),
            ],
            options={
                'verbose_name': 'Catégorie de contrat',
                'verbose_name_plural': 'Catégories de contrat',
            },
        ),
        migrations.CreateModel(
            name='ArticleContratSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_special', to='t_rh.contrats')),
            ],
            options={
                'verbose_name': 'Article de contrat special',
                'verbose_name_plural': 'Articles de contrat special',
            },
        ),
        migrations.AddField(
            model_name='contrats',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='t_rh.employees'),
        ),
        migrations.CreateModel(
            name='Conges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_rh.employees')),
            ],
            options={
                'verbose_name': 'Conge',
                'verbose_name_plural': 'Conges',
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True)),
                ('date_paie', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_rh.employees')),
            ],
            options={
                'verbose_name': 'Paie',
                'verbose_name_plural': 'Paies',
            },
        ),
        migrations.AddField(
            model_name='contrats',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.posts'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.services'),
        ),
        migrations.AddField(
            model_name='contrats',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.services'),
        ),
        migrations.CreateModel(
            name='TachesPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_rh.posts')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
            },
        ),
        migrations.CreateModel(
            name='TemplateFichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, choices=[('vacataire', 'Enseignant vacataire'), ('employe', 'Employe(e)')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temple fiche de paie',
                'verbose_name_plural': 'Templates fiche de paie',
            },
        ),
        migrations.CreateModel(
            name='TypesContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.categoriescontrat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrat',
            },
        ),
        migrations.AddField(
            model_name='contrats',
            name='type_contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='t_rh.typescontrat'),
        ),
        migrations.CreateModel(
            name='ArticlesContratStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='t_rh.typescontrat')),
            ],
        ),
    ]
