# Generated by Django 5.1.4 on 2025-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrats',
            name='mode_essei',
            field=models.CharField(blank=True, choices=[('m', 'Mois'), ('a', 'Années')], default='m', max_length=100, null=True),
        ),
    ]
