# Generated by Django 5.1.4 on 2025-03-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='work_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
    ]
