# Generated by Django 5.1.4 on 2026-05-12 10:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absences',
            options={'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AddField(
            model_name='absences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 12, 10, 49, 44, 398315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absences',
            name='date_debut',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absences',
            name='date_fin',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absences',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='absences_rh', to='t_rh.employees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absences',
            name='justifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absences',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('half_day', 'Demi-journée')], default='present', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='t_rh.employees')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
