# Generated by Django 5.1.4 on 2025-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='secu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
