# Generated by Django 5.1.4 on 2025-10-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
