# Generated by Django 5.1.4 on 2025-09-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0002_contrats_mode_essei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='tenant',
        ),
    ]
