# Generated by Django 5.1.4 on 2026-05-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0002_alter_absences_options_absences_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conges',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.AddField(
            model_name='conges',
            name='commentaire_rh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conges',
            name='duree',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nombre de jours ouvrables', max_digits=5),
        ),
        migrations.AddField(
            model_name='conges',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='conges/justificatifs/'),
        ),
        migrations.AddField(
            model_name='conges',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='conges',
            name='type_conge',
            field=models.CharField(choices=[('ANNUEL', 'Congé Annuel'), ('MALADIE', 'Congé Maladie'), ('MATERNITE', 'Congé Maternité'), ('EXCEPTIONNEL', 'Congé Exceptionnel (Mariage, Décès, etc.)'), ('SANS_SOLDE', 'Congé Sans Solde'), ('RECUPERATION', 'Récupération')], default='ANNUEL', max_length=20),
        ),
        migrations.AddField(
            model_name='conges',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employees',
            name='solde_conge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde de congé actuel (jours)', max_digits=5),
        ),
        migrations.AddField(
            model_name='employees',
            name='solde_conge_annee_prec',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reliquat année précédente', max_digits=5),
        ),
        migrations.AlterField(
            model_name='conges',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='t_rh.employees'),
        ),
    ]
