# Generated by Django 5.1.4 on 2025-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0002_articlecontratspecial_typescontrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescontratstandard',
            name='contenu',
            field=models.TextField(null=True),
        ),
    ]
