# Generated by Django 5.1.4 on 2025-12-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0002_employees_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='sexe',
            new_name='genre',
        ),
    ]
