# Generated by Django 5.1.4 on 2026-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0003_alter_conges_options_conges_commentaire_rh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut_standard', models.TimeField(default='08:00')),
                ('heure_fin_standard', models.TimeField(default='16:30')),
                ('quota_annuel_conge', models.IntegerField(default=30)),
                ('cloture_conge_mois', models.IntegerField(default=6)),
                ('cloture_conge_jour', models.IntegerField(default=30)),
                ('taux_heure_sup_standard', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('taux_heure_sup_nuit', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration RH',
                'verbose_name_plural': 'Configurations RH',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='date_debut_probation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_fin_probation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
