# Generated by Django 5.1.4 on 2025-09-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0003_remove_employees_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conges',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='tenant',
        ),
    ]
