# Generated by Django 5.1.4 on 2025-03-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0003_alter_articlescontratstandard_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrats',
            name='observations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contrats',
            name='periode_essai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
