# Generated by Django 5.1.4 on 2025-02-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0003_absences_services_employees_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('type_contrat', models.CharField(choices=[('CDD', 'Contrat à Durée Déterminée'), ('CDI', 'Contrat à Durée Indéterminée'), ('Stage', 'Stage'), ('Vacation', 'Vacation'), ('Tous', 'Applicable à tous')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='service',
        ),
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('interim', 'Interim')], max_length=255, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('poste', models.CharField(blank=True, choices=[('emp', 'Employe(e)'), ('dir', 'Directeur(trice)'), ('per', 'Enseignant permanant'), ('vac', 'Enseignant vacataire')], max_length=255, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_rh.employees')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.services')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
    ]
