# Generated by Django 5.1.4 on 2026-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0004_hrconfig_employees_date_debut_probation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrats',
            name='prime_panier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrats',
            name='prime_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
