# Generated by Django 5.1.4 on 2025-03-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0004_contrats_observations_contrats_periode_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='prenom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='prenom_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
