# Generated by Django 5.1.4 on 2025-02-26 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0004_articlescontrat_remove_employees_date_depart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescontrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articlescontrat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlescontrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlescontrat',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlescontrat',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDD', 'Contrat à Durée Déterminée'), ('CDI', 'Contrat à Durée Indéterminée'), ('Stage', 'Stage'), ('Vacation', 'Vacation'), ('Tous', 'Applicable à tous')], max_length=20, null=True),
        ),
    ]
