# Generated by Django 5.1.4 on 2026-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0005_contrats_prime_panier_contrats_prime_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='ccp',
            field=models.CharField(blank=True, help_text='Compte CCP', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='rib',
            field=models.CharField(blank=True, help_text='RIB Bancaire (20 chiffres)', max_length=25, null=True),
        ),
    ]
