# Generated by Django 5.1.4 on 2025-03-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_rh', '0005_employees_nom_mere_employees_prenom_mere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='work_in',
        ),
        migrations.AddField(
            model_name='contrats',
            name='work_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
    ]
