# Generated by Django 5.1.4 on 2025-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0006_lignefichedepaie_templatefichepaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='civilite',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mme', 'Mme'), ('mlle', 'Mlle')], max_length=100, null=True),
        ),
    ]
