# Generated by Django 5.1.4 on 2026-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0006_employees_ccp_employees_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrconfig',
            name='jours_supplementaires_sud',
            field=models.IntegerField(default=10, help_text='Jours de congé supplémentaires pour le Sud'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='taux_heure_sup_75',
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=5),
        ),
    ]
