# Generated by Django 5.1.4 on 2025-03-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0006_remove_employees_work_in_contrats_work_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de contrat',
                'verbose_name_plural': 'Catégories de contrat',
            },
        ),
        migrations.AddField(
            model_name='typescontrat',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.categoriescontrat'),
        ),
    ]
