# Generated by Django 5.1.4 on 2025-03-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_rh', '0007_categoriescontrat_typescontrat_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriescontrat',
            name='entite_legal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
    ]
