# Generated by Django 5.1.4 on 2025-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0007_employees_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
