# Generated by Django 5.1.4 on 2026-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0007_hrconfig_jours_supplementaires_sud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_particular_irg',
            field=models.BooleanField(default=False, help_text="Cochez pour appliquer le barème particulier de l'IRG", verbose_name='Cas particulier IRG (Retraité / Handicapé)'),
        ),
    ]
