# Generated by Django 5.1.4 on 2025-03-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0008_employees_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='t_rh.employees'),
        ),
    ]
