# Generated by Django 5.1.4 on 2025-03-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0008_categoriescontrat_entite_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriescontrat',
            name='etat',
            field=models.CharField(choices=[('active', 'Activé'), ('disabled', 'Désactivé')], default='active', max_length=100, null=True),
        ),
    ]
