# Generated by Django 5.1.4 on 2025-03-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0009_alter_contrats_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='has_contract',
            field=models.BooleanField(default=False),
        ),
    ]
