# Generated by Django 5.1.4 on 2025-03-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0011_posts_alter_contrats_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrats',
            old_name='salaire',
            new_name='salaire_base',
        ),
        migrations.RemoveField(
            model_name='contrats',
            name='work_in',
        ),
    ]
