# Generated by Django 5.1.4 on 2025-03-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0013_contrats_duree_contrats_has_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='etat',
            field=models.CharField(blank=True, choices=[('en cours', "En cours d'activité"), ('demission', 'Démissionnaire')], max_length=100, null=True),
        ),
    ]
