# Generated by Django 5.1.4 on 2025-04-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0014_employees_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TachesPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_rh.posts')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
            },
        ),
    ]
