# Generated by Django 5.1.4 on 2025-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_rh', '0015_tachesposte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrats',
            name='date_debut',
        ),
        migrations.AlterField(
            model_name='contrats',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
