# Generated by Django 5.1.4 on 2026-01-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('members', models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Groupe de discussion',
                'verbose_name_plural': 'Groupes de discussion',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/', verbose_name='Fichier joint')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='t_communication.chatgroup', verbose_name='Groupe')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('bg-primary', 'Travail (Bleu)'), ('bg-success', 'Personnel (Vert)'), ('bg-danger', 'Important (Rouge)'), ('bg-warning', 'A faire (Jaune)'), ('bg-info', 'Autre (Ciel)')], default='bg-primary', max_length=20, verbose_name='Catégorie')),
                ('start_time', models.DateTimeField(verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complété')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['start_time'],
            },
        ),
    ]
