# Generated by Django 5.1.4 on 2026-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_communication', '0002_message_file_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('bg-primary', 'Travail (Bleu)'), ('bg-success', 'Personnel (Vert)'), ('bg-danger', 'Important (Rouge)'), ('bg-warning', 'A faire (Jaune)'), ('bg-info', 'Autre (Ciel)')], default='bg-primary', max_length=20, verbose_name='Catégorie'),
        ),
    ]
