# Generated by Django 5.1.4 on 2026-01-11 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_communication', '0003_reminder_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
