# Generated by Django 5.1.4 on 2026-01-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_formations', '0002_initial'),
        ('t_groupe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCrenau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('jour_data', models.JSONField(blank=True, default=dict, null=True)),
                ('horaire_data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de la salle')),
                ('capacite', models.IntegerField(verbose_name='Capacité')),
                ('type_salle', models.CharField(choices=[('Amphi', 'Amphithéâtre'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('Bureau', 'Bureau')], max_length=50, verbose_name='Type de salle')),
                ('equipements', models.TextField(blank=True, null=True, verbose_name='Équipements')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4')], max_length=20, verbose_name='Semestre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.CharField(blank=True, max_length=100, null=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('enc', 'En cours'), ('pau', 'Pause'), ('ter', 'Terminé')], default='bro', max_length=100, null=True)),
                ('is_special', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_timetable.modelcrenau')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EditionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_timetable.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, max_length=100, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules', verbose_name='Cours')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.formateurs')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_timetable.salle', verbose_name='Salle')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='t_timetable.timetable', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': "Entrée d'emploi du temps",
                'verbose_name_plural': "Entrées d'emploi du temps",
            },
        ),
    ]
