# Generated by Django 5.1.4 on 2025-10-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_formations', '0009_remove_formation_frais_assurance'),
        ('t_groupe', '0006_groupe_code_partenaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'horaire")),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom du jour')),
                ('abreviation', models.CharField(max_length=10, verbose_name='Abréviation')),
                ('ordre', models.IntegerField(verbose_name='Ordre dans la semaine')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jour',
                'verbose_name_plural': 'Jours',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de la salle')),
                ('capacite', models.IntegerField(verbose_name='Capacité')),
                ('type_salle', models.CharField(choices=[('Amphi', 'Amphithéâtre'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('Bureau', 'Bureau')], max_length=50, verbose_name='Type de salle')),
                ('equipements', models.TextField(blank=True, null=True, verbose_name='Équipements')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4')], max_length=20, verbose_name='Semestre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules', verbose_name='Cours')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_timetable.horaire', verbose_name='Horaire')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_timetable.jour', verbose_name='Jour')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_timetable.salle', verbose_name='Salle')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_timetable.timetable', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': "Entrée d'emploi du temps",
                'verbose_name_plural': "Entrées d'emploi du temps",
                'ordering': ['jour__ordre', 'horaire__heure_debut'],
                'unique_together': {('timetable', 'jour', 'horaire')},
            },
        ),
    ]
