# Generated by Django 5.1.4 on 2025-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
    ]
