# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('enc', 'En cours'), ('pau', 'Pause'), ('ter', 'Terminé')], default='bro', max_length=100, null=True),
        ),
    ]
