# Generated by Django 5.1.4 on 2025-10-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0002_timetable_is_configured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jour',
            options={'verbose_name': 'Jour', 'verbose_name_plural': 'Jours'},
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'verbose_name': "Entrée d'emploi du temps", 'verbose_name_plural': "Entrées d'emploi du temps"},
        ),
        migrations.RemoveField(
            model_name='jour',
            name='abreviation',
        ),
        migrations.RemoveField(
            model_name='jour',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='jour',
            name='ordre',
        ),
        migrations.AddField(
            model_name='jour',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_timetable.timetable'),
        ),
    ]
