# Generated by Django 5.1.4 on 2025-10-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0003_alter_jour_options_alter_timetableentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_timetable.timetable'),
        ),
    ]
