# Generated by Django 5.1.4 on 2025-10-19 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0004_horaire_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCrenau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('jour_data', models.JSONField(blank=True, default=dict, null=True)),
                ('horaire_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jour',
            name='timetable',
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='crenau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_timetable.modelcrenau'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timetable', 'crenau')},
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='horaire',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='jour',
        ),
        migrations.DeleteModel(
            name='Horaire',
        ),
        migrations.DeleteModel(
            name='Jour',
        ),
    ]
