# Generated by Django 5.1.4 on 2025-10-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0005_modelcrenau_remove_jour_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcrenau',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
