# Generated by Django 5.1.4 on 2025-10-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0006_modelcrenau_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_timetable.modelcrenau'),
        ),
    ]
