# Generated by Django 5.1.4 on 2025-10-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0007_timetable_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcrenau',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
