# Generated by Django 5.1.4 on 2025-10-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0013_alter_enseignantmodule_module'),
        ('t_timetable', '0011_alter_timetableentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.formateurs'),
        ),
    ]
