# Generated by Django 5.1.4 on 2025-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0012_timetableentry_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
