# Generated by Django 5.1.4 on 2025-10-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0013_timetable_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='t_timetable.timetable', verbose_name='Emploi du temps'),
        ),
    ]
