# Generated by Django 5.1.4 on 2025-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0014_alter_timetableentry_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
