# Generated by Django 5.1.4 on 2025-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0015_timetable_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='is_validated',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('pau', 'Pause'), ('ter', 'Terminer')], max_length=100, null=True),
        ),
    ]
