# Generated by Django 5.1.4 on 2025-10-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0016_alter_timetable_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='est_actif',
        ),
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('pau', 'Pause'), ('ter', 'Terminer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
