# Generated by Django 5.1.4 on 2025-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0017_remove_timetable_est_actif_timetable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(blank=True, choices=[('bro', 'Brouillon'), ('enc', 'En cours'), ('pau', 'Pause'), ('ter', 'Terminer')], default='bro', max_length=100, null=True),
        ),
    ]
