# Generated by Django 5.1.4 on 2025-10-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0014_formateurs_dispo'),
        ('t_timetable', '0019_suivicours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivicours',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_suivie_cours', to='t_formations.modules'),
        ),
    ]
