# Generated by Django 5.1.4 on 2025-10-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0020_alter_suivicours_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiviCours',
        ),
    ]
