# Generated by Django 5.1.4 on 2025-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_timetable', '0021_delete_suivicours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='annee_scolaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
