# Generated by Django 5.1.4 on 2026-02-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institut',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('associe', 'Associe'), ('master', 'Compte maitre'), ('second', 'Compte standard')], max_length=255, null=True),
        ),
    ]
