# Generated by Django 5.1.4 on 2025-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('master', 'master'), ('second', 'second')], max_length=255, null=True),
        ),
    ]
