# Generated by Django 5.1.4 on 2026-04-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to='app.institut'),
        ),
        migrations.AlterField(
            model_name='tenantfolder',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_folders', to='app.institut'),
        ),
        migrations.AlterField(
            model_name='tenantmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.institut'),
        ),
    ]
