# Generated by Django 5.1.4 on 2025-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_institut_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institut',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('master', 'Compte maitre'), ('second', 'Compte standard')], max_length=255, null=True),
        ),
    ]
