# Generated by Django 5.1.4 on 2026-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tenantdocument_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmessage',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='tenant_chat_docs/'),
        ),
        migrations.AlterField(
            model_name='tenantmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
