# Generated by Django 5.1.4 on 2026-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tenantmessage_attached_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='max_upload_size',
            field=models.PositiveIntegerField(blank=True, help_text='Laissez vide pour utiliser la limite globale du SaaS', null=True, verbose_name='Taille max upload (KB)'),
        ),
    ]
