# Generated by Django 5.1.4 on 2026-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_institut_max_upload_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='Forcer le changement de mot de passe'),
        ),
        migrations.AddField(
            model_name='institut',
            name='password_reset_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de forçage du reset'),
        ),
    ]
