# Generated by Django 5.1.4 on 2026-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_institut_force_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='crm_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Notifications CRM actives'),
        ),
    ]
