# Generated by Django 5.1.4 on 2026-04-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_institut_crm_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible dans la sélection'),
        ),
    ]
