# Generated by Django 5.1.4 on 2026-05-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_institut_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
    ]
