# Generated by Django 5.1.4 on 2026-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_institut_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='is_sync_enabled',
            field=models.BooleanField(default=True, verbose_name='Synchronisation activée'),
        ),
        migrations.AddField(
            model_name='institut',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation'),
        ),
        migrations.AddField(
            model_name='institut',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Intervalle de synchronisation (min)'),
        ),
        migrations.AddField(
            model_name='institut',
            name='sync_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token de synchronisation'),
        ),
    ]
