# Generated by Django 5.1.4 on 2026-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_institut_is_sync_enabled_institut_last_sync_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='code_tenant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code Tenant'),
        ),
    ]
