# Generated by Django 5.1.4 on 2026-06-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_institut_code_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='is_portail_active',
            field=models.BooleanField(default=True, verbose_name='Accès Portail (Étudiants/Formateurs)'),
        ),
    ]
