# Generated by Django 5.1.4 on 2025-02-22 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_etudiants', '0002_etudiant_alreeady_paied'),
        ('t_formations', '0010_partenaires_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_student', models.IntegerField(default=0)),
                ('max_student', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_createdy', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe_specialite', to='t_formations.specialites')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_line_groupe', to='t_groupe.groupe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_line_student', to='t_etudiants.etudiant')),
            ],
            options={
                'verbose_name': "Groupe d'etudiants",
                'verbose_name_plural': "Groupes d'etudiants",
            },
        ),
    ]
