# Generated by Django 5.1.4 on 2026-03-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0030_remove_tvaconseil_entreprise'),
        ('t_groupe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='thematique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='t_conseil.thematiques'),
        ),
    ]
