# Generated by Django 5.1.4 on 2026-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='date_lancement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
