# Generated by Django 5.1.4 on 2025-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='annee_scolaire',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
