# Generated by Django 5.1.4 on 2025-10-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0024_prospets_matricule_prospets_matricule_interne'),
        ('t_groupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeline',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_line_student', to='t_crm.prospets'),
        ),
    ]
