# Generated by Django 5.1.4 on 2025-10-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0002_alter_groupeline_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='description',
        ),
    ]
