# Generated by Django 5.1.4 on 2025-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0002_groupe_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='etat',
            field=models.CharField(choices=[('inscription', "En cours d'inscription"), ('enc', 'En cours'), ('Cloturé', 'Cloturé')], default='enc', max_length=200),
        ),
    ]
