# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0002_groupe_date_lancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='etat',
            field=models.CharField(choices=[('valider', 'Groupe validé'), ('brouillon', 'Brouillon'), ('inscription', "En cours d'inscription"), ('enc', 'En cours'), ('cloture', 'Clôturé')], default='brouillon', max_length=200),
        ),
    ]
