# Generated by Django 5.1.4 on 2026-03-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0030_remove_tvaconseil_entreprise'),
        ('t_formations', '0005_formateurs_nin'),
        ('t_groupe', '0002_groupe_thematique'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='t_conseil.devis'),
        ),
        migrations.CreateModel(
            name='GroupeThematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formateurs')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_thematiques', to='t_groupe.groupe')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_conseil.thematiques')),
            ],
        ),
    ]
