# Generated by Django 5.1.4 on 2025-03-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0002_alter_groupe_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='etat',
            field=models.CharField(choices=[('valider', 'Groupe valider'), ('brouillon', 'Brouillon'), ('inscription', "En cours d'inscription"), ('enc', 'En cours'), ('Cloturé', 'Cloturé')], default='brouillon', max_length=200),
        ),
    ]
