# Generated by Django 5.1.4 on 2025-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0003_alter_groupe_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='max_student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='min_student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
