# Generated by Django 5.1.4 on 2026-03-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0003_groupe_devis_groupethematique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='thematique',
        ),
        migrations.DeleteModel(
            name='GroupeThematique',
        ),
    ]
