# Generated by Django 5.1.4 on 2026-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0004_remove_groupe_devis_remove_groupe_thematique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='etat',
            field=models.CharField(choices=[('valider', 'Groupe validé'), ('brouillon', 'Brouillon'), ('inscription', "En cours d'inscription"), ('inscription_terminee', 'Inscription terminée'), ('enc', 'En cours'), ('cloture', 'Clôturé')], default='brouillon', max_length=200),
        ),
    ]
