# Generated by Django 5.1.4 on 2025-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0004_alter_groupe_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='etat',
            field=models.CharField(choices=[('inscription', "En cours d'inscription"), ('enc', 'En cours'), ('Cloturé', 'Cloturé')], default='inscription', max_length=200),
        ),
    ]
