# Generated by Django 5.1.4 on 2025-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0004_alter_groupe_createdy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='etat',
            field=models.CharField(choices=[('valider', 'Groupe valider'), ('brouillon', 'Brouillon'), ('inscription', "En cours d'inscription"), ('enc', 'En cours'), ('cloture', 'Cloturé')], default='brouillon', max_length=200),
        ),
    ]
