# Generated by Django 5.1.4 on 2026-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0005_alter_groupe_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='admissible_stage',
            field=models.BooleanField(default=False),
        ),
    ]
