# Generated by Django 5.1.4 on 2025-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0005_alter_groupe_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='code_partenaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
