# Generated by Django 5.1.4 on 2025-11-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0006_groupe_code_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='num_groupe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
