# Generated by Django 5.1.4 on 2026-06-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0006_groupe_admissible_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='concerne_examen_final',
            field=models.BooleanField(default=True),
        ),
    ]
