# Generated by Django 5.1.4 on 2025-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_groupe', '0007_groupe_num_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='semestre',
            field=models.CharField(blank=True, choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4'), ('s', 'Stage')], default='1', max_length=100, null=True),
        ),
    ]
