# Generated by Django 5.1.4 on 2025-12-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0036_alter_prospets_slug'),
        ('t_formations', '0024_promos_is_archived'),
        ('t_groupe', '0008_groupe_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites')),
            ],
        ),
    ]
