# Generated by Django 5.1.4 on 2025-12-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0036_alter_prospets_slug'),
        ('t_formations', '0024_promos_is_archived'),
        ('t_groupe', '0009_affectationgroupe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationgroupe',
            unique_together={('etudiant', 'specialite')},
        ),
    ]
