# Generated by Django 5.1.4 on 2025-04-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clientPaiementsRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPaiementsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(blank=True, choices=[('tranche', 'Tranche'), ('mensuelle', 'Mensuelle'), ('totalite', 'Paiement unique')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(blank=True, choices=[('en_attente', 'En Attente'), ('annulation', "Demande d'annulation"), ('annulation_approuver', "Demande d'annulation approuvée"), ('terminer', 'Cloturer')], default='en_attente', max_length=100, null=True)),
                ('approuved_annulation', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demandes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.demandeinscription')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.formation')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites')),
            ],
            options={
                'verbose_name': 'Demande de paiement',
                'verbose_name_plural': 'Demandes de paiement',
            },
        ),
    ]
