# Generated by Django 5.1.4 on 2025-12-31 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autreproduit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_crm.prospets'),
        ),
    ]
