# Generated by Django 5.1.4 on 2025-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientPaiementsRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
