# Generated by Django 5.1.4 on 2025-05-18 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_alter_specialites_formation'),
        ('t_tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilPaiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(null=True)),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites')),
            ],
        ),
    ]
