# Generated by Django 5.1.4 on 2025-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpaiementsrequest',
            name='paiement_date',
        ),
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('tranche', 'Tranche'), ('mensuelle', 'Mensuelle'), ('totalite', 'Paiement unique')], max_length=100, null=True),
        ),
    ]
