# Generated by Django 5.1.4 on 2026-01-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='depenses',
            name='sous_categorie',
        ),
        migrations.AddField(
            model_name='depenses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.depensescategory'),
        ),
    ]
