# Generated by Django 5.1.4 on 2025-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0002_clientpaiementsrequestline'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En Attente'), ('terminer', 'Cloturer')], max_length=100, null=True),
        ),
    ]
