# Generated by Django 5.1.4 on 2025-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0002_seuilpaiements'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuilpaiements',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
