# Generated by Django 5.1.4 on 2026-01-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0002_autreproduit_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiements',
            name='context',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('autre', 'Autres'), ('dette', 'Module en dette'), ('facture', 'Paiement facture'), ('rach', 'Rachât de crédit')], max_length=100, null=True),
        ),
    ]
