# Generated by Django 5.1.4 on 2025-09-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0002_remises'),
    ]

    operations = [
        migrations.AddField(
            model_name='remises',
            name='taux',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
