# Generated by Django 5.1.4 on 2026-01-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_initial'),
        ('t_tresorerie', '0003_rembourssements_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
    ]
