# Generated by Django 5.1.4 on 2026-01-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_tresorerie', '0003_alter_paiements_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='autreproduit',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institut_app.entreprise'),
        ),
    ]
