# Generated by Django 5.1.4 on 2025-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0003_remises_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='remises',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
