# Generated by Django 5.1.4 on 2025-05-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_alter_specialites_formation'),
        ('t_tresorerie', '0003_seuilpaiements_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seuilpaiements',
            unique_together={('specialite', 'valeur')},
        ),
    ]
