# Generated by Django 5.1.4 on 2026-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0004_autreproduit_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='autreproduit',
            name='num',
            field=models.CharField(blank=True, help_text='Numéro séquentiel de paiement', max_length=100, null=True, unique=True),
        ),
    ]
