# Generated by Django 5.1.4 on 2026-01-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_tresorerie', '0004_depenses_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise'),
        ),
    ]
