# Generated by Django 5.1.4 on 2025-05-19 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0004_alter_seuilpaiements_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuilpaiements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seuilpaiements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
