# Generated by Django 5.1.4 on 2025-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0007_alter_visiteurs_etat'),
        ('t_tresorerie', '0004_alter_clientpaiementsrequest_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpaiementsrequest',
            name='client',
        ),
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='demande_inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.demandeinscription'),
        ),
    ]
