# Generated by Django 5.1.4 on 2025-04-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0005_remove_clientpaiementsrequest_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpaiementsrequest',
            old_name='demande_inscription',
            new_name='demandes',
        ),
    ]
