# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0005_autreproduit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaiementsrequestline',
            name='etat',
            field=models.CharField(blank=True, choices=[('auc', 'Aucun paiement effectué'), ('part', 'Paiement partiel'), ('tot', 'Paiement cash'), ('ter', 'Paiement terminé')], default='auc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequestline',
            name='motif_paiement',
            field=models.CharField(blank=True, choices=[('fin', "Frais d'inscription"), ('ass', 'Assurance'), ('frf', 'Frais de formation')], max_length=100, null=True),
        ),
    ]
