# Generated by Django 5.1.4 on 2025-05-19 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0005_seuilpaiements_created_at_seuilpaiements_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='data_paiement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='motif_paiement',
            field=models.CharField(blank=True, choices=[('frf', 'Frais de formation'), ('de', 'Module en dette'), ('re', 'Régularisation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='paiement_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_tresorerie.clientpaiementsrequest'),
        ),
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
