# Generated by Django 5.1.4 on 2025-09-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0005_echeancierpaiementsepcial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remises',
        ),
    ]
