# Generated by Django 5.1.4 on 2025-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0006_clientpaiementsrequestline_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='etat',
            field=models.CharField(blank=True, choices=[('part', 'Paiement partiel'), ('tot', 'Paiement cash')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequestline',
            name='motif_paiement',
            field=models.CharField(blank=True, choices=[('fin', "Frais d'incription"), ('ass', 'Assurance'), ('frf', 'Frais de formation')], max_length=100, null=True),
        ),
    ]
