# Generated by Django 5.1.4 on 2026-01-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_alter_programmeformation_unique_together'),
        ('t_tresorerie', '0006_promorembourssement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promorembourssement',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos', unique=True),
        ),
    ]
