# Generated by Django 5.1.4 on 2025-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0006_rename_demande_inscription_clientpaiementsrequest_demandes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En Attente'), ('annulation', "Demande d'annulation"), ('terminer', 'Cloturer')], default='en_attente', max_length=100, null=True),
        ),
    ]
