# Generated by Django 5.1.4 on 2025-09-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_partenaires_logo'),
        ('t_tresorerie', '0006_delete_remises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeancierpaiement',
            name='label',
        ),
        migrations.RemoveField(
            model_name='echeancierpaiement',
            name='promo',
        ),
        migrations.CreateModel(
            name='ModelEcheancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos')),
            ],
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.modelecheancier'),
        ),
    ]
