# Generated by Django 5.1.4 on 2025-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0007_alter_clientpaiementsrequest_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='approuved_annulation',
            field=models.BooleanField(default=False),
        ),
    ]
