# Generated by Django 5.1.4 on 2025-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0007_remove_echeancierpaiement_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelecheancier',
            name='nombre_tranche',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
