# Generated by Django 5.1.4 on 2025-05-19 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0007_clientpaiementsrequestline_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='motif',
            field=models.CharField(blank=True, choices=[('frais', "Frais d'admission"), ('autre', 'Autres')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paiements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiements',
            name='data_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiements',
            name='montant_paye',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequestline',
            name='etat',
            field=models.CharField(blank=True, choices=[('auc', 'Aucun paiement effectuer'), ('part', 'Paiement partiel'), ('tot', 'Paiement cash')], default='auc', max_length=100, null=True),
        ),
    ]
