# Generated by Django 5.1.4 on 2026-01-28 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0025_dasmapping'),
        ('t_tresorerie', '0008_alter_promorembourssement_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbancaire',
            name='autre_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettrages', to='t_tresorerie.autreproduit'),
        ),
        migrations.AddField(
            model_name='operationsbancaire',
            name='conseil_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettrages', to='t_conseil.paiement'),
        ),
    ]
