# Generated by Django 5.1.4 on 2025-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0008_clientpaiementsrequest_motif_paiements_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='motif',
            field=models.CharField(blank=True, choices=[('frais', "Frais d'admission"), ('autre', 'Autres'), ('dette', 'Module en dette')], max_length=100, null=True),
        ),
    ]
