# Generated by Django 5.1.4 on 2025-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0008_clientpaiementsrequest_approuved_annulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En Attente'), ('annulation', "Demande d'annulation"), ('annulation_approuver', "Demande d'annulation approuvée"), ('terminer', 'Cloturer')], default='en_attente', max_length=100, null=True),
        ),
    ]
