# Generated by Django 5.1.4 on 2025-09-15 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0008_modelecheancier_nombre_tranche'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelecheancier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelecheancier',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
