# Generated by Django 5.1.4 on 2025-05-20 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0009_paiements_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='paiement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.clientpaiementsrequestline'),
        ),
    ]
