# Generated by Django 5.1.4 on 2026-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0009_operationsbancaire_autre_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='category_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('rachat_credit', 'Rachat de Crédit')], default='standard', max_length=50, verbose_name='Type de Catégorie'),
        ),
    ]
