# Generated by Django 5.1.4 on 2025-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0009_modelecheancier_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelecheancier',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
