# Generated by Django 5.1.4 on 2026-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0010_paymentcategory_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autreproduit',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
    ]
