# Generated by Django 5.1.4 on 2025-05-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0010_paiements_paiement_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiements',
            old_name='data_paiement',
            new_name='date_paiement',
        ),
    ]
