# Generated by Django 5.1.4 on 2025-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0010_modelecheancier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiementline',
            name='montant_tranche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
