# Generated by Django 5.1.4 on 2025-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0010_prospets_has_special_echeancier'),
        ('t_tresorerie', '0011_echeancierpaiementline_montant_tranche'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliquerEcheancierSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validate', models.BooleanField(default=False)),
                ('is_approuved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEcheancierPaiementSepcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_tranche', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='EcheancierPaiementSepcial',
        ),
        migrations.AddField(
            model_name='appliquerecheancierspecial',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.modelecheancierpaiementsepcial'),
        ),
    ]
