# Generated by Django 5.1.4 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0011_alter_autreproduit_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='autreproduit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
