# Generated by Django 5.1.4 on 2025-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0011_rename_data_paiement_paiements_date_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequestline',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
