# Generated by Django 5.1.4 on 2025-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0012_clientpaiementsrequestline_montant_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espece'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequestline',
            name='etat',
            field=models.CharField(blank=True, choices=[('auc', 'Aucun paiement effectuer'), ('part', 'Paiement partiel'), ('tot', 'Paiement cash'), ('ter', 'Paiement terminer')], default='auc', max_length=100, null=True),
        ),
    ]
