# Generated by Django 5.1.4 on 2026-01-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0012_autreproduit_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensescategory',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depense_categories', to='t_tresorerie.paymentcategory'),
        ),
    ]
