# Generated by Django 5.1.4 on 2025-09-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0010_prospets_has_special_echeancier'),
        ('t_tresorerie', '0012_appliquerecheancierspecial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_crm.prospets'),
        ),
    ]
