# Generated by Django 5.1.4 on 2026-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0013_depensescategory_payment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_categories', models.ManyToManyField(related_name='payment_types', to='t_tresorerie.paymentcategory')),
            ],
            options={
                'verbose_name': 'Type de Paiement',
                'verbose_name_plural': 'Types de Paiement',
            },
        ),
    ]
