# Generated by Django 5.1.4 on 2025-09-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0010_prospets_has_special_echeancier'),
        ('t_tresorerie', '0013_alter_clientpaiementsrequest_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliquerecheancierspecial',
            name='model',
        ),
        migrations.RemoveField(
            model_name='appliquerecheancierspecial',
            name='prospect',
        ),
        migrations.CreateModel(
            name='EcheancierSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tranche', models.IntegerField(blank=True, null=True)),
                ('is_validate', models.BooleanField(default=False)),
                ('is_approuved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelEcheancierPaiementSepcial',
        ),
        migrations.DeleteModel(
            name='AppliquerEcheancierSpecial',
        ),
    ]
