# Generated by Django 5.1.4 on 2025-05-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0014_paiements_reference_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remboussements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_rembourssement', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.CharField(blank=True, choices=[('enc', 'En cours de traitement'), ('acp', 'Approuvé'), ('ref', 'Refusé')], default='enc', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paiements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.paiements')),
            ],
        ),
    ]
