# Generated by Django 5.1.4 on 2026-03-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0014_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.paymenttype'),
        ),
    ]
