# Generated by Django 5.1.4 on 2026-03-07 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0006_notification'),
        ('t_tresorerie', '0015_paiements_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
    ]
