# Generated by Django 5.1.4 on 2025-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0015_clientpaiementsrequest_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='motif',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('frais', "Frais d'admission"), ('autre', 'Autres'), ('dette', 'Module en dette')], max_length=100, null=True),
        ),
    ]
