# Generated by Django 5.1.4 on 2025-05-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0015_remboussements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remboussements',
            new_name='Rembourssements',
        ),
    ]
