# Generated by Django 5.1.4 on 2025-05-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0016_rename_remboussements_rembourssements'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembourssements',
            name='is_approuved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rembourssements',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
