# Generated by Django 5.1.4 on 2025-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0016_alter_clientpaiementsrequest_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
