# Generated by Django 5.1.4 on 2026-03-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0027_facture_module_source'),
        ('t_tresorerie', '0016_paiements_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tresorerie_paiements', to='t_conseil.facture'),
        ),
    ]
