# Generated by Django 5.1.4 on 2026-03-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0017_paiements_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autreproduit',
            name='compte',
        ),
        migrations.AddField(
            model_name='autreproduit',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.paymenttype'),
        ),
    ]
