# Generated by Django 5.1.4 on 2025-05-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_initial'),
        ('t_tresorerie', '0017_rembourssements_is_approuved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpaiementsrequest',
            name='demandes',
        ),
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_crm.visiteurs'),
        ),
    ]
