# Generated by Django 5.1.4 on 2025-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0017_echeancierpaiement_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiements',
            name='paiement_line',
        ),
    ]
