# Generated by Django 5.1.4 on 2026-03-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0018_remove_autreproduit_compte_autreproduit_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensescategory',
            name='global_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='global_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='global_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
