# Generated by Django 5.1.4 on 2025-05-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0018_remove_clientpaiementsrequest_demandes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='etat',
            field=models.CharField(blank=True, choices=[('val', 'Valider'), ('dmr', 'Demande de remboursement'), ('rem', 'Rembourssement approuvé')], default='val', max_length=100, null=True),
        ),
    ]
