# Generated by Django 5.1.4 on 2025-09-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0018_remove_paiements_paiement_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiements',
            name='etat',
        ),
    ]
