# Generated by Django 5.1.4 on 2025-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0019_remove_paiements_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiements',
            name='is_frais_inscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiements',
            name='paiement_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Numéro séquentiel de paiement', max_length=100, null=True, unique=True),
        ),
    ]
