# Generated by Django 5.1.4 on 2026-03-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0006_notification'),
        ('t_tresorerie', '0019_depensescategory_global_id_paymentcategory_global_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierspecial',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True),
        ),
    ]
