# Generated by Django 5.1.4 on 2026-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0020_echeancierspecial_entite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloquer_date_paiement', models.BooleanField(default=True, help_text="Si activé, la date de paiement dans le modal d'enregistrement est pré-remplie avec la date du jour et verrouillée. Si désactivé, l'agent peut choisir librement la date.", verbose_name='Bloquer la date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre Financier',
                'verbose_name_plural': 'Paramètres Financiers',
            },
        ),
    ]
