# Generated by Django 5.1.4 on 2025-09-18 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0020_paiements_is_done_paiements_is_frais_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='date_echeancier',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='echeancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.echeancierspecial'),
        ),
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='montant_tranche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='taux',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
