# Generated by Django 5.1.4 on 2026-04-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_alter_promos_session'),
        ('t_tresorerie', '0021_parametrefinancier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promorembourssement',
            name='promo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos'),
        ),
    ]
