# Generated by Django 5.1.4 on 2025-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0021_echeancierpaiementspecialline_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuePaiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_echeancier', models.CharField(blank=True, max_length=1000, null=True)),
                ('montant_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
