# Generated by Django 5.1.4 on 2026-04-24 15:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0022_passwordresetrequest'),
        ('t_tresorerie', '0022_alter_promorembourssement_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('caisse', 'Caisse'), ('banque', 'Banque')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('annee_scolaire', models.IntegerField(help_text="L'année de début de l'année scolaire (ex: 2023 pour 2023/2024)")),
                ('date_solde', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise')),
            ],
            options={
                'verbose_name': 'Solde Initial',
                'verbose_name_plural': 'Soldes Initiaux',
                'unique_together': {('type', 'annee_scolaire', 'entite')},
            },
        ),
    ]
