# Generated by Django 5.1.4 on 2025-09-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0012_alter_derogations_date_de_traitement'),
        ('t_tresorerie', '0023_duepaiements_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='due_paiements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.duepaiements'),
        ),
        migrations.AddField(
            model_name='paiements',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
    ]
