# Generated by Django 5.1.4 on 2026-04-24 15:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0022_passwordresetrequest'),
        ('t_tresorerie', '0023_soldeinitial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotBanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, help_text='Numéro séquentiel de remise de fonds', max_length=100, null=True, unique=True)),
                ('date_depot', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('agent_remettant', models.CharField(help_text="Nom de la personne qui dépose l'argent", max_length=255)),
                ('reference_bordereau', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banque_destinatrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.bankaccount')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise')),
            ],
            options={
                'verbose_name': 'Dépôt en Banque',
                'verbose_name_plural': 'Dépôts en Banque',
            },
        ),
    ]
