# Generated by Django 5.1.4 on 2025-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0024_paiements_due_paiements_paiements_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='num',
            field=models.CharField(blank=True, help_text='Numéro séquentiel de paiement', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
