# Generated by Django 5.1.4 on 2026-04-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0008_dossierinscription_include_in_tracking'),
        ('t_tresorerie', '0024_depotbanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites'),
        ),
    ]
