# Generated by Django 5.1.4 on 2026-04-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0025_echeancierpaiement_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='ref_echeancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.echeancierpaiement'),
        ),
    ]
