# Generated by Django 5.1.4 on 2025-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0025_paiements_num_alter_paiements_reference_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
