# Generated by Django 5.1.4 on 2026-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0026_clientpaiementsrequest_ref_echeancier'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensescategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
