# Generated by Django 5.1.4 on 2025-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0026_duepaiements_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
