# Generated by Django 5.1.4 on 2025-09-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0012_alter_derogations_date_de_traitement'),
        ('t_tresorerie', '0027_duepaiements_montant_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembourssements',
            name='allowed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rembourssements',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
    ]
