# Generated by Django 5.1.4 on 2026-05-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0027_depensescategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
