# Generated by Django 5.1.4 on 2026-05-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0028_echeancierpaiement_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='type_remise',
            field=models.CharField(choices=[('fixe', 'Montant Fixe'), ('pourcentage', 'Pourcentage')], default='fixe', max_length=20),
        ),
    ]
