# Generated by Django 5.1.4 on 2025-09-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0028_rembourssements_allowed_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rembourssements',
            name='paiements',
        ),
    ]
