# Generated by Django 5.1.4 on 2026-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0029_echeancierpaiement_type_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='majoration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='type_majoration',
            field=models.CharField(choices=[('fixe', 'Montant Fixe'), ('pourcentage', 'Pourcentage')], default='fixe', max_length=20),
        ),
    ]
