# Generated by Django 5.1.4 on 2025-09-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0029_remove_rembourssements_paiements'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='t_tresorerie.paiements')),
                ('remboursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_rembourses', to='t_tresorerie.rembourssements')),
            ],
        ),
    ]
