# Generated by Django 5.1.4 on 2025-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0030_paiementremboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='context',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('autre', 'Autres'), ('dette', 'Module en dette')], max_length=100, null=True),
        ),
    ]
