# Generated by Django 5.1.4 on 2026-05-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0030_echeancierpaiement_majoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='has_majoration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='has_remise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='tarif_formation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='has_majoration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='has_remise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='majoration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='tarif_formation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='type_majoration',
            field=models.CharField(choices=[('fixe', 'Montant Fixe'), ('pourcentage', 'Pourcentage')], default='fixe', max_length=20),
        ),
        migrations.AddField(
            model_name='echeancierspecial',
            name='type_remise',
            field=models.CharField(choices=[('fixe', 'Montant Fixe'), ('pourcentage', 'Pourcentage')], default='fixe', max_length=20),
        ),
    ]
