# Generated by Django 5.1.4 on 2025-09-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0012_alter_derogations_date_de_traitement'),
        ('t_tresorerie', '0031_paiements_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremboursement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
    ]
