# Generated by Django 5.1.4 on 2026-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0031_echeancierpaiement_has_majoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrefinancier',
            name='activer_timbre',
            field=models.BooleanField(default=False, help_text='Activer le calcul automatique du droit de timbre (1% pour les paiements en espèces).', verbose_name='Activer les droits de timbre'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='taux_timbre',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Taux du timbre (%)'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='timbre_cash_only',
            field=models.BooleanField(default=True, help_text="Si activé, le timbre ne s'applique qu'aux paiements marqués comme 'Espèce'.", verbose_name='Uniquement pour les espèces'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='timbre_max',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10, verbose_name='Montant maximum (DA)'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='timbre_min',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Montant minimum (DA)'),
        ),
    ]
