# Generated by Django 5.1.4 on 2025-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0032_paiementremboursement_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremboursement',
            name='date_remboursement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementremboursement',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
    ]
