# Generated by Django 5.1.4 on 2025-09-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0033_paiementremboursement_date_remboursement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rembourssements',
            old_name='is_approuved',
            new_name='is_done',
        ),
    ]
