# Generated by Django 5.1.4 on 2026-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0033_parametrefinancier_relance_echeancier_corps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='has_printed_quittance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiements',
            name='quittance_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiements',
            name='quittance_printed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='relance_echeancier_corps',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Rappel de Paiement</title>\n</head>\n<body style="margin: 0; padding: 0; font-family: \'Segoe UI\', Helvetica, Arial, sans-serif; background-color: #f8fafc; color: #334155;">\n    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; padding: 40px 10px;">\n        <tr>\n            <td align="center">\n                <table width="600" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03); overflow: hidden;">\n                    <!-- Header -->\n                    <tr>\n                        <td style="background: linear-gradient(135deg, #1e3a8a 0%, #0d9488 100%); padding: 35px 40px; text-align: left;">\n                            <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px;">Rappel d\'échéance de paiement</h1>\n                            <p style="color: #e2e8f0; margin: 5px 0 0 0; font-size: 14px;">{tenant_name} - Service Trésorerie</p>\n                        </td>\n                    </tr>\n                    <!-- Body -->\n                    <tr>\n                        <td style="padding: 40px;">\n                            <h2 style="color: #0f172a; margin-top: 0; margin-bottom: 20px; font-size: 18px; font-weight: 600;">Bonjour {nom} {prenom},</h2>\n                            <p style="line-height: 1.6; color: #475569; font-size: 15px; margin-bottom: 25px;">\n                                Nous vous contactons pour vous rappeler que votre échéancier de paiement de formation présente une ou plusieurs échéances en attente de régularisation.\n                            </p>\n                            \n                            <!-- Table structure -->\n                            <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse: collapse; margin-bottom: 25px;">\n                                <thead>\n                                    <tr style="background-color: #f1f5f9;">\n                                        <th style="padding: 12px; font-weight: 600; text-align: left; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Échéance</th>\n                                        <th style="padding: 12px; font-weight: 600; text-align: left; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Date d\'échéance</th>\n                                        <th style="padding: 12px; font-weight: 600; text-align: right; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Montant dû</th>\n                                        <th style="padding: 12px; font-weight: 600; text-align: right; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Reste à payer</th>\n                                    </tr>\n                                </thead>\n                                <tbody>\n                                    {table_rows}\n                                </tbody>\n                            </table>\n\n                            <!-- Summary Banner -->\n                            <div style="background-color: #fff1f2; border-left: 4px solid #f43f5e; padding: 15px 20px; border-radius: 6px; margin-bottom: 30px;">\n                                <table width="100%" border="0" cellpadding="0" cellspacing="0">\n                                    <tr>\n                                        <td style="color: #9f1239; font-size: 15px; font-weight: 600;">Total restant à payer :</td>\n                                        <td style="color: #be123c; font-size: 18px; font-weight: 700; text-align: right;">{total_remaining} DA</td>\n                                    </tr>\n                                </table>\n                            </div>\n\n                            <p style="line-height: 1.6; color: #475569; font-size: 15px; margin-bottom: 25px;">\n                                Nous vous prions de bien vouloir procéder à la régularisation de ces montants dans les plus brefs délais auprès de notre service comptabilité.\n                            </p>\n                            \n                            <p style="line-height: 1.6; color: #64748b; font-size: 13px; font-style: italic; border-top: 1px solid #e2e8f0; padding-top: 20px;">\n                                Si vous avez déjà procédé à ce paiement récemment, merci de ne pas tenir compte de ce message ou de nous transmettre votre reçu de paiement pour mise à jour de votre dossier.\n                            </p>\n                        </td>\n                    </tr>\n                    <!-- Footer -->\n                    <tr>\n                        <td style="background-color: #f1f5f9; padding: 25px 40px; text-align: center; font-size: 12px; color: #94a3b8;">\n                            <p style="margin: 0 0 5px 0;">Ce courriel a été généré automatiquement par {tenant_name}.</p>\n                            <p style="margin: 0;">© {annee_courante} Tous droits réservés.</p>\n                        </td>\n                    </tr>\n                </table>\n            </td>\n        </tr>\n    </table>\n</body>\n</html>', verbose_name="Corps de l'email de relance (HTML)"),
        ),
    ]
