# Generated by Django 5.1.4 on 2025-09-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0012_alter_derogations_date_de_traitement'),
        ('t_tresorerie', '0034_rename_is_approuved_rembourssements_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiements',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='t_crm.prospets'),
        ),
    ]
