# Generated by Django 5.1.4 on 2026-05-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0034_paiements_has_printed_quittance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrefinancier',
            name='timbre_bareme',
            field=models.TextField(default='[{"min_ttc": 0, "max_ttc": 300, "rate": 0.0, "is_exempt": true}, {"min_ttc": 301, "max_ttc": 30000, "rate": 1.0, "is_exempt": false}, {"min_ttc": 30001, "max_ttc": 100000, "rate": 1.5, "is_exempt": false}, {"min_ttc": 100001, "max_ttc": null, "rate": 2.0, "is_exempt": false}]', help_text="Liste ordonnée de tranches progressives avec min, max, taux et statut d'exonération au format JSON.", verbose_name='Barème progressif des droits de timbre (JSON)'),
        ),
    ]
