# Generated by Django 5.1.4 on 2026-05-20 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0035_parametrefinancier_timbre_bareme'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.paymenttype'),
        ),
    ]
