# Generated by Django 5.1.4 on 2025-09-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0009_remove_formation_frais_assurance'),
        ('t_tresorerie', '0035_alter_paiements_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_paiements', to='t_formations.promos'),
        ),
    ]
