# Generated by Django 5.1.4 on 2026-05-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0036_duepaiements_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyGlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalite_retard', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pénalité de retard')),
                ('prix_rachat_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix de rachat de crédit')),
                ('frais_duplicata', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de duplicata')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frais_duplicata_payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_duplicata_configs', to='t_tresorerie.paymenttype')),
                ('penalite_retard_payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalite_retard_configs', to='t_tresorerie.paymenttype')),
                ('prix_rachat_credit_payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix_rachat_credit_configs', to='t_tresorerie.paymenttype')),
            ],
            options={
                'verbose_name': 'Configuration Globale des Pénalités',
                'verbose_name_plural': 'Configurations Globales des Pénalités',
            },
        ),
    ]
