# Generated by Django 5.1.4 on 2025-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0036_paiements_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
