# Generated by Django 5.1.4 on 2026-05-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0037_facture_montant_timbre'),
        ('t_tresorerie', '0037_penaltyglobalconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembourssements',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='t_conseil.facture'),
        ),
    ]
