# Generated by Django 5.1.4 on 2025-09-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0037_duepaiements_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembourssements',
            name='mode_rembourssement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
    ]
