# Generated by Django 5.1.4 on 2025-09-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0038_rembourssements_mode_rembourssement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
