# Generated by Django 5.1.4 on 2026-05-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0038_rembourssements_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='date_depense',
            field=models.DateField(blank=True, null=True),
        ),
    ]
