# Generated by Django 5.1.4 on 2025-09-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0039_paiements_is_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='refund_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.rembourssements'),
        ),
        migrations.AddField(
            model_name='rembourssements',
            name='is_appliced',
            field=models.BooleanField(default=False),
        ),
    ]
