# Generated by Django 5.1.4 on 2026-05-31 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0039_depenses_date_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrefinancier',
            name='compte_timbre',
            field=models.ForeignKey(blank=True, help_text="Compte du plan comptable utilisé pour l'imputation des droits de timbre", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre', to='t_tresorerie.plancomptable', verbose_name='Compte Droit de Timbre'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='compte_tva',
            field=models.ForeignKey(blank=True, help_text="Compte du plan comptable utilisé pour l'imputation de la TVA", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva', to='t_tresorerie.plancomptable', verbose_name='Compte TVA'),
        ),
    ]
