# Generated by Django 5.1.4 on 2025-09-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0009_remove_formation_frais_assurance'),
        ('t_tresorerie', '0040_paiements_refund_id_rembourssements_is_appliced'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos'),
        ),
    ]
