# Generated by Django 5.1.4 on 2026-05-31 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0040_parametrefinancier_compte_timbre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrefinancier',
            name='compte_timbre',
        ),
        migrations.RemoveField(
            model_name='parametrefinancier',
            name='compte_tva',
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='compte_timbre_charge',
            field=models.ForeignKey(blank=True, help_text="Compte du plan comptable utilisé pour l'imputation des droits de timbre payés (ex: 64/635)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre_charge', to='t_tresorerie.plancomptable', verbose_name='Compte Droit de Timbre Charge (Dépenses)'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='compte_timbre_collecte',
            field=models.ForeignKey(blank=True, help_text="Compte du plan comptable utilisé pour l'imputation des droits de timbre collectés (ex: 447)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre_collecte', to='t_tresorerie.plancomptable', verbose_name='Compte Droit de Timbre Collecté (Recettes)'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='compte_tva_collectee',
            field=models.ForeignKey(blank=True, help_text="Compte du plan comptable utilisé pour l'imputation de la TVA sur les factures clients (ex: 4457)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva_collectee', to='t_tresorerie.plancomptable', verbose_name='Compte TVA Collectée (Recettes)'),
        ),
        migrations.AddField(
            model_name='parametrefinancier',
            name='compte_tva_deductible',
            field=models.ForeignKey(blank=True, help_text="Compte du plan comptable utilisé pour l'imputation de la TVA sur les achats fournisseurs (ex: 4456)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva_deductible', to='t_tresorerie.plancomptable', verbose_name='Compte TVA Déductible (Dépenses)'),
        ),
    ]
