# Generated by Django 5.1.4 on 2026-05-31 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0041_remove_parametrefinancier_compte_timbre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_timbre_charge',
            field=models.ForeignKey(blank=True, help_text='Type de dépense utilisé pour les droits de timbre payés', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre_charge', to='t_tresorerie.depensescategory', verbose_name='Type Dépense Droit de Timbre'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_timbre_collecte',
            field=models.ForeignKey(blank=True, help_text='Catégorie de recette utilisée pour les droits de timbre collectés', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre_collecte', to='t_tresorerie.paymentcategory', verbose_name='Catégorie Recette Droit de Timbre'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_tva_collectee',
            field=models.ForeignKey(blank=True, help_text='Catégorie de recette utilisée pour la TVA sur les factures clients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva_collectee', to='t_tresorerie.paymentcategory', verbose_name='Catégorie Recette TVA Collectée'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_tva_deductible',
            field=models.ForeignKey(blank=True, help_text='Type de dépense utilisé pour la TVA sur les achats fournisseurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva_deductible', to='t_tresorerie.depensescategory', verbose_name='Type Dépense TVA Déductible'),
        ),
    ]
