# Generated by Django 5.1.4 on 2025-09-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0009_remove_formation_frais_assurance'),
        ('t_tresorerie', '0041_duepaiements_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duepaiements',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_paiement_promo', to='t_formations.promos'),
        ),
    ]
