# Generated by Django 5.1.4 on 2026-06-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0042_alter_parametrefinancier_compte_timbre_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelecheancier',
            name='has_frais_inscription',
            field=models.BooleanField(default=False),
        ),
    ]
