# Generated by Django 5.1.4 on 2025-09-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0042_alter_duepaiements_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='is_annulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='refund_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.rembourssements'),
        ),
    ]
