# Generated by Django 5.1.4 on 2026-06-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0043_modelecheancier_has_frais_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='timbre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DepenseLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tva', models.DecimalField(decimal_places=2, default=0, help_text='Taux de TVA en %', max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.depensescategory')),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='t_tresorerie.depenses')),
            ],
        ),
    ]
