# Generated by Django 5.1.4 on 2025-09-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0043_duepaiements_is_annulated_alter_paiements_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='duepaiements',
            name='type',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('dette', 'Module en dette'), ('autre', 'Autre')], max_length=100, null=True),
        ),
    ]
