# Generated by Django 5.1.4 on 2026-06-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0044_depenses_timbre_depenseligne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='category',
        ),
    ]
