# Generated by Django 5.1.4 on 2025-09-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0044_duepaiements_observation_duepaiements_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duepaiements',
            name='ref_echeancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.echeancierpaiement'),
        ),
    ]
