# Generated by Django 5.1.4 on 2025-10-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0045_alter_duepaiements_ref_echeancier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiements',
            name='context',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('autre', 'Autres'), ('dette', 'Module en dette'), ('facture', 'Paiement facture')], max_length=100, null=True),
        ),
    ]
