# Generated by Django 5.1.4 on 2026-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0045_remove_depenses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='reference_document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
