# Generated by Django 5.1.4 on 2026-06-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0046_depenses_reference_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbancaire',
            name='remboursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettrages', to='t_tresorerie.rembourssements'),
        ),
    ]
