# Generated by Django 5.1.4 on 2026-06-11 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0047_operationsbancaire_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembourssements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements', to='t_tresorerie.depensescategory'),
        ),
    ]
