# Generated by Django 5.1.4 on 2026-06-11 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0032_remove_entreprise_quittance_prefix_and_more'),
        ('t_tresorerie', '0048_rembourssements_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depotbanque',
            options={'verbose_name': 'DÃ©pÃ´t en Banque', 'verbose_name_plural': 'DÃ©pÃ´ts en Banque'},
        ),
        migrations.AlterModelOptions(
            name='parametrefinancier',
            options={'verbose_name': 'ParamÃ¨tre Financier', 'verbose_name_plural': 'ParamÃ¨tres Financiers'},
        ),
        migrations.AlterModelOptions(
            name='penaltyglobalconfiguration',
            options={'verbose_name': 'Configuration Globale des PÃ©nalitÃ©s', 'verbose_name_plural': 'Configurations Globales des PÃ©nalitÃ©s'},
        ),
        migrations.AlterField(
            model_name='autreproduit',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'ChÃ¨que'), ('esp', 'EspÃ¨ce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autreproduit',
            name='num',
            field=models.CharField(blank=True, help_text='NumÃ©ro sÃ©quentiel de paiement', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En Attente'), ('annulation', "Demande d'annulation"), ('annulation_approuver', "Demande d'annulation approuvÃ©e"), ('terminer', 'Cloturer')], default='en_attente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='motif',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('frais', "Frais d'admission"), ('autre', 'Autres'), ('dette', 'Module en dette'), ('rach', 'RachÃ¢t de crÃ©dit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaiementsrequestline',
            name='etat',
            field=models.CharField(blank=True, choices=[('auc', 'Aucun paiement effectuÃ©'), ('part', 'Paiement partiel'), ('tot', 'Paiement cash'), ('ter', 'Paiement terminÃ©')], default='auc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'ChÃ¨que'), ('esp', 'EspÃ¨ce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depotbanque',
            name='agent_remettant',
            field=models.CharField(help_text="Nom de la personne qui dÃ©pose l'argent", max_length=255),
        ),
        migrations.AlterField(
            model_name='depotbanque',
            name='num',
            field=models.CharField(blank=True, help_text='NumÃ©ro sÃ©quentiel de remise de fonds', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='duepaiements',
            name='type',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('dette', 'Module en dette'), ('autre', 'Autre'), ('rach', 'RachÃ¢t de crÃ©dit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationsbancaire',
            name='operation_type',
            field=models.CharField(choices=[('entree', 'Encaissement'), ('sortie', 'DÃ©caissement')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paiementremboursement',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'ChÃ¨que'), ('esp', 'EspÃ¨ce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='context',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('autre', 'Autres'), ('dette', 'Module en dette'), ('facture', 'Paiement facture'), ('rach', 'RachÃ¢t de crÃ©dit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'ChÃ¨que'), ('esp', 'EspÃ¨ce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='num',
            field=models.CharField(blank=True, help_text='NumÃ©ro sÃ©quentiel de paiement', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='activer_timbre',
            field=models.BooleanField(default=False, help_text='Activer le calcul automatique du droit de timbre (1% pour les paiements en espÃ¨ces).', verbose_name='Activer les droits de timbre'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='bloquer_date_paiement',
            field=models.BooleanField(default=True, help_text="Si activÃ©, la date de paiement dans le modal d'enregistrement est prÃ©-remplie avec la date du jour et verrouillÃ©e. Si dÃ©sactivÃ©, l'agent peut choisir librement la date.", verbose_name='Bloquer la date de paiement'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_timbre_charge',
            field=models.ForeignKey(blank=True, help_text='Type de dÃ©pense utilisÃ© pour les droits de timbre payÃ©s', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre_charge', to='t_tresorerie.depensescategory', verbose_name='Type DÃ©pense Droit de Timbre'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_timbre_collecte',
            field=models.ForeignKey(blank=True, help_text='CatÃ©gorie de recette utilisÃ©e pour les droits de timbre collectÃ©s', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_timbre_collecte', to='t_tresorerie.paymentcategory', verbose_name='CatÃ©gorie Recette Droit de Timbre'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_tva_collectee',
            field=models.ForeignKey(blank=True, help_text='CatÃ©gorie de recette utilisÃ©e pour la TVA sur les factures clients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva_collectee', to='t_tresorerie.paymentcategory', verbose_name='CatÃ©gorie Recette TVA CollectÃ©e'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='compte_tva_deductible',
            field=models.ForeignKey(blank=True, help_text='Type de dÃ©pense utilisÃ© pour la TVA sur les achats fournisseurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_tva_deductible', to='t_tresorerie.depensescategory', verbose_name='Type DÃ©pense TVA DÃ©ductible'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='relance_echeancier_corps',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Rappel de Paiement</title>\n</head>\n<body style="margin: 0; padding: 0; font-family: \'Segoe UI\', Helvetica, Arial, sans-serif; background-color: #f8fafc; color: #334155;">\n    <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; padding: 40px 10px;">\n        <tr>\n            <td align="center">\n                <table width="600" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03); overflow: hidden;">\n                    <!-- Header -->\n                    <tr>\n                        <td style="background: linear-gradient(135deg, #1e3a8a 0%, #0d9488 100%); padding: 35px 40px; text-align: left;">\n                            <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px;">Rappel d\'Ã©chÃ©ance de paiement</h1>\n                            <p style="color: #e2e8f0; margin: 5px 0 0 0; font-size: 14px;">{tenant_name} - Service TrÃ©sorerie</p>\n                        </td>\n                    </tr>\n                    <!-- Body -->\n                    <tr>\n                        <td style="padding: 40px;">\n                            <h2 style="color: #0f172a; margin-top: 0; margin-bottom: 20px; font-size: 18px; font-weight: 600;">Bonjour {nom} {prenom},</h2>\n                            <p style="line-height: 1.6; color: #475569; font-size: 15px; margin-bottom: 25px;">\n                                Nous vous contactons pour vous rappeler que votre Ã©chÃ©ancier de paiement de formation prÃ©sente une ou plusieurs Ã©chÃ©ances en attente de rÃ©gularisation.\n                            </p>\n                            \n                            <!-- Table structure -->\n                            <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse: collapse; margin-bottom: 25px;">\n                                <thead>\n                                    <tr style="background-color: #f1f5f9;">\n                                        <th style="padding: 12px; font-weight: 600; text-align: left; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Ã\x89chÃ©ance</th>\n                                        <th style="padding: 12px; font-weight: 600; text-align: left; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Date d\'Ã©chÃ©ance</th>\n                                        <th style="padding: 12px; font-weight: 600; text-align: right; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Montant dÃ»</th>\n                                        <th style="padding: 12px; font-weight: 600; text-align: right; color: #475569; font-size: 13px; border-bottom: 2px solid #cbd5e1;">Reste Ã\xa0 payer</th>\n                                    </tr>\n                                </thead>\n                                <tbody>\n                                    {table_rows}\n                                </tbody>\n                            </table>\n\n                            <!-- Summary Banner -->\n                            <div style="background-color: #fff1f2; border-left: 4px solid #f43f5e; padding: 15px 20px; border-radius: 6px; margin-bottom: 30px;">\n                                <table width="100%" border="0" cellpadding="0" cellspacing="0">\n                                    <tr>\n                                        <td style="color: #9f1239; font-size: 15px; font-weight: 600;">Total restant Ã\xa0 payer :</td>\n                                        <td style="color: #be123c; font-size: 18px; font-weight: 700; text-align: right;">{total_remaining} DA</td>\n                                    </tr>\n                                </table>\n                            </div>\n\n                            <p style="line-height: 1.6; color: #475569; font-size: 15px; margin-bottom: 25px;">\n                                Nous vous prions de bien vouloir procÃ©der Ã\xa0 la rÃ©gularisation de ces montants dans les plus brefs dÃ©lais auprÃ¨s de notre service comptabilitÃ©.\n                            </p>\n                            \n                            <p style="line-height: 1.6; color: #64748b; font-size: 13px; font-style: italic; border-top: 1px solid #e2e8f0; padding-top: 20px;">\n                                Si vous avez dÃ©jÃ\xa0 procÃ©dÃ© Ã\xa0 ce paiement rÃ©cemment, merci de ne pas tenir compte de ce message ou de nous transmettre votre reÃ§u de paiement pour mise Ã\xa0 jour de votre dossier.\n                            </p>\n                        </td>\n                    </tr>\n                    <!-- Footer -->\n                    <tr>\n                        <td style="background-color: #f1f5f9; padding: 25px 40px; text-align: center; font-size: 12px; color: #94a3b8;">\n                            <p style="margin: 0 0 5px 0;">Ce courriel a Ã©tÃ© gÃ©nÃ©rÃ© automatiquement par {tenant_name}.</p>\n                            <p style="margin: 0;">Â© {annee_courante} Tous droits rÃ©servÃ©s.</p>\n                        </td>\n                    </tr>\n                </table>\n            </td>\n        </tr>\n    </table>\n</body>\n</html>', verbose_name="Corps de l'email de relance (HTML)"),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='relance_echeancier_sujet',
            field=models.CharField(default='Rappel de paiement - Ã\x89chÃ©ancier de formation - {nom} {prenom}', max_length=255, verbose_name="Sujet de l'email de relance"),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='timbre_bareme',
            field=models.TextField(default='[{"min_ttc": 0, "max_ttc": 300, "rate": 0.0, "is_exempt": true}, {"min_ttc": 301, "max_ttc": 30000, "rate": 1.0, "is_exempt": false}, {"min_ttc": 30001, "max_ttc": 100000, "rate": 1.5, "is_exempt": false}, {"min_ttc": 100001, "max_ttc": null, "rate": 2.0, "is_exempt": false}]', help_text="Liste ordonnÃ©e de tranches progressives avec min, max, taux et statut d'exonÃ©ration au format JSON.", verbose_name='BarÃ¨me progressif des droits de timbre (JSON)'),
        ),
        migrations.AlterField(
            model_name='parametrefinancier',
            name='timbre_cash_only',
            field=models.BooleanField(default=True, help_text="Si activÃ©, le timbre ne s'applique qu'aux paiements marquÃ©s comme 'EspÃ¨ce'.", verbose_name='Uniquement pour les espÃ¨ces'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='category_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('rachat_credit', 'Rachat de CrÃ©dit')], default='standard', max_length=50, verbose_name='Type de CatÃ©gorie'),
        ),
        migrations.AlterField(
            model_name='penaltyglobalconfiguration',
            name='penalite_retard',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='PÃ©nalitÃ© de retard'),
        ),
        migrations.AlterField(
            model_name='penaltyglobalconfiguration',
            name='prix_rachat_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix de rachat de crÃ©dit'),
        ),
        migrations.AlterField(
            model_name='rembourssements',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours de traitement'), ('acp', 'ApprouvÃ©'), ('ref', 'RefusÃ©')], default='enc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rembourssements',
            name='mode_rembourssement',
            field=models.CharField(blank=True, choices=[('che', 'ChÃ¨que'), ('esp', 'EspÃ¨ce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soldeinitial',
            name='annee_scolaire',
            field=models.IntegerField(help_text="L'annÃ©e de dÃ©but de l'annÃ©e scolaire (ex: 2023 pour 2023/2024)"),
        ),
        migrations.CreateModel(
            name='ReglementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reglement', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='institut_app.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_affecte', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='t_tresorerie.depenses')),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_payees', to='t_tresorerie.reglementfournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFournisseurMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('banque', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=255, null=True)),
                ('etat_cheque', models.CharField(blank=True, choices=[('emis', 'Émis'), ('signature', 'En attente de signature'), ('remis', 'Remis au fournisseur'), ('decaisse', 'Décaissé')], max_length=50, null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_remise', models.DateField(blank=True, null=True)),
                ('date_encaissement', models.DateField(blank=True, null=True)),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_paiement', to='t_tresorerie.reglementfournisseur')),
            ],
        ),
    ]
