# Generated by Django 5.1.4 on 2025-11-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0049_typedepense'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedepense',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
