# Generated by Django 5.1.4 on 2026-06-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0049_alter_depotbanque_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementremboursement',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='context',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('autre', 'Autres'), ('dette', 'Module en dette'), ('facture', 'Paiement facture'), ('rach', 'Rachat de crédit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiements',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rembourssements',
            name='etat',
            field=models.CharField(blank=True, choices=[('enc', 'En cours de traitement'), ('acp', 'Approuvé'), ('ref', 'Refusé')], default='enc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rembourssements',
            name='mode_rembourssement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SuiviChequeSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('emis', 'Emis'), ('attente_signature', 'En attente de signature'), ('remis', 'Remis au client/fournisseur'), ('decaisse', 'Décaissé')], default='emis', max_length=50)),
                ('date_emis', models.DateTimeField(auto_now_add=True)),
                ('date_attente_signature', models.DateTimeField(blank=True, null=True)),
                ('date_remis', models.DateTimeField(blank=True, null=True)),
                ('date_decaisse', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_cheque', to='t_tresorerie.operationsbancaire')),
            ],
        ),
    ]
