# Generated by Django 5.1.4 on 2026-06-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0050_alter_paiementremboursement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivichequesortant',
            name='operation',
        ),
        migrations.AddField(
            model_name='suivichequesortant',
            name='depense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_cheque', to='t_tresorerie.depenses'),
        ),
        migrations.AddField(
            model_name='suivichequesortant',
            name='remboursement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_cheque', to='t_tresorerie.rembourssements'),
        ),
    ]
