# Generated by Django 5.1.4 on 2025-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0050_typedepense_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousTypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
