# Generated by Django 5.1.4 on 2026-06-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0051_remove_suivichequesortant_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autreproduit',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='autreproduit',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_tresorerie.paymentcategory'),
        ),
    ]
