# Generated by Django 5.1.4 on 2025-11-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0051_soustypedepense'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustypedepense',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soustypedepense',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soustypedepense',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soustypedepense',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.typedepense'),
        ),
        migrations.AddField(
            model_name='soustypedepense',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
