# Generated by Django 5.1.4 on 2026-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0052_remove_autreproduit_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivichequesortant',
            name='statut',
            field=models.CharField(choices=[('emis', 'Emis'), ('attente_signature', 'En attente de signature'), ('remis', 'Remis au client/fournisseur'), ('decaisse', 'Décaissé'), ('en_attente', 'En attente'), ('effectue', 'Virement effectué')], default='emis', max_length=50),
        ),
    ]
