# Generated by Django 5.1.4 on 2025-11-14 11:16

import django.db.models.deletion
import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0018_fournisseur_site_web'),
        ('t_tresorerie', '0052_soustypedepense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.typedepense'),
        ),
        migrations.AddField(
            model_name='depenses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='fournissuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.fournisseur'),
        ),
        migrations.AddField(
            model_name='depenses',
            name='montant_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='piece',
            field=models.FileField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_piece_depanse),
        ),
        migrations.AddField(
            model_name='depenses',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.soustypedepense'),
        ),
        migrations.AddField(
            model_name='depenses',
            name='tva',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
