# Generated by Django 5.1.4 on 2026-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0053_alter_suivichequesortant_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='date_frais_inscription',
            field=models.DateField(blank=True, null=True),
        ),
    ]
