# Generated by Django 5.1.4 on 2025-11-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0053_depenses_categorie_depenses_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depenses',
            old_name='fournissuer',
            new_name='fournisseur',
        ),
    ]
