# Generated by Django 5.1.4 on 2026-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0054_echeancierpaiement_date_frais_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrefinancier',
            name='activer_ticket_caisse',
            field=models.BooleanField(default=False, help_text="Activer l'option pour imprimer les reçus de paiement au format ticket de caisse thermique 80mm.", verbose_name="Activer l'impression du ticket de caisse (80mm)"),
        ),
    ]
