# Generated by Django 5.1.4 on 2025-11-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0054_rename_fournissuer_depenses_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='montant',
        ),
    ]
