# Generated by Django 5.1.4 on 2026-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0055_parametrefinancier_activer_ticket_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierspecial',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
