# Generated by Django 5.1.4 on 2025-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0055_remove_depenses_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
