# Generated by Django 5.1.4 on 2025-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0017_promos_annee_academique'),
        ('t_tresorerie', '0056_depenses_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='specialites',
            field=models.ManyToManyField(blank=True, null=True, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='modelecheancier',
            name='is_double_diplomation',
            field=models.BooleanField(default=False),
        ),
    ]
