# Generated by Django 5.1.4 on 2026-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0056_echeancierspecial_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierspecial',
            name='date_frais_inscription',
            field=models.DateField(blank=True, null=True),
        ),
    ]
