# Generated by Django 5.1.4 on 2025-11-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0020_doublediplomation'),
        ('t_tresorerie', '0057_echeancierpaiement_specialites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaiementsrequest',
            name='specialite_double',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.doublediplomation'),
        ),
    ]
