# Generated by Django 5.1.4 on 2025-11-27 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0021_doublediplomation_prix'),
        ('t_tresorerie', '0058_clientpaiementsrequest_specialite_double'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeancierpaiement',
            name='specialites',
        ),
        migrations.AddField(
            model_name='echeancierpaiement',
            name='formation_double',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.doublediplomation'),
        ),
    ]
