# Generated by Django 5.1.4 on 2025-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0059_remove_echeancierpaiement_specialites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duepaiements',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='duepaiements',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
