# Generated by Django 5.1.4 on 2025-11-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0018_fournisseur_site_web'),
        ('t_tresorerie', '0060_alter_duepaiements_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiement',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
    ]
