# Generated by Django 5.1.4 on 2025-12-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0061_echeancierpaiement_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('che', 'Chèque'), ('esp', 'Espèce'), ('vir', 'Virement Bancaire')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='depenses',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
