# Generated by Django 5.1.4 on 2025-12-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0062_depenses_mode_paiement_depenses_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depenses',
            old_name='date',
            new_name='date_paiement',
        ),
    ]
