# Generated by Django 5.1.4 on 2025-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0063_rename_date_depenses_date_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=1)),
                ('type_compte', models.CharField(blank=True, choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit'), ('hors_bilan', 'Hors bilan')], max_length=20, null=True)),
            ],
        ),
    ]
