# Generated by Django 5.1.4 on 2025-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0065_typepaiement_echeancierpaiement_frais_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiements',
            name='date_effet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiements',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
