# Generated by Django 5.1.4 on 2025-12-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0019_bankaccount_bank_code'),
        ('t_tresorerie', '0066_paiements_date_effet_paiements_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiements',
            name='date_effet',
        ),
        migrations.RemoveField(
            model_name='paiements',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='Lettrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('entree', 'Encaissement'), ('sortie', 'Décaissement')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_operation', models.DateField()),
                ('reference_bancaire', models.CharField(blank=True, max_length=255, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('is_rapproche', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institut_app.bankaccount')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettrages', to='t_tresorerie.depenses')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettrages', to='t_tresorerie.paiements')),
            ],
        ),
    ]
