# Generated by Django 5.1.4 on 2025-12-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0020_alter_bankaccount_entreprise'),
        ('t_tresorerie', '0067_remove_paiements_date_effet_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lettrage',
            new_name='Rapprochement',
        ),
    ]
