# Generated by Django 5.1.4 on 2025-12-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0020_alter_bankaccount_entreprise'),
        ('t_tresorerie', '0068_rename_lettrage_rapprochement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rapprochement',
            new_name='OperationsBancaire',
        ),
    ]
