# Generated by Django 5.1.4 on 2025-12-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0020_alter_bankaccount_entreprise'),
        ('t_tresorerie', '0069_rename_rapprochement_operationsbancaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsbancaire',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.bankaccount'),
        ),
        migrations.AlterField(
            model_name='operationsbancaire',
            name='date_operation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
