# Generated by Django 5.1.4 on 2025-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0070_alter_operationsbancaire_compte_bancaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbancaire',
            name='date_paiement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='operationsbancaire',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
