# Generated by Django 5.1.4 on 2025-12-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0021_modules'),
        ('t_tresorerie', '0071_operationsbancaire_date_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiementline',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise'),
        ),
    ]
