# Generated by Django 5.1.4 on 2025-12-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0073_typepaiement_description_soustypepaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='t_tresorerie.paymentcategory')),
            ],
            options={
                'verbose_name': 'Payment category',
                'verbose_name_plural': 'Payment categories',
            },
        ),
        migrations.DeleteModel(
            name='SousTypePaiement',
        ),
        migrations.DeleteModel(
            name='TypePaiement',
        ),
    ]
