# Generated by Django 5.1.4 on 2025-12-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0026_alter_module_name'),
        ('t_tresorerie', '0075_paymentcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepaiements',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.entreprise'),
        ),
    ]
