# Generated by Django 5.1.4 on 2025-12-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0024_promos_is_archived'),
        ('t_tresorerie', '0076_duepaiements_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialiteCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_tresorerie.paymentcategory')),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites')),
            ],
        ),
    ]
