# Generated by Django 5.1.4 on 2025-12-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0077_specialitecompte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='t_tresorerie.depensescategory')),
            ],
            options={
                'verbose_name': 'Depense category',
                'verbose_name_plural': 'Depenses categories',
            },
        ),
    ]
