# Generated by Django 5.1.4 on 2025-12-22 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0026_alter_module_name'),
        ('t_tresorerie', '0078_depensescategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancierpaiementspecialline',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise'),
        ),
    ]
