# Generated by Django 5.1.4 on 2025-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_tresorerie', '0079_echeancierpaiementspecialline_entite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaiementsrequest',
            name='motif',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('frais', "Frais d'admission"), ('autre', 'Autres'), ('dette', 'Module en dette'), ('rach', 'Rachât de crédit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='duepaiements',
            name='type',
            field=models.CharField(blank=True, choices=[('frais_f', 'Frais de formation'), ('dette', 'Module en dette'), ('autre', 'Autre'), ('rach', 'Rachât de crédit')], max_length=100, null=True),
        ),
    ]
