# Generated by Django 5.1.4 on 2026-01-06 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0004_alter_prospets_canal'),
        ('t_formations', '0001_initial'),
        ('t_groupe', '0001_initial'),
        ('t_rh', '0001_initial'),
        ('t_timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinTypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('max_note', models.FloatField(null=True)),
                ('has_sous_notes', models.BooleanField(default=False)),
                ('nb_sous_notes', models.PositiveIntegerField(default=0)),
                ('is_calculee', models.BooleanField(default=False)),
                ('type_calcul', models.CharField(choices=[('NONE', 'Note saisie'), ('SUM', 'Somme'), ('AVG', 'Moyenne')], default='NONE', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ExamTypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('max_note', models.FloatField(null=True)),
                ('has_sous_notes', models.BooleanField(default=False)),
                ('nb_sous_notes', models.PositiveIntegerField(default=0)),
                ('is_calculee', models.BooleanField(default=False)),
                ('type_calcul', models.CharField(default='NONE', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='BuiltinSousNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('max_note', models.FloatField(null=True)),
                ('type_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_notes', to='t_exam.builtintypenote')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('criters', models.TextField(blank=True, null=True)),
                ('date_commission', models.DateField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('formateurs', models.ManyToManyField(to='t_formations.formateurs')),
                ('groupes', models.ManyToManyField(to='t_groupe.groupe')),
                ('participant', models.ManyToManyField(to='t_rh.employees')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos')),
            ],
        ),
        migrations.CreateModel(
            name='CommisionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('exam', 'Examen'), ('rach', 'Rachat'), ('ajou', 'Ajourné(e)')], max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('etudiants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('modules', models.ManyToManyField(to='t_formations.modules')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions')),
            ],
        ),
        migrations.CreateModel(
            name='ExamNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('type_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_exam.examtypenote')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text="Date de l'examen", null=True)),
                ('heure_debut', models.TimeField(blank=True, help_text="Heure de début de l'examen", null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text="Heure de fin de l'examen", null=True)),
                ('type_examen', models.CharField(blank=True, choices=[('normal', 'Ordinaire'), ('rachat', 'Rachat de credit'), ('rattrage', 'Rattrapage')], max_length=100, null=True)),
                ('mode_examination', models.CharField(blank=True, choices=[('tr', 'Travail à remettre'), ('exam', 'Examen'), ('ligne', 'Examen en ligne'), ('orale', 'Présentation orale')], max_length=100, null=True)),
                ('statut', models.CharField(blank=True, choices=[('termine', 'Termine'), ('nabouti', 'Non abouti'), ('att', 'En attente')], default='att', max_length=100, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.modules')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_planification_salle', to='t_timetable.salle')),
                ('surveillant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formateurs')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSousNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_notes', to='t_exam.examnote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModelBuilltins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label du modèle de builtins', max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('systeme_notation', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtin_formation', to='t_formations.formation')),
            ],
        ),
        migrations.AddField(
            model_name='builtintypenote',
            name='builtin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_notes', to='t_exam.modelbuilltins'),
        ),
        migrations.CreateModel(
            name='PvExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_planification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='t_exam.examplanification')),
            ],
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types_notes', to='t_exam.pvexamen'),
        ),
        migrations.AddField(
            model_name='examnote',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_exam.pvexamen'),
        ),
        migrations.CreateModel(
            name='SessionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text="Code de la session d'examen", max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('type_session', models.CharField(blank=True, choices=[('normal', 'Session Ordinaire'), ('rattrapage', 'Session de rattrapage (Spéciale)')], max_length=11, null=True)),
                ('date_debut', models.DateTimeField(null=True)),
                ('date_fin', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('clo', 'Clôturé'), ('att', 'En attente')], default='att', max_length=100, null=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examen",
            },
        ),
        migrations.CreateModel(
            name='SessionExamLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('att', 'En attente'), ('clo', 'Clôturé')], default='att', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_groupe', to='t_groupe.groupe')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_exam_lines', to='t_exam.sessionexam')),
            ],
        ),
        migrations.AddField(
            model_name='examplanification',
            name='exam_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_planification', to='t_exam.sessionexamline'),
        ),
        migrations.CreateModel(
            name='BuiltinTypeNoteDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(help_text='Type de note utilisé dans le calcul', on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='t_exam.builtintypenote')),
                ('parent', models.ForeignKey(help_text='Type de note calculée', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='t_exam.builtintypenote')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='ExamTypeNoteDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='t_exam.examtypenote')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='t_exam.examtypenote')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='builtintypenote',
            unique_together={('builtin', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examtypenote',
            unique_together={('pv', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examnote',
            unique_together={('pv', 'etudiant', 'type_note')},
        ),
        migrations.CreateModel(
            name='ExamDecisionEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('valide', 'Admis'), ('rattrapage', 'Rattrapage'), ('rach', 'Rachat de crédit'), ('ajou', 'Ajourné')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='t_exam.pvexamen')),
            ],
            options={
                'unique_together': {('pv', 'etudiant')},
            },
        ),
    ]
