# Generated by Django 5.1.4 on 2025-12-31 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_etudiants', '0001_initial'),
        ('t_formations', '0001_initial'),
        ('t_groupe', '0001_initial'),
        ('t_rh', '0001_initial'),
        ('t_timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('criters', models.TextField(blank=True, null=True)),
                ('date_commission', models.DateField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('formateurs', models.ManyToManyField(to='t_formations.formateurs')),
                ('groupes', models.ManyToManyField(to='t_groupe.groupe')),
                ('participant', models.ManyToManyField(to='t_rh.employees')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos')),
            ],
        ),
        migrations.CreateModel(
            name='CommisionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('exam', 'Examen'), ('rach', 'Rachat'), ('ajou', 'Ajourné(e)')], max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('etudiants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('modules', models.ManyToManyField(to='t_formations.modules')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions')),
            ],
        ),
        migrations.CreateModel(
            name='ModelBuilltins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label du modèle de builtins', max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtin_formation', to='t_formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='PVNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe')),
                ('model_builtin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_exam.modelbuilltins')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules')),
            ],
            options={
                'unique_together': {('module', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='SessionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text="Code de la session d'examen", max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('type_session', models.CharField(blank=True, choices=[('normal', 'Session Normal'), ('rattrapage', 'Session de rattrapage')], max_length=11, null=True)),
                ('date_debut', models.DateTimeField(null=True)),
                ('date_fin', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examen",
            },
        ),
        migrations.CreateModel(
            name='SessionExamLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_groupe', to='t_groupe.groupe')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_lines', to='t_exam.sessionexam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text="Date de l'examen", null=True)),
                ('heure_debut', models.TimeField(blank=True, help_text="Heure de début de l'examen", null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text="Heure de fin de l'examen", null=True)),
                ('type_examen', models.CharField(blank=True, choices=[('normal', 'Normal'), ('rachat', 'Rachat de credit'), ('rattrage', 'Rattrapage')], max_length=100, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.modules')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_planification_salle', to='t_timetable.salle')),
                ('exam_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_planification', to='t_exam.sessionexamline')),
            ],
        ),
        migrations.CreateModel(
            name='TypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Nom du type de note', max_length=100, null=True)),
                ('affichage', models.CharField(blank=True, help_text="Quelle text afficher dans les PV's et builltins", max_length=100, null=True)),
                ('eval', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('model_builtins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtins', to='t_exam.modelbuilltins')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_etudiants.etudiant')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_exam.pvnotes')),
                ('note_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_exam.typenote')),
            ],
            options={
                'unique_together': {('etudiant', 'note_type', 'pv')},
            },
        ),
    ]
