# Generated by Django 5.1.4 on 2025-04-29 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0001_initial'),
        ('t_formations', '0003_alter_partenaires_type_partenaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinsNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etudiant_builtins', to=settings.AUTH_USER_MODEL)),
                ('session_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_builtins', to='t_exam.sessionexam')),
            ],
        ),
        migrations.CreateModel(
            name='BuiltinsNotsLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, help_text='Note du module', null=True)),
                ('builtin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='builtin_lines', to='t_exam.builtinsnote')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='builtin_module', to='t_formations.modules')),
            ],
        ),
    ]
