# Generated by Django 5.1.4 on 2026-01-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pvnotes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pvnotes',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='pvnotes',
            name='model_builtin',
        ),
        migrations.RemoveField(
            model_name='pvnotes',
            name='module',
        ),
        migrations.RemoveField(
            model_name='typenote',
            name='model_builtins',
        ),
        migrations.CreateModel(
            name='BuiltinTypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('max_note', models.FloatField()),
                ('has_sous_notes', models.BooleanField(default=False)),
                ('nb_sous_notes', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('builtin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_notes', to='t_exam.modelbuilltins')),
            ],
        ),
        migrations.CreateModel(
            name='BuiltinSousNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('type_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_notes', to='t_exam.builtintypenote')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='PVNotes',
        ),
        migrations.DeleteModel(
            name='TypeNote',
        ),
    ]
