# Generated by Django 5.1.4 on 2026-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtintypenote',
            name='is_rachat',
            field=models.BooleanField(default=False, help_text="Note faisant l'objet du rachat crédit"),
        ),
        migrations.AddField(
            model_name='builtintypenote',
            name='is_rattrapage',
            field=models.BooleanField(default=False, help_text="Note concerner dans l'examen de rattrapage"),
        ),
    ]
