# Generated by Django 5.1.4 on 2025-09-11 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_exam', '0001_initial'),
        ('t_formations', '0002_initial'),
        ('t_groupe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pvnotes',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='pvnotes',
            name='model_builtin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_exam.modelbuilltins'),
        ),
        migrations.AddField(
            model_name='pvnotes',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules'),
        ),
        migrations.AddField(
            model_name='note',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_exam.pvnotes'),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_groupe', to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_lines', to='t_exam.sessionexam'),
        ),
        migrations.AddField(
            model_name='examplanification',
            name='exam_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_planification', to='t_exam.sessionexamline'),
        ),
        migrations.AddField(
            model_name='typenote',
            name='model_builtins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtins', to='t_exam.modelbuilltins'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_exam.typenote'),
        ),
        migrations.AlterUniqueTogether(
            name='pvnotes',
            unique_together={('module', 'groupe')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'note_type', 'pv')},
        ),
    ]
