# Generated by Django 5.1.4 on 2025-04-23 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sessionexam',
            options={'verbose_name': "Session d'examen", 'verbose_name_plural': "Sessions d'examen"},
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='code',
            field=models.CharField(blank=True, help_text="Code de la session d'examen", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='type_session',
            field=models.CharField(blank=True, choices=[('normal', 'Session Normal'), ('rattrapage', 'Session de rattrapage')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
