# Generated by Django 5.1.4 on 2026-01-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0002_initial'),
        ('t_exam', '0001_initial'),
        ('t_formations', '0002_initial'),
        ('t_groupe', '0001_initial'),
        ('t_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='groupes',
            field=models.ManyToManyField(to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='commissions',
            name='participant',
            field=models.ManyToManyField(to='t_rh.employees'),
        ),
        migrations.AddField(
            model_name='commissions',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos'),
        ),
        migrations.AddField(
            model_name='commisionresult',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions'),
        ),
        migrations.AddField(
            model_name='examdecisionetudiant',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='examnote',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='examplanification',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.modules'),
        ),
    ]
