# Generated by Django 5.1.4 on 2025-04-30 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0001_initial'),
        ('t_exam', '0002_builtinsnote_builtinsnotslines'),
        ('t_formations', '0003_alter_partenaires_type_partenaire'),
        ('t_groupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text="Date de l'examen", null=True)),
                ('heure_debut', models.TimeField(blank=True, help_text="Heure de début de l'examen", null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text="Heure de fin de l'examen", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelBuilltins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label du modèle de builtins', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_etudiants.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='PVNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules')),
            ],
            options={
                'unique_together': {('module', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='TypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom du type de note', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_builtins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtins', to='t_exam.modelbuilltins')),
            ],
        ),
        migrations.RemoveField(
            model_name='builtinsnote',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='builtinsnote',
            name='session_exam',
        ),
        migrations.RemoveField(
            model_name='builtinsnotslines',
            name='builtin',
        ),
        migrations.RemoveField(
            model_name='builtinsnotslines',
            name='module',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_groupe', to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_lines', to='t_exam.sessionexam'),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examplanification',
            name='exam_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_planification', to='t_exam.sessionexamline'),
        ),
        migrations.AddField(
            model_name='note',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_exam.pvnotes'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_exam.typenote'),
        ),
        migrations.DeleteModel(
            name='BuiltinsNote',
        ),
        migrations.DeleteModel(
            name='BuiltinsNotsLines',
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'note_type', 'pv')},
        ),
    ]
