# Generated by Django 5.1.4 on 2026-01-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_exam', '0002_initial'),
        ('t_formations', '0002_initial'),
        ('t_groupe', '0001_initial'),
        ('t_timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_planification_salle', to='t_timetable.salle'),
        ),
        migrations.AddField(
            model_name='examplanification',
            name='surveillant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formateurs'),
        ),
        migrations.AddField(
            model_name='examsousnote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_notes', to='t_exam.examnote'),
        ),
        migrations.AddField(
            model_name='examnote',
            name='type_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_exam.examtypenote'),
        ),
        migrations.AddField(
            model_name='examtypenotedependency',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='t_exam.examtypenote'),
        ),
        migrations.AddField(
            model_name='examtypenotedependency',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='t_exam.examtypenote'),
        ),
        migrations.AddField(
            model_name='modelbuilltins',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtin_formation', to='t_formations.formation'),
        ),
        migrations.AddField(
            model_name='builtintypenote',
            name='builtin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_notes', to='t_exam.modelbuilltins'),
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_types_notes', to='t_exam.notebloc'),
        ),
        migrations.AddField(
            model_name='builtintypenote',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_notes', to='t_exam.notebloc'),
        ),
        migrations.AddField(
            model_name='pvexamen',
            name='exam_planification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='t_exam.examplanification'),
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types_notes', to='t_exam.pvexamen'),
        ),
        migrations.AddField(
            model_name='examnote',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_exam.pvexamen'),
        ),
        migrations.AddField(
            model_name='examdecisionetudiant',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='t_exam.pvexamen'),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions'),
        ),
        migrations.AddField(
            model_name='sessionexam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_exam_groupe', to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_exam_lines', to='t_exam.sessionexam'),
        ),
        migrations.AddField(
            model_name='examplanification',
            name='exam_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_planification', to='t_exam.sessionexamline'),
        ),
        migrations.AlterUniqueTogether(
            name='builtintypenotedependency',
            unique_together={('parent', 'child')},
        ),
        migrations.AlterUniqueTogether(
            name='examtypenotedependency',
            unique_together={('parent', 'child')},
        ),
        migrations.AlterUniqueTogether(
            name='builtintypenote',
            unique_together={('builtin', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examtypenote',
            unique_together={('pv', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examnote',
            unique_together={('pv', 'etudiant', 'type_note')},
        ),
        migrations.AlterUniqueTogether(
            name='examdecisionetudiant',
            unique_together={('pv', 'etudiant')},
        ),
    ]
