# Generated by Django 5.1.4 on 2026-01-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0002_builtintypenote_is_rachat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='builtintypenote',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_notes', to='t_exam.notebloc'),
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_types_notes', to='t_exam.notebloc'),
        ),
    ]
