# Generated by Django 5.1.4 on 2026-01-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_exam', '0002_alter_pvnotes_unique_together_remove_pvnotes_groupe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('max_note', models.FloatField()),
                ('has_sous_notes', models.BooleanField(default=False)),
                ('nb_sous_notes', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('type_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_exam.examtypenote')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSousNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_notes', to='t_exam.examnote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PvExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_planification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='t_exam.examplanification')),
            ],
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types_notes', to='t_exam.pvexamen'),
        ),
        migrations.AddField(
            model_name='examnote',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='t_exam.pvexamen'),
        ),
        migrations.AlterUniqueTogether(
            name='examtypenote',
            unique_together={('pv', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examnote',
            unique_together={('pv', 'etudiant', 'type_note')},
        ),
    ]
