# Generated by Django 5.1.4 on 2026-05-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtintypenote',
            name='coefficient',
            field=models.FloatField(default=1.0, help_text='Coefficient de pondération pour le calcul de la moyenne générale'),
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='coefficient',
            field=models.FloatField(default=1.0, help_text='Coefficient de pondération pour le calcul de la moyenne générale'),
        ),
    ]
