# Generated by Django 5.1.4 on 2026-01-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0003_notebloc_builtintypenote_bloc_examtypenote_bloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtintypenote',
            name='in_moyenne',
            field=models.BooleanField(default=False, help_text='Intervient dans le calcul de la moyenne générale'),
        ),
        migrations.AddField(
            model_name='examtypenote',
            name='in_moyenne',
            field=models.BooleanField(default=False, help_text='Intervient dans le calcul de la moyenne générale'),
        ),
    ]
