# Generated by Django 5.1.4 on 2026-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0003_examtypenote_examnote_examsousnote_pvexamen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtinsousnote',
            name='max_note',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='examtypenote',
            name='max_note',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
