# Generated by Django 5.1.4 on 2025-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0003_commissions'),
        ('t_groupe', '0008_groupe_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='groupes',
            field=models.ManyToManyField(to='t_groupe.groupe'),
        ),
    ]
