# Generated by Django 5.1.4 on 2026-01-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0004_builtinsousnote_max_note_alter_examtypenote_max_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='mode_examination',
            field=models.CharField(blank=True, choices=[('tr', 'Travail à remettre'), ('exam', 'Examen'), ('ligne', 'Examen en ligne')], max_length=100, null=True),
        ),
    ]
