# Generated by Django 5.1.4 on 2025-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0004_alter_examplanification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionexam',
            name='date_debut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionexam',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
