# Generated by Django 5.1.4 on 2026-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0004_builtintypenote_in_moyenne_examtypenote_in_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebloc',
            name='in_pv_deliberation',
            field=models.BooleanField(default=False),
        ),
    ]
