# Generated by Django 5.1.4 on 2025-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0004_commissions_groupes'),
        ('t_formations', '0023_doublediplomation_prix_spec1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='formateurs',
            field=models.ManyToManyField(to='t_formations.formateurs'),
        ),
    ]
