# Generated by Django 5.1.4 on 2026-05-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0020_prospets_engagement_printed_at_and_more'),
        ('t_exam', '0004_builtintypenote_coefficient_examtypenote_coefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliberationEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_jury', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.CharField(blank=True, max_length=50, null=True)),
                ('moyenne_semestre', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('session_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='t_exam.sessionexamline')),
            ],
            options={
                'unique_together': {('session_line', 'etudiant')},
            },
        ),
    ]
