# Generated by Django 5.1.4 on 2025-05-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0002_salleclasse'),
        ('t_exam', '0005_alter_sessionexam_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_planification_salle', to='institut_app.salleclasse'),
        ),
    ]
