# Generated by Django 5.1.4 on 2026-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0005_notebloc_in_pv_deliberation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commisionresult',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Payé'), ('unpaid', 'Non Payé')], max_length=100, null=True),
        ),
    ]
