# Generated by Django 5.1.4 on 2026-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0005_deliberationetudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvexamen',
            name='soumis_par_formateur',
            field=models.BooleanField(default=False),
        ),
    ]
