# Generated by Django 5.1.4 on 2026-01-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0005_examplanification_mode_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtintypenote',
            name='is_rachat',
            field=models.BooleanField(default=False, help_text="Note faisant l'objet du rachat crédit"),
        ),
        migrations.AddField(
            model_name='builtintypenote',
            name='is_rattrapage',
            field=models.BooleanField(default=False, help_text="Note concerner dans l'examen de rattrapage"),
        ),
        migrations.AlterField(
            model_name='examplanification',
            name='type_examen',
            field=models.CharField(blank=True, choices=[('normal', 'Ordinaire'), ('rachat', 'Rachat de credit'), ('rattrage', 'Rattrapage')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexam',
            name='type_session',
            field=models.CharField(blank=True, choices=[('normal', 'Session Ordinaire'), ('rattrapage', 'Session de rattrapage (Spéciale)')], max_length=11, null=True),
        ),
    ]
