# Generated by Django 5.1.4 on 2025-12-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0005_commissions_formateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='date_commission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissions',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
