# Generated by Django 5.1.4 on 2025-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0006_examplanification_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexamline',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionexamline',
            name='semestre',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True),
        ),
    ]
