# Generated by Django 5.1.4 on 2025-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0006_commissions_date_commission_commissions_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
