# Generated by Django 5.1.4 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0006_commisionresult_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commisionresult',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='commisionresult',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
