# Generated by Django 5.1.4 on 2026-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0006_builtintypenote_is_rachat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
