# Generated by Django 5.1.4 on 2025-12-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0036_alter_prospets_slug'),
        ('t_exam', '0007_commissions_comment'),
        ('t_formations', '0023_doublediplomation_prix_spec1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommisionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('exam', 'Examen'), ('rach', 'Rachat'), ('ajou', 'Ajourné(e)')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions')),
                ('etudiants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('modules', models.ManyToManyField(to='t_formations.modules')),
            ],
        ),
    ]
