# Generated by Django 5.1.4 on 2026-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0007_remove_commisionresult_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebloc',
            name='in_builltin_note',
            field=models.BooleanField(default=False),
        ),
    ]
