# Generated by Django 5.1.4 on 2025-05-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0007_sessionexamline_date_debut_sessionexamline_date_fin_and_more'),
        ('t_formations', '0003_alter_partenaires_type_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.modules'),
        ),
    ]
