# Generated by Django 5.1.4 on 2026-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0007_examplanification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='statut',
            field=models.CharField(blank=True, choices=[('termine', 'Terminer'), ('nabouti', 'Non abouti')], max_length=100, null=True),
        ),
    ]
