# Generated by Django 5.1.4 on 2026-01-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_exam', '0008_examplanification_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDecisionEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('rattrapage', 'Rattrapage'), ('absent', 'Absent')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='t_exam.pvexamen')),
            ],
            options={
                'unique_together': {('pv', 'etudiant')},
            },
        ),
    ]
