# Generated by Django 5.1.4 on 2025-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0008_commisionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='commisionresult',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
