# Generated by Django 5.1.4 on 2025-05-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0008_examplanification_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
