# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0008_notebloc_in_builltin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtintypenote',
            name='is_rachat',
            field=models.BooleanField(default=False, help_text="Note faisant l'objet du rachat de crédit"),
        ),
        migrations.AlterField(
            model_name='builtintypenote',
            name='is_rattrapage',
            field=models.BooleanField(default=False, help_text="Note concernée dans l'examen de rattrapage"),
        ),
        migrations.AlterField(
            model_name='examplanification',
            name='statut',
            field=models.CharField(blank=True, choices=[('termine', 'Terminé'), ('nabouti', 'Non abouti'), ('att', 'En attente')], default='att', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examplanification',
            name='type_examen',
            field=models.CharField(blank=True, choices=[('normal', 'Ordinaire'), ('rachat', 'Rachat de crédit'), ('rattrage', 'Rattrapage')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelbuilltins',
            name='label',
            field=models.CharField(blank=True, help_text='Label du modèle de bulletins', max_length=100, null=True),
        ),
    ]
