# Generated by Django 5.1.4 on 2026-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0009_examdecisionetudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdecisionetudiant',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé'), ('rattrapage', 'Rattrapage')], max_length=20),
        ),
    ]
