# Generated by Django 5.1.4 on 2025-05-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0009_examplanification_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvnotes',
            name='model_builtin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_exam.modelbuilltins'),
        ),
        migrations.AlterField(
            model_name='examplanification',
            name='exam_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_planification', to='t_exam.sessionexamline'),
        ),
    ]
