# Generated by Django 5.1.4 on 2025-12-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0009_commisionresult_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
