# Generated by Django 5.1.4 on 2025-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0010_pvnotes_model_builtin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbuilltins',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
