# Generated by Django 5.1.4 on 2026-01-02 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0010_alter_examdecisionetudiant_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexam',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_exam.commissions'),
        ),
    ]
