# Generated by Django 5.1.4 on 2025-05-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0011_modelbuilltins_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typenote',
            old_name='nom',
            new_name='label',
        ),
    ]
