# Generated by Django 5.1.4 on 2026-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0011_sessionexam_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdecisionetudiant',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé'), ('rattrapage', 'Rattrapage'), ('rach', 'Rachat de crédit'), ('ajou', 'Ajourné')], max_length=20),
        ),
    ]
