# Generated by Django 5.1.4 on 2026-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0013_alter_examdecisionetudiant_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexamline',
            name='status',
            field=models.CharField(blank=True, choices=[('att', 'En attente'), ('clo', 'Clôturé')], default='att', max_length=100, null=True),
        ),
    ]
