# Generated by Django 5.1.4 on 2025-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0013_typenote_eval'),
    ]

    operations = [
        migrations.AddField(
            model_name='typenote',
            name='affichage',
            field=models.CharField(blank=True, help_text="Quelle text afficher dans les PV's et builltins", max_length=100, null=True),
        ),
    ]
