# Generated by Django 5.1.4 on 2025-05-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0014_typenote_affichage'),
        ('t_formations', '0004_alter_specialites_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbuilltins',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_builtin_formation', to='t_formations.formation'),
        ),
    ]
