# Generated by Django 5.1.4 on 2026-01-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0014_sessionexamline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexam',
            name='status',
            field=models.CharField(blank=True, choices=[('clo', 'Clôturé'), ('att', 'En attente')], default='att', max_length=100, null=True),
        ),
    ]
