# Generated by Django 5.1.4 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0015_sessionexam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplanification',
            name='mode_examination',
            field=models.CharField(blank=True, choices=[('tr', 'Travail à remettre'), ('exam', 'Examen'), ('ligne', 'Examen en ligne'), ('orale', 'Présentation orale')], max_length=100, null=True),
        ),
    ]
