# Generated by Django 5.1.4 on 2026-01-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0016_alter_examplanification_mode_examination'),
        ('t_formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplanification',
            name='surveillant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formateurs'),
        ),
        migrations.AlterField(
            model_name='examplanification',
            name='statut',
            field=models.CharField(blank=True, choices=[('termine', 'Termine'), ('nabouti', 'Non abouti'), ('att', 'En attente')], max_length=100, null=True),
        ),
    ]
