# Generated by Django 5.1.4 on 2026-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_exam', '0017_examplanification_surveillant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplanification',
            name='statut',
            field=models.CharField(blank=True, choices=[('termine', 'Termine'), ('nabouti', 'Non abouti'), ('att', 'En attente')], default='att', max_length=100, null=True),
        ),
    ]
