# Generated by Django 5.1.4 on 2026-01-12 20:08

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du template')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-friendly name')),
                ('template_type', models.CharField(choices=[('invoice', 'Facture'), ('contract', 'Contrat'), ('certificate', 'Certificat'), ('report', 'Rapport'), ('letter', 'Lettre'), ('student_info', 'Fiche Étudiant'), ('payment_receipt', 'Reçu de Paiement'), ('payment_statement', 'Relevé de Paiement')], max_length=20, verbose_name='Type de template')),
                ('content', tinymce.models.HTMLField(help_text='Utilisez TinyMCE pour éditer le template', verbose_name='Contenu du template')),
                ('description', models.TextField(blank=True, verbose_name='Description des variables disponibles')),
                ('custom_css', models.TextField(blank=True, default='', verbose_name='CSS personnalisé pour impression')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Document',
                'verbose_name_plural': 'Templates de Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField(default=dict, verbose_name='Données de contexte')),
                ('rendered_content', models.TextField(verbose_name='Contenu rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='pdf_editor.documenttemplate')),
            ],
            options={
                'verbose_name': 'Document Généré',
                'verbose_name_plural': 'Documents Générés',
                'ordering': ['-created_at'],
            },
        ),
    ]
