# Generated by Django 5.1.4 on 2025-12-30 18:06

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Template',
                'verbose_name_plural': 'Catégories de Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations"),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Version du template'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='pdf_editor.documenttemplatecategory', verbose_name='Catégorie'),
        ),
    ]
