# Generated by Django 5.1.4 on 2026-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0002_alter_documenttemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('invoice', 'Facture'), ('contract', 'Contrat'), ('certificate', 'Certificat'), ('report', 'Rapport'), ('letter', 'Lettre'), ('student_info', 'Fiche Étudiant'), ('payment_receipt', 'Reçu de Paiement'), ('payment_statement', 'Relevé de Paiement'), ('stage', 'Document Stage'), ('bulletin', 'Bulletin de Notes')], max_length=20, verbose_name='Type de template'),
        ),
    ]
