# Generated by Django 5.1.4 on 2025-12-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0002_documenttemplatecategory_documenttemplate_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='category',
        ),
        migrations.DeleteModel(
            name='DocumentTemplateCategory',
        ),
    ]
