# Generated by Django 5.1.4 on 2025-12-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0003_remove_documenttemplate_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='tags',
        ),
    ]
