# Generated by Django 5.1.4 on 2025-12-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0004_remove_documenttemplate_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='version',
        ),
    ]
