# Generated by Django 5.1.4 on 2025-12-31 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_formations', '0001_initial'),
        ('t_groupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_arabe', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_arabe', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_pere', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_pere', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_mere', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True)),
                ('situation_familiale', models.CharField(blank=True, choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf(ve)')], max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('alreeady_paied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_crm.prospets')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='LigneRegistrePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=100, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('jour', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_presence', to='t_formations.modules')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.formateurs')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historique', models.JSONField(blank=True, default=list, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('ligne_presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_absence', to='t_etudiants.ligneregistrepresence')),
            ],
        ),
        migrations.CreateModel(
            name='ModelContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('annee_scolaire', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('act', 'Actif'), ('att', 'En attente'), ('ina', 'Inactif')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='ClauseContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.modelcontrat')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.CharField(blank=True, choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4')], max_length=100, null=True)),
                ('annee_academique', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.CharField(blank=True, max_length=100, null=True)),
                ('is_validate', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('enc', 'En cours'), ('ter', 'Cloturer')], default='enc', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.registrepresence'),
        ),
        migrations.CreateModel(
            name='SuiviCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('cours', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance_module', to='t_etudiants.ligneregistrepresence')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_suivie_cours', to='t_formations.modules')),
            ],
        ),
    ]
