# Generated by Django 5.1.4 on 2025-04-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_arabe', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_arabe', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_pere', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_pere', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_mere', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True)),
                ('situation_familiale', models.CharField(blank=True, choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf(ve)')], max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('alreeady_paied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_crm.visiteurs')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
    ]
