# Generated by Django 5.1.4 on 2026-01-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_etudiants', '0001_initial'),
        ('t_formations', '0001_initial'),
        ('t_groupe', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_presence', to='t_formations.modules'),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.formateurs'),
        ),
        migrations.AddField(
            model_name='historiqueabsence',
            name='ligne_presence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_absence', to='t_etudiants.ligneregistrepresence'),
        ),
        migrations.AddField(
            model_name='modelcontrat',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.formation'),
        ),
        migrations.AddField(
            model_name='clausecontrat',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.modelcontrat'),
        ),
        migrations.AddField(
            model_name='registrepresence',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.registrepresence'),
        ),
        migrations.AddField(
            model_name='suivicours',
            name='ligne_presence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance_module', to='t_etudiants.ligneregistrepresence'),
        ),
        migrations.AddField(
            model_name='suivicours',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_suivie_cours', to='t_formations.modules'),
        ),
    ]
