# Generated by Django 5.1.4 on 2025-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
