# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrepresence',
            name='status',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ter', 'Clôturer')], default='enc', max_length=100, null=True),
        ),
    ]
