# Generated by Django 5.1.4 on 2026-04-06 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0013_alter_demandeinscription_session'),
        ('t_etudiants', '0002_initial'),
        ('t_formations', '0006_alter_promos_session'),
        ('t_groupe', '0004_remove_groupe_devis_remove_groupe_thematique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('done', 'Exécuté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('origin_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_from', to='t_groupe.groupe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='t_crm.prospets')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_to_group', to='t_groupe.groupe')),
                ('target_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_to_promo', to='t_formations.promos')),
                ('target_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_to_specialty', to='t_formations.specialites')),
            ],
        ),
    ]
