# Generated by Django 5.1.4 on 2025-02-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_visiteurs_is_entreprise_visiteurs_is_student'),
        ('t_etudiants', '0002_etudiant_alreeady_paied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='cin',
            new_name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='date_naisance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='lieu_naisance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom_mere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_crm.visiteurs'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='tel_mere',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='tel_pere',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
