# Generated by Django 5.1.4 on 2025-10-16 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0002_ligneregistrepresence_registrepresence'),
        ('t_groupe', '0006_groupe_code_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrepresence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrepresence',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_groupe.groupe'),
        ),
        migrations.AddField(
            model_name='registrepresence',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrepresence',
            name='semestre',
            field=models.CharField(blank=True, choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrepresence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
