# Generated by Django 5.1.4 on 2026-04-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0003_studenttransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransferrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
