# Generated by Django 5.1.4 on 2025-10-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0003_registrepresence_created_at_registrepresence_groupe_and_more'),
        ('t_formations', '0009_remove_formation_frais_assurance'),
        ('t_rh', '0002_employees_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules'),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='registre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.registrepresence'),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_rh.employees'),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
