# Generated by Django 5.1.4 on 2026-04-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0004_studenttransferrequest_rejection_reason'),
        ('t_formations', '0006_alter_promos_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransferrequest',
            name='target_double_diploma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_to_double', to='t_formations.doublediplomation'),
        ),
        migrations.AddField(
            model_name='studenttransferrequest',
            name='target_is_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studenttransferrequest',
            name='target_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_to_specialty', to='t_formations.specialites'),
        ),
    ]
