# Generated by Django 5.1.4 on 2025-10-17 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0026_notesprocpects_observation'),
        ('t_etudiants', '0004_ligneregistrepresence_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historique', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('ligne_presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.ligneregistrepresence')),
            ],
        ),
    ]
