# Generated by Django 5.1.4 on 2025-10-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0005_historiqueabsence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligneregistrepresence',
            old_name='hours',
            new_name='heure_debut',
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
