# Generated by Django 5.1.4 on 2025-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0007_alter_ligneregistrepresence_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrepresence',
            name='context',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
