# Generated by Django 5.1.4 on 2025-10-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0008_registrepresence_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneregistrepresence',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='ligneregistrepresence',
            name='heure_fin',
        ),
    ]
