# Generated by Django 5.1.4 on 2025-10-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0009_remove_ligneregistrepresence_heure_debut_and_more'),
        ('t_formations', '0014_formateurs_dispo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneregistrepresence',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_presence', to='t_formations.modules'),
        ),
    ]
