# Generated by Django 5.1.4 on 2025-10-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0010_alter_ligneregistrepresence_module'),
        ('t_formations', '0014_formateurs_dispo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.ligneregistrepresence')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_suivie_cours', to='t_formations.modules')),
            ],
        ),
    ]
