# Generated by Django 5.1.4 on 2025-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0011_suivicours'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrepresence',
            name='status',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ter', 'Cloturer')], max_length=100, null=True),
        ),
    ]
