# Generated by Django 5.1.4 on 2025-10-31 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0012_registrepresence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueabsence',
            name='ligne_presence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_absence', to='t_etudiants.ligneregistrepresence'),
        ),
        migrations.AlterField(
            model_name='suivicours',
            name='ligne_presence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance_module', to='t_etudiants.ligneregistrepresence'),
        ),
    ]
