# Generated by Django 5.1.4 on 2025-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0013_alter_historiqueabsence_ligne_presence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicours',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
