# Generated by Django 5.1.4 on 2025-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0014_suivicours_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicours',
            name='cours',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
