# Generated by Django 5.1.4 on 2025-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0015_suivicours_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivicours',
            name='cours',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
