# Generated by Django 5.1.4 on 2025-11-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0016_alter_suivicours_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClauseContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_etudiants.modelcontrat')),
            ],
        ),
    ]
