# Generated by Django 5.1.4 on 2025-11-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0017_modelcontrat_clausecontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontrat',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
