# Generated by Django 5.1.4 on 2025-11-03 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0018_modelcontrat_label'),
        ('t_formations', '0015_formation_qualification_specialites_branche'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausecontrat',
            name='article',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='clausecontrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clausecontrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelcontrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelcontrat',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.formation'),
        ),
        migrations.AddField(
            model_name='modelcontrat',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
