# Generated by Django 5.1.4 on 2025-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0019_clausecontrat_article_clausecontrat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontrat',
            name='status',
            field=models.CharField(blank=True, choices=[('act', 'Actif'), ('att', 'En attente'), ('ina', 'Inactif')], max_length=10, null=True),
        ),
    ]
