# Generated by Django 5.1.4 on 2025-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0020_modelcontrat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontrat',
            name='annee_scolaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
