# Generated by Django 5.1.4 on 2025-11-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0021_modelcontrat_annee_scolaire'),
        ('t_formations', '0015_formation_qualification_specialites_branche'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelcontrat',
            unique_together={('formation', 'annee_scolaire')},
        ),
    ]
