# Generated by Django 5.1.4 on 2025-11-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0022_alter_modelcontrat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelcontrat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clausecontrat',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
