# Generated by Django 5.1.4 on 2025-12-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0023_alter_modelcontrat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrepresence',
            name='status',
            field=models.CharField(blank=True, choices=[('enc', 'En cours'), ('ter', 'Cloturer')], default='enc', max_length=100, null=True),
        ),
    ]
