# Generated by Django 5.1.4 on 2025-12-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0024_alter_registrepresence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueabsence',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
