# Generated by Django 5.1.4 on 2025-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0025_historiqueabsence_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrepresence',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
