# Generated by Django 5.1.4 on 2025-12-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0026_registrepresence_annee_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='heure_debut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='heure_fin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
