# Generated by Django 5.1.4 on 2025-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0027_ligneregistrepresence_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneregistrepresence',
            name='jour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
