# Generated by Django 5.1.4 on 2025-12-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_etudiants', '0028_ligneregistrepresence_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrepresence',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
