# Generated by Django 5.1.4 on 2026-01-12 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_formations', '0001_initial'),
        ('t_rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.employees'),
        ),
        migrations.AddField(
            model_name='specialites',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='specialite_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmeformation',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='modules',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='fraisinscription',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='doublediplomation',
            name='specialite1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='double_spec1', to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='doublediplomation',
            name='specialite2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='double_spec2', to='t_formations.specialites'),
        ),
        migrations.AlterUniqueTogether(
            name='modules',
            unique_together={('code', 'specialite')},
        ),
    ]
