# Generated by Django 5.1.4 on 2026-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='penalite_retard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promos',
            name='prix_rachat_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
