# Generated by Django 5.1.4 on 2026-01-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_formations', '0002_promos_penalite_retard_promos_prix_rachat_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institut_app.entreprise'),
        ),
    ]
