# Generated by Django 5.1.4 on 2025-03-15 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0002_specialites_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='type_partenaire',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('etranger', 'Etranger')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partenaires',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_partenaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
