# Generated by Django 5.1.4 on 2025-09-12 11:02

import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos),
        ),
    ]
