# Generated by Django 5.1.4 on 2026-01-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modules',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modules',
            name='code_interne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='modules',
            unique_together={('code_interne', 'specialite')},
        ),
    ]
