# Generated by Django 5.1.4 on 2025-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaires',
            name='type_partenaire',
            field=models.CharField(blank=True, choices=[('national', 'Partenaire National'), ('etranger', 'Partenaire Etranger')], max_length=100, null=True),
        ),
    ]
