# Generated by Django 5.1.4 on 2025-02-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_partenaires_formation_entite_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.partenaires'),
        ),
    ]
