# Generated by Django 5.1.4 on 2026-01-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_alter_modules_unique_together_modules_code_interne_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programmeformation',
            unique_together={('module', 'semestre')},
        ),
    ]
