# Generated by Django 5.1.4 on 2025-05-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_alter_partenaires_type_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialites',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_specilite', to='t_formations.formation', to_field='code'),
        ),
    ]
