# Generated by Django 5.1.4 on 2025-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_modules_systeme_eval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='etat',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10, null=True),
        ),
    ]
