# Generated by Django 5.1.4 on 2025-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_partenaires_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='prix_formation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
