# Generated by Django 5.1.4 on 2026-01-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0003_promos_entite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeformation',
            options={'verbose_name': 'Répartition du module', 'verbose_name_plural': 'Répartition des modules'},
        ),
        migrations.AlterField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(blank=True, choices=[('etrangere', 'Formation étrangère'), ('national', 'Formation Etatique')], default='national', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialites',
            name='etat',
            field=models.CharField(blank=True, choices=[('last', 'À jour'), ('updated', 'Mis à jour')], default='last', max_length=10, null=True),
        ),
    ]
