# Generated by Django 5.1.4 on 2025-02-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_formation_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='nb_tranche',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
