# Generated by Django 5.1.4 on 2025-03-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='etat',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
