# Generated by Django 5.1.4 on 2025-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_formation_prix_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promos',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
