# Generated by Django 5.1.4 on 2025-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_alter_promos_etat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AddField(
            model_name='specialites',
            name='condition_access',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='specialites',
            name='dossier_inscription',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
