# Generated by Django 5.1.4 on 2026-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0004_alter_programmeformation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurs',
            name='nin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
