# Generated by Django 5.1.4 on 2025-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0005_promos_date_debut_promos_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prix_formation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
