# Generated by Django 5.1.4 on 2026-04-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0005_formateurs_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='session',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=255, null=True),
        ),
    ]
