# Generated by Django 5.1.4 on 2025-03-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0005_promos_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promos',
            name='created_by',
        ),
    ]
