# Generated by Django 5.1.4 on 2025-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0005_specialites_nb_tranche'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='nb_semestre',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
