# Generated by Django 5.1.4 on 2025-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0005_dossierinscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='etat',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partenaires',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
