# Generated by Django 5.1.4 on 2025-08-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_partenaires_etat_partenaires_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierinscription',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
