# Generated by Django 5.1.4 on 2026-04-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_alter_promos_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
