# Generated by Django 5.1.4 on 2025-03-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_remove_promos_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='session',
            field=models.CharField(blank=True, choices=[('octobre', 'Octobre'), ('mars', 'Mars')], max_length=255, null=True),
        ),
    ]
