# Generated by Django 5.1.4 on 2025-04-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_planscadre_planscours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planscadre',
            options={'verbose_name': 'Plan cadre', 'verbose_name_plural': 'Plans cadre'},
        ),
        migrations.AddField(
            model_name='planscadre',
            name='bibliographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='competences_visees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='contenus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='methodes_pedagogiques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='modalites_evaluation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules'),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='objectifs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='prerequis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='volume_cours',
            field=models.PositiveIntegerField(default=0, help_text='Heures de cours magistral'),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='volume_td',
            field=models.PositiveIntegerField(default=0, help_text='Heures de travaux dirigés'),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='volume_tp',
            field=models.PositiveIntegerField(default=0, help_text='Heures de travaux pratiques'),
        ),
    ]
