# Generated by Django 5.1.4 on 2025-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_specialites_nb_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
