# Generated by Django 5.1.4 on 2025-09-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0006_alter_formation_prix_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prix_formation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
