# Generated by Django 5.1.4 on 2025-09-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0007_alter_formation_prix_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialites',
            name='dossier_inscription',
        ),
    ]
