# Generated by Django 5.1.4 on 2026-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0007_specialites_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierinscription',
            name='include_in_tracking',
            field=models.BooleanField(default=True),
        ),
    ]
