# Generated by Django 5.1.4 on 2025-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0007_dossierinscription_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='begin_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promos',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promos',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
