# Generated by Django 5.1.4 on 2025-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0007_formation_frais_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(blank=True, choices=[('etrangere', 'Formation étrangere'), ('national', 'Formation Etatique')], default='national', max_length=100, null=True),
        ),
    ]
