# Generated by Django 5.1.4 on 2026-05-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0008_dossierinscription_include_in_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promos',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='promos',
            name='date_fin',
        ),
    ]
