# Generated by Django 5.1.4 on 2025-09-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0008_promos_begin_year_promos_code_promos_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='begin_year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promos',
            name='end_year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
