# Generated by Django 5.1.4 on 2025-09-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0008_remove_specialites_dossier_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='frais_assurance',
        ),
    ]
