# Generated by Django 5.1.4 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0009_remove_promos_date_debut_remove_promos_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='frais_duplicata',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
