# Generated by Django 5.1.4 on 2025-02-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0009_partenaires_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaires',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
