# Generated by Django 5.1.4 on 2025-10-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0010_formateurs_enseignantmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurs',
            name='diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
