# Generated by Django 5.1.4 on 2025-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0010_partenaires_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialites',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
