# Generated by Django 5.1.4 on 2026-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0010_promos_frais_duplicata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurs',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
