# Generated by Django 5.1.4 on 2025-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0011_formateurs_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='est_valider',
            field=models.BooleanField(default=False),
        ),
    ]
