# Generated by Django 5.1.4 on 2026-06-02 11:00

import django.core.validators
import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0011_formateurs_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='plan_cours',
            field=models.FileField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_plan_cours, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
