# Generated by Django 5.1.4 on 2026-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0011_formateurs_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='planscadre',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='plans_cadre/pdf/'),
        ),
        migrations.AddField(
            model_name='planscadre',
            name='type_plan',
            field=models.CharField(blank=True, choices=[('text', 'Formulaire texte'), ('pdf', 'Fichier PDF')], default='text', max_length=10, null=True),
        ),
    ]
