# Generated by Django 5.1.4 on 2025-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0011_alter_specialites_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='frais_assurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
