# Generated by Django 5.1.4 on 2025-03-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0012_formation_frais_assurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepartitionsModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.modules')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.specialites')),
            ],
            options={
                'verbose_name': 'Repartition du module',
                'verbose_name_plural': 'Repartition des modules',
                'unique_together': {('module', 'specialite', 'semestre')},
            },
        ),
    ]
