# Generated by Django 5.1.4 on 2025-10-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0012_modules_est_valider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignantmodule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affect_module', to='t_formations.modules'),
        ),
    ]
