# Generated by Django 5.1.4 on 2026-06-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0012_planscadre_fichier_pdf_planscadre_type_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planscours',
            options={'verbose_name': 'Plan de cours', 'verbose_name_plural': 'Plans de cours'},
        ),
        migrations.AddField(
            model_name='planscours',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_cours', to='t_formations.enseignantmodule'),
        ),
        migrations.AddField(
            model_name='planscours',
            name='autres',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='planscours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='planscours',
            name='deroulment',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='planscours',
            name='evaluation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='planscours',
            name='general',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='planscours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
