# Generated by Django 5.1.4 on 2026-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0012_modules_plan_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurs',
            name='is_particular_irg',
            field=models.BooleanField(default=False, help_text='Cochez pour appliquer le barème particulier (Retraités et Personnes Handicapées)', verbose_name='Cas particulier IRG'),
        ),
    ]
