# Generated by Django 5.1.4 on 2026-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0013_alter_planscours_options_planscours_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantmodule',
            name='demande_plan_cours',
            field=models.BooleanField(default=False),
        ),
    ]
