# Generated by Django 5.1.4 on 2025-10-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0013_alter_enseignantmodule_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurs',
            name='dispo',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
