# Generated by Django 5.1.4 on 2025-03-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0013_repartitionsmodules'),
        ('t_rh', '0006_lignefichedepaie_templatefichepaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_rh.employees'),
        ),
    ]
