# Generated by Django 5.1.4 on 2026-06-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0014_enseignantmodule_demande_plan_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planscadre',
            name='type_plan',
            field=models.CharField(blank=True, choices=[('pdf', 'Fichier PDF')], default='pdf', max_length=10, null=True),
        ),
    ]
