# Generated by Django 5.1.4 on 2025-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0014_specialites_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
