# Generated by Django 5.1.4 on 2025-11-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0014_formateurs_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='qualification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='specialites',
            name='branche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
