# Generated by Django 5.1.4 on 2025-11-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0015_formation_qualification_specialites_branche'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='abr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
