# Generated by Django 5.1.4 on 2026-06-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0013_formateurs_is_particular_irg'),
        ('t_formations', '0015_alter_planscadre_type_plan'),
    ]

    operations = [
    ]
