# Generated by Django 5.1.4 on 2025-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0016_specialites_abr'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
