# Generated by Django 5.1.4 on 2025-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0017_promos_annee_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='prix_double_diplomation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
