# Generated by Django 5.1.4 on 2025-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0018_alter_specialites_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialites',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
