# Generated by Django 5.1.4 on 2025-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0018_specialites_prix_double_diplomation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialites',
            name='prix_double_diplomation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
