# Generated by Django 5.1.4 on 2025-11-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0019_alter_specialites_prix_double_diplomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleDiplomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('specialite1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='double_spec1', to='t_formations.specialites')),
                ('specialite2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='double_spec2', to='t_formations.specialites')),
            ],
        ),
    ]
