# Generated by Django 5.1.4 on 2025-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0020_doublediplomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublediplomation',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
