# Generated by Django 5.1.4 on 2025-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0021_doublediplomation_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublediplomation',
            name='frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
