# Generated by Django 5.1.4 on 2025-12-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0022_doublediplomation_frais_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublediplomation',
            name='prix_spec1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='doublediplomation',
            name='prix_spec2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
