# Generated by Django 5.1.4 on 2025-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0023_doublediplomation_prix_spec1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
