# Generated by Django 5.1.4 on 2025-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0024_promos_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialites',
            name='branche',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
