# Generated by Django 5.1.4 on 2025-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0002_documenttemplate_config'),
        ('t_formations', '0025_alter_specialites_branche'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='documents',
            field=models.ManyToManyField(to='t_documents_maker.documenttemplate'),
        ),
    ]
