# Generated by Django 5.1.4 on 2025-12-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0027_entreprise_agrement'),
        ('t_formations', '0026_formation_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrepondanceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.doublediplomation')),
                ('modules', models.ManyToManyField(to='institut_app.module')),
            ],
        ),
    ]
