# Generated by Django 5.1.4 on 2025-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
