# Generated by Django 5.1.4 on 2025-12-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='documentvariable',
            name='tenant',
        ),
    ]
