# Generated by Django 5.1.4 on 2025-12-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0002_remove_documenttemplate_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvariable',
            name='name',
            field=models.CharField(choices=[('formation', 'Formation'), ('specialite', 'Spécialité'), ('qualification', 'Qualification'), ('prix_formation', 'Prix de la formation'), ('annee_academique', 'Année académique'), ('ville', 'Ville'), ('date', 'Date'), ('institut', 'Institut'), ('date_naissance_etudiant', 'Date de naissance étudiant'), ('lieu_naissance_etudiant', 'Lieu de naissance étudiant'), ('adresse_etudiant', 'Adresse étudiant'), ('branche', 'Branche')], help_text="Variable name without braces, e.g., 'formation' for {{formation}}", max_length=255),
        ),
    ]
