# Generated by Django 5.1.4 on 2025-12-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0002_documenttemplate_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='html_content',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
