# Generated by Django 5.1.4 on 2025-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0003_add_pages_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/footer/'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/header/'),
        ),
    ]
