# Generated by Django 5.1.4 on 2025-12-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_documents_maker', '0004_documenttemplate_footer_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='header_logo',
        ),
    ]
