# Generated by Django 5.1.4 on 2025-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_remise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remises',
            name='has_to_justify',
            field=models.BooleanField(default=False),
        ),
    ]
