# Generated by Django 5.1.4 on 2025-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_remise', '0002_remises_has_to_justify'),
    ]

    operations = [
        migrations.AddField(
            model_name='remises',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
