# Generated by Django 5.1.4 on 2025-11-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_remise', '0003_remises_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='remises',
            name='is_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remises',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
