# Generated by Django 5.1.4 on 2025-12-31 21:53

import django.contrib.auth.models
import django.db.models.deletion
import t_crm.tenant_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroupe',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos)),
                ('entete_logo', models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos)),
                ('pied_page_logo', models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos)),
                ('rc', models.CharField(blank=True, max_length=255, null=True)),
                ('nif', models.CharField(blank=True, max_length=255, null=True)),
                ('art', models.CharField(blank=True, max_length=255, null=True)),
                ('nis', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=222, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('entete', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('representant', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('agrement', models.CharField(blank=True, max_length=100, null=True)),
                ('entite_afficher', models.CharField(blank=True, help_text='Abreviation a afficher sur les rapport ex: INSIM', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('site_web', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('rc', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('art', models.CharField(blank=True, max_length=100, null=True)),
                ('nis', models.CharField(blank=True, max_length=100, null=True)),
                ('banque', models.CharField(blank=True, max_length=100, null=True)),
                ('num_compte', models.CharField(blank=True, max_length=100, null=True)),
                ('code_banque', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('crm', 'CRM'), ('ped', 'Pédagogie'), ('eva', 'Evaluation'), ('con', 'Conseil'), ('adm', 'Administration'), ('tre', 'Trésorerie'), ('daf', 'DAF'), ('scol', 'Scolarité'), ('rh', 'Ressources Humaines'), ('rem', 'Remise')], max_length=50, null=True, unique=True, verbose_name='Module')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du Rôle')),
                ('level', models.IntegerField(choices=[(1, 'Utilisateur'), (2, 'Superviseur'), (3, 'Manager'), (4, 'Administrateur')], verbose_name='Niveau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_add', models.BooleanField(default=True)),
                ('can_validate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SalleClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('etage', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_place', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationDesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_devis', models.CharField(blank=True, help_text='Préfixe pour les devis', max_length=50, null=True)),
                ('prefix_facture', models.CharField(blank=True, help_text='Préfixe pour les factures', max_length=50, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise')),
            ],
            options={
                'verbose_name': 'Configuration des documents',
                'verbose_name_plural': 'Configurations des documents',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_iban', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_currency', models.CharField(blank=True, choices=[('eur', 'Euro'), ('dzd', 'Dinars'), ('usd', 'USD')], max_length=1000, null=True)),
                ('bank_observations', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_entreprise', to='institut_app.entreprise')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'Visualiser'), ('add', 'Ajouter'), ('change', 'Modifier'), ('delete', 'Supprimer'), ('export', 'Exporter'), ('approuv', 'Approuver')], max_length=20, verbose_name='Type de permission')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='institut_app.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Permission de Module',
                'verbose_name_plural': 'Permissions de module',
                'ordering': ['module', 'permission_type'],
                'unique_together': {('module', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('tresorier', 'Trésorier'), ('rh', 'Ressources Humaines'), ('crm', 'Chargé(e) clientèle')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='profile_images/default1.png', null=True, upload_to='profile_images')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('module_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='institut_app.modulepermission', verbose_name='Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='institut_app.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Permission de Role',
                'verbose_name_plural': 'Permissions de Role',
                'ordering': ['role', 'module_permission__module'],
                'unique_together': {('role', 'module_permission')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='institut_app.module', verbose_name='Module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institut_app.role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Role Utilisateur-Module',
                'verbose_name_plural': 'Roles Utilisteur-Module',
                'ordering': ['user', 'module', '-role__level'],
                'indexes': [models.Index(fields=['user', 'module'], name='institut_ap_user_id_b67314_idx'), models.Index(fields=['module', 'role'], name='institut_ap_module__fd4e65_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
