# Generated by Django 5.1.4 on 2025-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('tresorier', 'Trésorier'), ('rh', 'Ressources Humaines'), ('crm', 'Chargé(e) clientèle')], max_length=100, null=True),
        ),
    ]
