# Generated by Django 5.1.4 on 2025-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='label',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='num',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_currency',
            field=models.CharField(blank=True, choices=[('eur', 'Euro'), ('dzd', 'Dinars'), ('usd', 'USD')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_observations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
