# Generated by Django 5.1.4 on 2025-02-18 19:13

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='wilaya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
