# Generated by Django 5.1.4 on 2026-01-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_tresorerie', '0013_depensescategory_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs', to='t_tresorerie.paymentcategory'),
        ),
    ]
