# Generated by Django 5.1.4 on 2025-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('etage', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_place', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
            },
        ),
    ]
