# Generated by Django 5.1.4 on 2024-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
            },
        ),
    ]
