# Generated by Django 5.1.4 on 2025-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0002_rename_label_bankaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
