# Generated by Django 5.1.4 on 2025-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0003_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('tresorier', 'Trésorier'), ('rh', 'Ressources Humaines'), ('crm', 'Gestion de la relation client')], max_length=100, null=True),
        ),
    ]
