# Generated by Django 5.1.4 on 2025-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0003_specialites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.AddField(
            model_name='specialites',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
