# Generated by Django 5.1.4 on 2025-07-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default1.jpg', null=True, upload_to='profile_images'),
        ),
    ]
