# Generated by Django 5.1.4 on 2025-08-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default1.png', null=True, upload_to='profile_images'),
        ),
    ]
