# Generated by Django 5.1.4 on 2025-02-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0004_delete_etudiant_specialites_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Specialites',
        ),
    ]
