# Generated by Django 5.1.4 on 2026-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0004_alter_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, choices=[('crm', 'CRM'), ('ped', 'Pédagogie'), ('exa', 'Chargé(e) des examens'), ('eva', 'Evaluation'), ('con', 'Conseil'), ('adm', 'Administration'), ('tre', 'Trésorerie'), ('daf', 'DAF'), ('scol', 'Scolarité'), ('rh', 'Ressources Humaines'), ('rem', 'Remise'), ('com', 'Communications'), ('ger', 'Gérant')], max_length=50, null=True, unique=True, verbose_name='Module'),
        ),
    ]
