# Generated by Django 5.1.4 on 2025-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0004_entreprise_entete_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='code_postal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='obserations',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
