# Generated by Django 5.1.4 on 2025-08-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_devis', models.CharField(blank=True, help_text='Préfixe pour les devis', max_length=50, null=True)),
                ('prefix_facture', models.CharField(blank=True, help_text='Préfixe pour les factures', max_length=50, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institut_app.entreprise')),
            ],
            options={
                'verbose_name': 'Configuration des documents',
                'verbose_name_plural': 'Configurations des documents',
            },
        ),
    ]
