# Generated by Django 5.1.4 on 2025-11-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0005_entreprise_code_postal_entreprise_obserations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='obserations',
            new_name='observations',
        ),
    ]
