# Generated by Django 5.1.4 on 2025-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0006_configurationdesdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='entete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
