# Generated by Django 5.1.4 on 2025-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0006_rename_obserations_entreprise_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
