# Generated by Django 5.1.4 on 2025-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0006_entreprise_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
