# Generated by Django 5.1.4 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications CRM actives')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Globale',
                'verbose_name_plural': 'Configurations Globales',
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
