# Generated by Django 5.1.4 on 2026-04-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0007_globalconfiguration_delete_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name="Délai d'inactivité (minutes)"),
        ),
    ]
