# Generated by Django 5.1.4 on 2025-09-02 17:56

import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0007_entreprise_entete'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos),
        ),
    ]
