# Generated by Django 5.1.4 on 2025-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0007_alter_entreprise_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='pays',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
