# Generated by Django 5.1.4 on 2025-11-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0008_alter_entreprise_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
