# Generated by Django 5.1.4 on 2026-04-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0008_globalconfiguration_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='session_timeout_enabled',
            field=models.BooleanField(default=True, verbose_name='Verrouillage de session actif'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='session_timeout_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name="Délai d'inactivité (secondes)"),
        ),
    ]
