# Generated by Django 5.1.4 on 2025-09-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0009_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='tenant',
        ),
    ]
