# Generated by Django 5.1.4 on 2025-11-03 21:24

import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0009_entreprise_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='pied_page_logo',
            field=models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos),
        ),
    ]
