# Generated by Django 5.1.4 on 2026-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0009_globalconfiguration_session_timeout_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
