# Generated by Django 5.1.4 on 2025-09-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0010_remove_entreprise_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='tenant',
        ),
    ]
