# Generated by Django 5.1.4 on 2025-11-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0010_entreprise_pied_page_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='representant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
