# Generated by Django 5.1.4 on 2026-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0011_userdevicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_device_lock_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
