# Generated by Django 5.1.4 on 2025-11-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0011_entreprise_representant'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='code_wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
