# Generated by Django 5.1.4 on 2026-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0012_usersession_is_device_lock_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='device_lock_enabled',
            field=models.BooleanField(default=True, verbose_name='Verrouillage par appareil actif'),
        ),
    ]
