# Generated by Django 5.1.4 on 2025-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0013_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='banque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='code_banque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='num_compte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
