# Generated by Django 5.1.4 on 2025-11-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0014_fournisseur_banque_fournisseur_code_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
