# Generated by Django 5.1.4 on 2026-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0015_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='crm_tab_validation_enabled',
            field=models.BooleanField(default=True, verbose_name='Validation des onglets CRM active'),
        ),
    ]
