# Generated by Django 5.1.4 on 2025-11-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0016_fournisseur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
