# Generated by Django 5.1.4 on 2026-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0016_globalconfiguration_crm_tab_validation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='default_from_email',
            field=models.CharField(default='noreply@school-saas.com', max_length=255, verbose_name='Email par défaut'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name="Envoi d'emails activé"),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Serveur SMTP'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_host_password',
            field=models.CharField(default='', max_length=255, verbose_name='Mot de passe email'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_host_user',
            field=models.CharField(default='', max_length=255, verbose_name='Email expéditeur'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Port SMTP'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_reset_password_subject',
            field=models.CharField(default='Réinitialisation de votre mot de passe - School SaaS', max_length=255, verbose_name='Objet - Reset mot de passe'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_reset_password_template',
            field=models.TextField(default="Bonjour {user_name},\n\nVotre mot de passe a été réinitialisé.\n\nVotre nouveau mot de passe est : {password}\n\nVeuillez vous connecter et changer ce mot de passe dès que possible.\n\nCordialement,\nL'équipe School SaaS", help_text='Utilisez {user_name} et {password} comme variables', verbose_name='Template - Reset mot de passe'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Utiliser TLS'),
        ),
    ]
