# Generated by Django 5.1.4 on 2025-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0018_fournisseur_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
