# Generated by Django 5.1.4 on 2026-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0018_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='registration_validation_enabled',
            field=models.BooleanField(default=True, verbose_name='Validation des inscriptions active'),
        ),
    ]
