# Generated by Django 5.1.4 on 2026-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0019_globalconfiguration_registration_validation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodulerole',
            name='denied_permissions',
            field=models.ManyToManyField(blank=True, related_name='denied_by_users', to='institut_app.modulepermission', verbose_name='Permissions désactivées'),
        ),
    ]
