# Generated by Django 5.1.4 on 2025-12-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0019_bankaccount_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_entreprise', to='institut_app.entreprise'),
        ),
    ]
