# Generated by Django 5.1.4 on 2026-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0020_usermodulerole_denied_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe'),
        ),
    ]
