# Generated by Django 5.1.4 on 2025-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0020_alter_bankaccount_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('crm', 'CRM'), ('ped', 'Pédagogie'), ('eva', 'Evaluation'), ('con', 'Conseil'), ('crm', 'CRM'), ('adm', 'Administration')], max_length=50, null=True, unique=True, verbose_name='Module')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
    ]
