# Generated by Django 5.1.4 on 2025-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0021_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='entite_afficher',
            field=models.CharField(blank=True, help_text='Abreviation a afficher sur les rapport ex: INSIM', max_length=100, null=True),
        ),
    ]
