# Generated by Django 5.1.4 on 2026-05-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0022_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, choices=[('crm', 'CRM'), ('ped', 'Pédagogie'), ('exa', 'Examens'), ('eva', 'Evaluation'), ('con', 'Executive Education'), ('adm', 'Administration'), ('tre', 'Trésorerie'), ('daf', 'DAF'), ('scol', 'Scolarité'), ('int', 'Interface Pédagogique'), ('rh', 'Ressources Humaines'), ('rem', 'Remise'), ('com', 'Communications'), ('ger', 'Gérant'), ('sta', 'Stage')], max_length=50, null=True, unique=True, verbose_name='Module'),
        ),
    ]
