# Generated by Django 5.1.4 on 2025-12-19 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0023_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('crm', 'CRM'), ('ped', 'Pédagogie'), ('eva', 'Evaluation'), ('con', 'Conseil'), ('adm', 'Administration')], max_length=50, null=True, unique=True, verbose_name='Module')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'Visualiser'), ('add', 'Ajouter'), ('change', 'Modifier'), ('delete', 'Supprimer'), ('export', 'Exporter'), ('approuv', 'Approuver')], max_length=20, verbose_name='Type de permission')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='institut_app.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Permission de Module',
                'verbose_name_plural': 'Permissions de module',
                'ordering': ['module', 'permission_type'],
                'unique_together': {('module', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('module_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='institut_app.modulepermission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Permission de Role',
                'verbose_name_plural': 'Permissions de Role',
                'ordering': ['role', 'module_permission__module'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='institut_app.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Role Utilisateur-Module',
                'verbose_name_plural': 'Roles Utilisteur-Module',
                'ordering': ['user', 'module', '-role__level'],
            },
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-level', 'name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='institut_app.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='usermodulerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institut_app.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='usermodulerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module_permission')},
        ),
        migrations.AddIndex(
            model_name='usermodulerole',
            index=models.Index(fields=['user', 'module'], name='institut_ap_user_id_b67314_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodulerole',
            index=models.Index(fields=['module', 'role'], name='institut_ap_module__fd4e65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermodulerole',
            unique_together={('user', 'module')},
        ),
    ]
