# Generated by Django 5.1.4 on 2026-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0023_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='messaging_realtime_enabled',
            field=models.BooleanField(default=True, verbose_name='Notifications Messagerie actives'),
        ),
    ]
