# Generated by Django 5.1.4 on 2026-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0024_globalconfiguration_messaging_realtime_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='Forcer le changement de mot de passe'),
        ),
    ]
