# Generated by Django 5.1.4 on 2025-12-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0024_module_modulepermission_rolepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, choices=[('crm', 'CRM'), ('ped', 'Pédagogie'), ('eva', 'Evaluation'), ('con', 'Conseil'), ('adm', 'Administration'), ('tre', 'Trésorerie'), ('daf', 'DAF'), ('scol', 'Scolarité'), ('rh', 'Ressources Humaines')], max_length=50, null=True, unique=True, verbose_name='Module'),
        ),
    ]
