# Generated by Django 5.1.4 on 2026-06-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0025_profile_force_password_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, choices=[('crm', 'CRM'), ('rel', 'Relations Extérieures'), ('ped', 'Pédagogie'), ('exa', 'Examens'), ('eva', 'Evaluation'), ('con', 'Executive Education'), ('adm', 'Administration'), ('tre', 'Trésorerie'), ('daf', 'DAF'), ('scol', 'Scolarité'), ('int', 'Interface Pédagogique'), ('rh', 'Ressources Humaines'), ('rem', 'Remise'), ('com', 'Communications'), ('ger', 'Gérant'), ('sta', 'Stage')], max_length=50, null=True, unique=True, verbose_name='Module'),
        ),
        migrations.CreateModel(
            name='UserSubMenuAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10)),
                ('submenu_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès Sous-Menu',
                'verbose_name_plural': 'Accès Sous-Menus',
                'unique_together': {('user', 'module_code', 'submenu_code')},
            },
        ),
    ]
