# Generated by Django 5.1.4 on 2025-12-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0026_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='agrement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
