# Generated by Django 5.1.4 on 2026-06-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0026_alter_module_name_usersubmenuaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='derogation_notification_mode',
            field=models.CharField(choices=[('role', 'Par rôle (Managers/Superviseurs CRM)'), ('specific', 'Comptes spécifiques')], default='role', max_length=20, verbose_name='Mode de notification de dérogation'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='derogation_notification_receivers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Receveurs des notifications de dérogation'),
        ),
    ]
