# Generated by Django 5.1.4 on 2026-06-03 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0027_globalconfiguration_derogation_notification_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='payment_notification_mode',
            field=models.CharField(choices=[('role', 'Par rôle (Trésorerie)'), ('specific', 'Comptes spécifiques')], default='role', max_length=20, verbose_name='Mode de notification de paiement'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='payment_notification_receivers',
            field=models.ManyToManyField(blank=True, related_name='payment_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receveurs des notifications de paiement'),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='derogation_notification_receivers',
            field=models.ManyToManyField(blank=True, related_name='derogation_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receveurs des notifications de dérogation'),
        ),
    ]
