# Generated by Django 5.1.4 on 2026-06-03 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0028_globalconfiguration_payment_notification_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='transfer_notification_mode',
            field=models.CharField(choices=[('role', 'Par rôle (Scolarité)'), ('specific', 'Comptes spécifiques')], default='role', max_length=20, verbose_name='Mode de notification de transfert'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='transfer_notification_receivers',
            field=models.ManyToManyField(blank=True, related_name='transfer_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receveurs des notifications de transfert'),
        ),
    ]
