# Generated by Django 5.1.4 on 2026-06-05 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0029_globalconfiguration_transfer_notification_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='paie_notification_mode',
            field=models.CharField(choices=[('role', 'Par rôle (Comptabilité/Finance)'), ('specific', 'Comptes spécifiques')], default='role', max_length=20, verbose_name='Mode de notification de paie'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='paie_notification_receivers',
            field=models.ManyToManyField(blank=True, related_name='paie_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receveurs des notifications de paie'),
        ),
    ]
