# Generated by Django 5.1.4 on 2026-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0030_globalconfiguration_paie_notification_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='quittance_prefix',
            field=models.CharField(blank=True, default='N°', max_length=50, null=True, verbose_name='Préfixe de Quittance'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='quittance_suffix',
            field=models.CharField(blank=True, default='/ST/{entite}/{wilaya}/{annexe}/{mois}/{annee}', max_length=100, null=True, verbose_name='Suffixe de Quittance'),
        ),
    ]
