# Generated by Django 5.1.4 on 2026-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0031_entreprise_quittance_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='quittance_prefix',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='quittance_suffix',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='quittance_format',
            field=models.CharField(blank=True, default='N°{seq}/ST/{entite}/{wilaya}/{annexe}/{mois}/{annee}', max_length=200, null=True, verbose_name='Format de Quittance'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='quittance_sequence_length',
            field=models.IntegerField(default=6, verbose_name='Longueur de la séquence'),
        ),
    ]
