# Generated by Django 5.1.4 on 2026-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0032_remove_entreprise_quittance_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfiguration',
            name='crm_tab_validation_enabled',
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='crm_field_locks',
            field=models.JSONField(blank=True, default=dict, verbose_name='Verrouillage des champs CRM'),
        ),
    ]
