# Generated by Django 5.1.4 on 2026-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0033_remove_globalconfiguration_crm_tab_validation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='crm_required_fields_double',
            field=models.JSONField(blank=True, default=dict, verbose_name='Champs requis CRM (Double Diplomation)'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='crm_required_fields_etranger',
            field=models.JSONField(blank=True, default=dict, verbose_name='Champs requis CRM (Etranger)'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='crm_required_fields_national',
            field=models.JSONField(blank=True, default=dict, verbose_name='Champs requis CRM (National)'),
        ),
    ]
