# Generated by Django 5.1.4 on 2026-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0034_globalconfiguration_crm_required_fields_double_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='bypass_preinscrit_verification',
            field=models.BooleanField(default=True, verbose_name='Désactiver la vérification du dossier (validation directe)'),
        ),
    ]
