# Generated by Django 5.1.4 on 2026-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0035_globalconfiguration_bypass_preinscrit_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfiguration',
            name='bypass_preinscrit_verification',
            field=models.BooleanField(default=False, verbose_name='Désactiver la vérification du dossier (validation directe)'),
        ),
    ]
