# Generated by Django 5.1.4 on 2025-08-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, help_text='Nom du client', max_length=255, null=True)),
                ('num_devis', models.CharField(blank=True, help_text='Numéro du devis', max_length=50, null=True, unique=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant du devis', max_digits=10, null=True)),
                ('date_emission', models.DateField(blank=True, help_text="Date d'émission du devis", null=True)),
                ('date_echeance', models.DateField(blank=True, help_text="Date d'échéance du devis", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thematiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label de la thématique', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description de la thématique', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Thématique',
                'verbose_name_plural': 'Thématiques',
            },
        ),
        migrations.CreateModel(
            name='LignesDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description de la ligne de devis', max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la ligne de devis', max_digits=10, null=True)),
                ('quantite', models.PositiveIntegerField(blank=True, help_text='Quantité de la ligne de devis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='t_conseil.devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
    ]
