# Generated by Django 5.1.4 on 2025-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='brouillon', max_length=50),
        ),
    ]
