# Generated by Django 5.1.4 on 2026-01-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='FormateurConseil',
        ),
    ]
