# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematiques',
            name='etat',
            field=models.CharField(choices=[('archive', 'Archivée'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
