# Generated by Django 5.1.4 on 2026-01-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0002_delete_client_delete_formateurconseil'),
        ('t_crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client facturé', null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='devis_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='t_conseil.devis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyée'), ('battente', 'En attente de paiement'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=50),
        ),
        migrations.AddField(
            model_name='facture',
            name='num_facture',
            field=models.CharField(blank=True, help_text='Numéro de la facture', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.IntegerField(choices=[(0, '0%'), (9, '9%'), (19, '19%')], default=19, help_text='Taux de TVA applicable'),
        ),
        migrations.AddField(
            model_name='facture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lignesdevis',
            name='thematique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='t_conseil.thematiques'),
        ),
        migrations.AddField(
            model_name='thematiques',
            name='billing_type',
            field=models.CharField(choices=[('heure', 'Heure'), ('jour', 'Jour')], default='heure', help_text='Mode de facturation', max_length=50),
        ),
        migrations.CreateModel(
            name='LignesFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='t_conseil.facture')),
                ('thematique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_conseil.thematiques')),
            ],
        ),
    ]
