# Generated by Django 5.1.4 on 2025-10-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0002_alter_devis_client'),
        ('t_crm', '0024_prospets_matricule_prospets_matricule_interne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(default=5, help_text='Nom du client', on_delete=django.db.models.deletion.CASCADE, related_name='client_devis', to='t_crm.prospets'),
            preserve_default=False,
        ),
    ]
