# Generated by Django 5.1.4 on 2025-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0002_devis_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom du client', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email du client', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Téléphone du client', max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, help_text='Adresse du client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
