# Generated by Django 5.1.4 on 2025-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematiques',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de la thématique', max_digits=10, null=True),
        ),
    ]
