# Generated by Django 5.1.4 on 2026-01-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0003_alter_facture_options_facture_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tva_percent', models.DecimalField(decimal_places=2, default=19.0, help_text='Taux de TVA par défaut (%)', max_digits=5)),
                ('show_tva_on_devis', models.BooleanField(default=True, help_text='Afficher la TVA sur les devis PDF/View')),
                ('show_tva_on_facture', models.BooleanField(default=True, help_text='Afficher la TVA sur les factures PDF/View')),
                ('enable_remise_global', models.BooleanField(default=False, help_text='Activer la gestion des remises')),
                ('default_remise_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de remise par défaut (%)', max_digits=5)),
                ('show_remise_on_devis', models.BooleanField(default=False, help_text='Afficher la colonne remise sur les devis')),
                ('show_remise_on_facture', models.BooleanField(default=False, help_text='Afficher la colonne remise sur les factures')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Conseil',
                'verbose_name_plural': 'Configuration Conseil',
            },
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={},
        ),
        migrations.AddField(
            model_name='lignesfacture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyée'), ('battente', 'En attente de paiement'), ('paye', 'Payée'), ('annule', 'Annulée')], default='brouillon', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2024-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignesfacture',
            name='description',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
