# Generated by Django 5.1.4 on 2026-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0004_conseilconfiguration_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesdevis',
            name='remise_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de remise', max_digits=5),
        ),
        migrations.AddField(
            model_name='lignesfacture',
            name='remise_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
