# Generated by Django 5.1.4 on 2025-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0004_thematiques_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematiques',
            name='duree',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en minutes', null=True),
        ),
    ]
