# Generated by Django 5.1.4 on 2025-08-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0005_thematiques_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormateurConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='thematiques',
            name='etat',
            field=models.CharField(choices=[('archive', 'Archivé'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
