# Generated by Django 5.1.4 on 2026-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0005_lignesdevis_remise_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvaConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: TVA 19%', max_length=50)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Valeur en %', max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TVA Conseil',
                'verbose_name_plural': 'TVAs Conseil',
            },
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Taux de TVA applicable', max_digits=5),
        ),
    ]
