# Generated by Django 5.1.4 on 2026-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0006_tvaconseil_alter_facture_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='show_tva',
            field=models.BooleanField(default=True, help_text='Afficher la TVA sur ce devis'),
        ),
    ]
