# Generated by Django 5.1.4 on 2026-01-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0007_devis_show_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesdevis',
            name='tva_percent',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Taux de TVA pour cette ligne', max_digits=5),
        ),
        migrations.AddField(
            model_name='lignesfacture',
            name='tva_percent',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
