# Generated by Django 5.1.4 on 2026-01-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0008_lignesdevis_tva_percent_lignesfacture_tva_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematiques',
            name='default_tva',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='TVA par défaut pour cette thématique', max_digits=5),
        ),
    ]
