# Generated by Django 5.1.4 on 2026-01-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0009_thematiques_default_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='devis_counter_width',
            field=models.PositiveIntegerField(default=4, help_text='Longueur du compteur (ex: 4 pour 0001)'),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='devis_prefix',
            field=models.CharField(default='DEV', help_text='Préfixe pour les devis', max_length=20),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='facture_counter_width',
            field=models.PositiveIntegerField(default=4, help_text='Longueur du compteur (ex: 4 pour 0001)'),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='facture_prefix',
            field=models.CharField(default='FAC', help_text='Préfixe pour les factures', max_length=20),
        ),
    ]
