# Generated by Django 5.1.4 on 2026-01-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_conseil', '0010_conseilconfiguration_devis_counter_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conseil_config', to='institut_app.entreprise'),
        ),
        migrations.AddField(
            model_name='devis',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_entreprise', to='institut_app.entreprise'),
        ),
        migrations.AddField(
            model_name='facture',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures_entreprise', to='institut_app.entreprise'),
        ),
    ]
