# Generated by Django 5.1.4 on 2026-01-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_conseil', '0011_conseilconfiguration_entreprise_devis_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilconfiguration',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conseil_config', to='institut_app.entreprise', unique=True),
        ),
    ]
