# Generated by Django 5.1.4 on 2026-01-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0001_initial'),
        ('t_conseil', '0012_alter_conseilconfiguration_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvaconseil',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tvas_conseil', to='institut_app.entreprise'),
        ),
    ]
