# Generated by Django 5.1.4 on 2026-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0013_tvaconseil_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematiques',
            name='categorie',
            field=models.CharField(choices=[('service', 'Service'), ('produit', 'Produit')], default='service', help_text='Catégorie de la thématique', max_length=20),
        ),
    ]
