# Generated by Django 5.1.4 on 2026-01-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0014_thematiques_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematiques',
            name='duree',
        ),
    ]
