# Generated by Django 5.1.4 on 2026-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0015_remove_thematiques_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='default_conditions_commerciales',
            field=models.TextField(blank=True, help_text='Conditions commerciales par défaut', null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='conditions_commerciales',
            field=models.TextField(blank=True, help_text='Conditions commerciales spécifiques à ce devis', null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='conditions_commerciales',
            field=models.TextField(blank=True, help_text='Conditions commerciales spécifiques à cette facture', null=True),
        ),
    ]
