# Generated by Django 5.1.4 on 2026-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0016_conseilconfiguration_default_conditions_commerciales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='payment_methods',
            field=models.TextField(blank=True, help_text='Méthodes de paiement par défaut (RIB, CCP, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='payment_methods',
            field=models.TextField(blank=True, help_text='Méthodes de paiement et coordonnées bancaires spécifiques à cette facture', null=True),
        ),
    ]
