# Generated by Django 5.1.4 on 2026-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0017_conseilconfiguration_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='show_remise',
            field=models.BooleanField(default=False, help_text='Afficher la remise sur ce devis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='show_remise',
            field=models.BooleanField(default=False, help_text='Afficher la remise sur cette facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='show_tva',
            field=models.BooleanField(default=True, help_text='Afficher la TVA sur cette facture'),
        ),
    ]
