# Generated by Django 5.1.4 on 2026-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0018_devis_show_remise_facture_show_remise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesdevis',
            name='long_description',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', null=True),
        ),
        migrations.AddField(
            model_name='lignesfacture',
            name='long_description',
            field=models.TextField(blank=True, help_text='Description détaillée de la prestation', null=True),
        ),
        migrations.AlterField(
            model_name='lignesdevis',
            name='description',
            field=models.CharField(blank=True, help_text='Description courte de la ligne', max_length=255, null=True),
        ),
    ]
