# Generated by Django 5.1.4 on 2026-01-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0019_lignesdevis_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement Bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('autre', 'Autre')], default='virement', help_text='Mode de paiement attendu', max_length=20),
        ),
    ]
