# Generated by Django 5.1.4 on 2026-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0020_facture_mode_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conseilconfiguration',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='payment_methods',
        ),
        migrations.AlterField(
            model_name='facture',
            name='conditions_commerciales',
            field=models.TextField(blank=True, help_text='Conditions spécifiques à cette facture', null=True),
        ),
    ]
