# Generated by Django 5.1.4 on 2026-01-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0021_remove_conseilconfiguration_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesdevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire HT', max_digits=10),
        ),
    ]
