# Generated by Django 5.1.4 on 2026-01-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0022_lignesdevis_prix_unitaire'),
        ('t_crm', '0006_opportunite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='opportunite',
            field=models.ForeignKey(blank=True, help_text='Opportunité liée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunite_devis', to='t_crm.opportunite'),
        ),
    ]
