# Generated by Django 5.1.4 on 2026-01-27 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0024_paiement'),
        ('t_tresorerie', '0008_alter_promorembourssement_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Désignation de l'association", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='das_mappings', to='t_tresorerie.paymentcategory')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='das_mappings', to='t_conseil.thematiques')),
            ],
            options={
                'verbose_name': 'Mapping DAS',
                'verbose_name_plural': 'Mappings DAS',
                'unique_together': {('thematique', 'payment_category')},
            },
        ),
    ]
