# Generated by Django 5.1.4 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0025_dasmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('vir', 'Virement Bancaire'), ('che', 'Chèque'), ('esp', 'Espèce'), ('autre', 'Autre')], max_length=20),
        ),
    ]
