# Generated by Django 5.1.4 on 2026-01-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0026_paiement_is_done_alter_paiement_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='module_source',
            field=models.CharField(choices=[('conseil', 'Executive Education'), ('tresorerie', 'Comptabilité')], default='conseil', help_text="Module d'origine de la facture", max_length=50),
        ),
    ]
