# Generated by Django 5.1.4 on 2026-03-15 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0028_lignesdevis_specialite_lignesfacture_specialite_and_more'),
        ('t_crm', '0008_alter_prospets_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants_pool', to='t_crm.prospets'),
        ),
    ]
