# Generated by Django 5.1.4 on 2026-03-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0029_participant_prospect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvaconseil',
            name='entreprise',
        ),
    ]
