# Generated by Django 5.1.4 on 2026-03-16 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0030_remove_tvaconseil_entreprise'),
        ('t_formations', '0005_formateurs_nin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('enc', 'En cours'), ('cloture', 'Clôturé')], default='brouillon', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_conseil_crees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_conseil', to='t_conseil.devis')),
            ],
            options={
                'verbose_name': 'Groupe Conseil',
                'verbose_name_plural': 'Groupes Conseil',
            },
        ),
        migrations.CreateModel(
            name='GroupeConseilParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_groupe', to='t_conseil.groupeconseil')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_impliques', to='t_conseil.participant')),
            ],
            options={
                'verbose_name': 'Participant du Groupe Conseil',
                'verbose_name_plural': 'Participants des Groupes Conseil',
            },
        ),
        migrations.CreateModel(
            name='GroupeConseilThematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formateurs')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_thematiques', to='t_conseil.groupeconseil')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_conseil.thematiques')),
            ],
            options={
                'verbose_name': 'Affectation Thématique Groupe Conseil',
                'verbose_name_plural': 'Affectations Thématiques Groupes Conseil',
            },
        ),
    ]
