# Generated by Django 5.1.4 on 2026-03-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0031_groupeconseil_groupeconseilparticipant_and_more'),
        ('t_formations', '0005_formateurs_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeconseil',
            name='jours_travail',
            field=models.CharField(blank=True, help_text='Jours de travail prévus (ex: Lun, Mar, Jeu)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='groupeconseil',
            name='lieu_formation',
            field=models.CharField(blank=True, help_text="Lieu de l'action de formation", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='GroupeConseilPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formateurs')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='t_conseil.groupeconseil')),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_conseil.thematiques')),
            ],
            options={
                'verbose_name': 'Planning Groupe Conseil',
                'verbose_name_plural': 'Plannings Groupes Conseil',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
