# Generated by Django 5.1.4 on 2026-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0032_groupeconseil_jours_travail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_confirmed_for_scolarite',
            field=models.BooleanField(default=False),
        ),
    ]
