# Generated by Django 5.1.4 on 2026-03-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0033_participant_is_confirmed_for_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='scolarite_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
