# Generated by Django 5.1.4 on 2026-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0034_participant_scolarite_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='apply_stamp_duty_on_cash_only',
            field=models.BooleanField(default=True, help_text='Appliquer uniquement sur les paiements en espèces'),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='enable_stamp_duty',
            field=models.BooleanField(default=False, help_text='Activer les droits de timbre (Algérie)'),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='stamp_duty_max',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Plafond du timbre (DZD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='stamp_duty_min',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Montant minimum du timbre (DZD)', max_digits=10),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='stamp_duty_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Taux du timbre en % (Standard: 1%)', max_digits=5),
        ),
    ]
