# Generated by Django 5.1.4 on 2026-04-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0015_alter_module_name'),
        ('t_conseil', '0035_conseilconfiguration_apply_stamp_duty_on_cash_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilconfiguration',
            name='entreprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conseil_config', to='institut_app.entreprise'),
        ),
    ]
