# Generated by Django 5.1.4 on 2026-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0036_alter_conseilconfiguration_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_timbre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Droit de timbre (fixé à la création)', max_digits=10),
        ),
    ]
