# Generated by Django 5.1.4 on 2026-05-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0037_facture_montant_timbre'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='avoir_counter_width',
            field=models.PositiveIntegerField(default=4, help_text='Longueur du compteur pour avoir (ex: 4 pour 0001)'),
        ),
        migrations.AddField(
            model_name='conseilconfiguration',
            name='avoir_prefix',
            field=models.CharField(default='AV', help_text='Préfixe pour les avoirs', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_source',
            field=models.ForeignKey(blank=True, help_text="Facture d'origine si c'est un avoir", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_lies', to='t_conseil.facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('standard', 'Standard'), ('avoir', 'Avoir')], default='standard', help_text='Type de document', max_length=20),
        ),
    ]
