# Generated by Django 5.1.4 on 2026-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0038_conseilconfiguration_avoir_counter_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement Bancaire'), ('vir', 'Virement Bancaire'), ('cheque', 'Chèque'), ('che', 'Chèque'), ('espece', 'Espèces'), ('esp', 'Espèces'), ('autre', 'Autre')], default='virement', help_text='Mode de paiement attendu', max_length=20),
        ),
    ]
