# Generated by Django 5.1.4 on 2026-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0039_alter_facture_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeconseilplanning',
            name='realisee',
            field=models.BooleanField(default=False, help_text='La séance a bien été tenue'),
        ),
        migrations.AddField(
            model_name='groupeconseilplanning',
            name='resume_seance',
            field=models.TextField(blank=True, help_text='Éléments réellement abordés', null=True),
        ),
    ]
