# Generated by Django 5.1.4 on 2026-06-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut_app', '0030_globalconfiguration_paie_notification_mode_and_more'),
        ('t_conseil', '0040_groupeconseilplanning_realisee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseilconfiguration',
            name='compte_bancaire_defaut',
            field=models.ForeignKey(blank=True, help_text='Compte bancaire par défaut pour les factures', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institut_app.bankaccount'),
        ),
    ]
