# Generated by Django 5.1.4 on 2026-06-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0041_conseilconfiguration_compte_bancaire_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeconseil',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes_conseil', to='t_conseil.facture'),
        ),
        migrations.AlterField(
            model_name='groupeconseil',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes_conseil', to='t_conseil.devis'),
        ),
    ]
