# Generated by Django 5.1.4 on 2026-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0043_consultant_groupeconseilplanning_consultant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client_nin_override',
            field=models.CharField(blank=True, help_text='NIN du tiers payeur', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='client_nom_override',
            field=models.CharField(blank=True, help_text='Nom du tiers payeur', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='client_prenom_override',
            field=models.CharField(blank=True, help_text='Prénom du tiers payeur', max_length=255, null=True),
        ),
    ]
