# Generated by Django 5.1.4 on 2026-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_conseil', '0044_facture_client_nin_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesdevis',
            name='unite',
            field=models.CharField(choices=[('jour', 'Jour'), ('groupe', 'Groupe'), ('participant', 'Participant'), ('heure', 'Heure')], default='participant', help_text='Unité de facturation', max_length=20),
        ),
        migrations.AddField(
            model_name='lignesfacture',
            name='unite',
            field=models.CharField(choices=[('jour', 'Jour'), ('groupe', 'Groupe'), ('participant', 'Participant'), ('heure', 'Heure')], default='participant', help_text='Unité de facturation', max_length=20),
        ),
    ]
