# Generated by Django 5.1.4 on 2026-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name="Envoi d'emails activé")),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Serveur SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='Port SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('email_host_user', models.CharField(default='', max_length=255, verbose_name='Email expéditeur')),
                ('email_host_password', models.CharField(default='', max_length=255, verbose_name='Mot de passe email')),
                ('default_from_email', models.CharField(default='noreply@school-saas.com', max_length=255, verbose_name='Email par défaut')),
                ('email_reset_password_subject', models.CharField(default='Réinitialisation de votre mot de passe - School SaaS', max_length=255, verbose_name='Objet - Reset mot de passe')),
                ('email_reset_password_template', models.TextField(default="Bonjour {user_name},\n\nVotre mot de passe a été réinitialisé.\n\nVotre nouveau mot de passe est : {password}\n\nVeuillez vous connecter et changer ce mot de passe dès que possible.\n\nCordialement,\nL'équipe School SaaS", help_text='Utilisez {user_name} et {password} comme variables', verbose_name='Template - Reset mot de passe')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Email SaaS',
                'verbose_name_plural': 'Configuration Email SaaS',
            },
        ),
    ]
