# Generated by Django 5.1.4 on 2026-04-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSMaintenanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Mode Maintenance (En attente) actif')),
                ('maintenance_message', models.TextField(default='Nous mettons actuellement la plateforme à jour. Merci de réessayer plus tard.', verbose_name='Message de maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Maintenance SaaS',
                'verbose_name_plural': 'Configuration Maintenance SaaS',
            },
        ),
    ]
