# Generated by Django 5.1.4 on 2026-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin_app', '0002_saasmaintenanceconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasmaintenanceconfiguration',
            name='maintenance_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin prévue'),
        ),
    ]
