# Generated by Django 5.1.4 on 2026-04-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institut_tenant_type'),
        ('saas_admin_app', '0003_saasmaintenanceconfiguration_maintenance_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backups/', verbose_name='Fichier de sauvegarde')),
                ('backup_type', models.CharField(choices=[('GLOBAL', 'Sauvegarde Globale'), ('TENANT', 'Sauvegarde Tenant')], default='GLOBAL', max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('size', models.BigIntegerField(default=0, verbose_name='Taille (bytes)')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='app.institut', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Sauvegarde Base de Données',
                'verbose_name_plural': 'Sauvegardes Base de Données',
                'ordering': ['-created_at'],
            },
        ),
    ]
