# Generated by Django 5.1.4 on 2026-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin_app', '0004_databasebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSGlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size', models.PositiveIntegerField(default=400, verbose_name='Taille max upload globale (KB)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Globale SaaS',
                'verbose_name_plural': 'Configurations Globales SaaS',
            },
        ),
    ]
