# Generated by Django 5.1.4 on 2026-04-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin_app', '0005_saasglobalconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Connaissance',
                'verbose_name_plural': 'Catégories de Connaissance',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Vidéo (YouTube/Vimeo)'), ('PDF', 'Document PDF'), ('ARTICLE', 'Article/Texte'), ('FILE', 'Fichier à télécharger')], default='VIDEO', max_length=20, verbose_name='Type de ressource')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description/Contenu')),
                ('video_url', models.URLField(blank=True, help_text='Lien direct vers la vidéo', null=True, verbose_name='URL Vidéo (Youtube/Vimeo)')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='knowledge_resources/', verbose_name='Fichier joint')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='saas_admin_app.knowledgecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ressource de Connaissance',
                'verbose_name_plural': 'Ressources de Connaissance',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
