# Generated by Django 5.1.4 on 2026-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin_app', '0006_knowledgecategory_knowledgeresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='ex: v1.2.4', max_length=50, verbose_name='Version')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('update_type', models.CharField(choices=[('bugfix', 'Correction de Bug'), ('feature', 'Nouvelle Fonctionnalité'), ('optimisation', 'Optimisation'), ('security', 'Sécurité'), ('other', 'Autre')], default='bugfix', max_length=20, verbose_name='Type de mise à jour')),
                ('date_published', models.DateTimeField(verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=True, verbose_name='Est publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mise à jour Système (Changelog)',
                'verbose_name_plural': 'Mises à jour Système',
                'ordering': ['-date_published', '-created_at'],
            },
        ),
    ]
