# Generated by Django 5.1.4 on 2026-06-07 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_institut_is_portail_active'),
        ('saas_admin_app', '0007_systemupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('target_type', models.CharField(choices=[('all', 'Tous les utilisateurs'), ('tenant', "Utilisateurs d'un Tenant spécifique"), ('user', 'Un utilisateur spécifique dans un Tenant')], default='all', max_length=20, verbose_name='Cible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.institut', verbose_name='Tenant ciblé')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ciblé')),
            ],
            options={
                'verbose_name': 'Annonce Système',
                'verbose_name_plural': 'Annonces Système',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='saas_admin_app.systemannouncement')),
            ],
            options={
                'verbose_name': "Lecture d'annonce",
                'verbose_name_plural': "Lectures d'annonces",
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
