# Generated by Django 5.1.4 on 2026-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin_app', '0008_systemannouncement_announcementread'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasglobalconfiguration',
            name='gestion_donnees_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe Gestion de Données'),
        ),
    ]
