# Generated by Django 5.1.4 on 2026-01-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_formations', '0004_alter_programmeformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('VACATION', "Vacation (Paiement à l'heure)")], default='CDD', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, help_text='Salaire de base mensuel ou Taux horaire si vacation', max_digits=12)),
                ('salaire_horaire', models.DecimalField(blank=True, decimal_places=2, help_text='Remplir si Vacation', max_digits=10, null=True)),
                ('prime_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_panier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='t_formations.formateurs')),
            ],
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.IntegerField()),
                ('jours_travailles', models.IntegerField(default=22)),
                ('heures_travailles', models.DecimalField(decimal_places=2, default=0, help_text='Pour les vacataires', max_digits=6)),
                ('primes_exceptionnelles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retenues_absences', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avance_sur_salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_base_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_poste', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_ss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salaire_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='t_ressource_humaine.contrat')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('contrat', 'mois', 'annee')},
            },
        ),
    ]
