# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepaie',
            name='prime_panier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fichepaie',
            name='prime_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
