# Generated by Django 5.1.4 on 2026-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepaie',
            name='heures_absence',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Nombre d'heures d'absence", max_digits=6),
        ),
        migrations.AddField(
            model_name='parametrespaie',
            name='heures_mensuelles_standard',
            field=models.DecimalField(decimal_places=2, default=173.33, help_text="Nombre d'heures travaillés standard par mois (ex: 173.33)", max_digits=6),
        ),
    ]
