# Generated by Django 5.1.4 on 2026-01-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0002_fichepaie_heures_absence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('type_rubrique', models.CharField(choices=[('GAIN', 'Gain (+)'), ('RETENUE', 'Retenue (-)')], default='GAIN', max_length=10)),
                ('est_cotisable', models.BooleanField(default=False, help_text='Soumis à la cotisation SS (9%) ?')),
                ('est_imposable', models.BooleanField(default=False, help_text="Soumis à l'impôt IRG ?")),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type_rubrique', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='LignePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche_paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_paie', to='t_ressource_humaine.fichepaie')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='t_ressource_humaine.rubrique')),
            ],
        ),
    ]
