# Generated by Django 5.1.4 on 2026-01-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0003_rubrique_lignepaie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='updated_at',
        ),
    ]
