# Generated by Django 5.1.4 on 2026-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0004_remove_contrat_actif_remove_contrat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
