# Generated by Django 5.1.4 on 2026-01-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0005_contrat_actif_contrat_created_at_contrat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrique',
            name='types_contrat',
            field=models.JSONField(blank=True, default=list, help_text="Types de contrats éligibles (ex: ['CDI', 'CDD'])"),
        ),
        migrations.CreateModel(
            name='RubriqueContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Montant par défaut pour ce contrat', max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques_contrat', to='t_ressource_humaine.contrat')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_lies', to='t_ressource_humaine.rubrique')),
            ],
            options={
                'verbose_name': 'Rubrique par Contrat',
                'verbose_name_plural': 'Rubriques par Contrat',
                'unique_together': {('contrat', 'rubrique')},
            },
        ),
    ]
