# Generated by Django 5.1.4 on 2026-01-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0006_rubrique_types_contrat_rubriquecontrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
