# Generated by Django 5.1.4 on 2026-01-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0007_alter_rubrique_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubriquecontrat',
            name='montant',
        ),
        migrations.AddField(
            model_name='lignepaie',
            name='valeur_saisie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='La valeur saisie (%, heures, ou montant)', max_digits=12),
        ),
        migrations.AddField(
            model_name='rubrique',
            name='mode_calcul',
            field=models.CharField(choices=[('FIXE', 'Montant Fixe (DA)'), ('PERCENT', 'Pourcentage du Salaire de Base (%)'), ('HOURS', "Nombre d'heures (h)")], default='FIXE', max_length=10),
        ),
        migrations.AddField(
            model_name='rubriquecontrat',
            name='valeur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur par défaut (Montant, % ou Heures)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignepaie',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Le montant calculé final', max_digits=12),
        ),
    ]
