# Generated by Django 5.1.4 on 2026-05-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0009_remove_promos_date_debut_remove_promos_date_fin'),
        ('t_ressource_humaine', '0008_remove_rubriquecontrat_montant_and_more'),
        ('t_rh', '0002_alter_absences_options_absences_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats_paie', to='t_rh.employees'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='t_formations.formateurs'),
        ),
    ]
