# Generated by Django 5.1.4 on 2026-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0009_contrat_employee_alter_contrat_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrancheIRG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_montant', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour la dernière tranche', max_digits=12, null=True)),
                ('taux', models.DecimalField(decimal_places=4, help_text='Ex: 0.23 pour 23%', max_digits=5)),
            ],
            options={
                'verbose_name': 'Tranche IRG',
                'verbose_name_plural': 'Tranches IRG',
                'ordering': ['min_montant'],
            },
        ),
    ]
