# Generated by Django 5.1.4 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0010_trancheirg'),
        ('t_rh', '0006_employees_ccp_employees_rib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrique',
            name='types_contrat',
        ),
        migrations.AddField(
            model_name='rubrique',
            name='eligible_types',
            field=models.ManyToManyField(blank=True, help_text="Types de contrats auxquels cette rubrique s'applique.", related_name='rubriques', to='t_rh.typescontrat'),
        ),
    ]
