# Generated by Django 5.1.4 on 2026-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0011_remove_rubrique_types_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrique',
            name='valeur_defaut',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur par défaut (Montant, % ou Heures)', max_digits=12),
        ),
    ]
