# Generated by Django 5.1.4 on 2026-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0012_rubrique_valeur_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepaie',
            name='montant_ss_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrespaie',
            name='snmg_valeur',
            field=models.DecimalField(decimal_places=2, default=20000.0, help_text='Valeur du Salaire National Minimum Garanti (SNMG)', max_digits=12),
        ),
        migrations.AddField(
            model_name='parametrespaie',
            name='taux_ss_patronal',
            field=models.DecimalField(decimal_places=4, default=0.26, help_text='Taux de sécurité sociale patronal (ex: 0.26 pour 26%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='mode_calcul',
            field=models.CharField(choices=[('FIXE', 'Montant Fixe (DA)'), ('PERCENT', 'Pourcentage du Salaire de Base (%)'), ('HOURS', "Nombre d'heures (h)"), ('ANCIENNETE', 'Ancienneté (IEP)')], default='FIXE', max_length=10),
        ),
    ]
