# Generated by Django 5.1.4 on 2026-06-04 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_formations', '0012_modules_plan_cours'),
        ('t_ressource_humaine', '0013_fichepaie_montant_ss_patronal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFicheMensuelleFormateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.IntegerField()),
                ('total_heures', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_mensuelles_validees', to='t_formations.formateurs')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Fiche Mensuelle Formateur',
                'verbose_name_plural': 'Validations Fiches Mensuelles Formateurs',
                'unique_together': {('formateur', 'mois', 'annee')},
            },
        ),
    ]
