# Generated by Django 5.1.4 on 2026-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0014_validationfichemensuelleformateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrespaie',
            name='taux_irg_vacataire',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text="Taux de l'IRG applicable aux formateurs vacataires (ex: 0.10 pour 10%, ou 0.15 pour 15%)", max_digits=5),
        ),
    ]
