# Generated by Django 5.1.4 on 2026-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0015_parametrespaie_taux_irg_vacataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrique',
            name='mode_calcul',
            field=models.CharField(choices=[('FIXE', 'Montant Fixe (DA)'), ('PERCENT', 'Pourcentage du Salaire de Base (%)'), ('HOURS', "Nombre d'heures (h)"), ('JOURS', 'Par jour travaillé (Jour)'), ('ANCIENNETE', 'Ancienneté (IEP)')], default='FIXE', max_length=10),
        ),
    ]
