# Generated by Django 5.1.4 on 2026-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_ressource_humaine', '0016_alter_rubrique_mode_calcul'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepaie',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichepaie',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
