# Generated by Django 5.1.4 on 2025-03-26 08:27

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, choices=[('monsieur', 'Monsieur'), ('madame', 'Madame')], max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('type_visiteur', models.CharField(blank=True, choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_paied_enrollment', models.BooleanField(default=False)),
                ('has_completed_documents', models.BooleanField(default=False)),
                ('has_paid_fees', models.BooleanField(default=False)),
                ('cin', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau_etude', models.CharField(blank=True, choices=[('9af', '9 AF/ 4 AM'), ('1as', '1 AS/2 AS'), ('ter', 'Terminal'), ('bac', 'Bac'), ('bac+2', 'Bac+2'), ('bac+3', 'Bac+3'), ('bac+4', 'Bac+4'), ('bac+5', 'Bac+5')], max_length=255, null=True)),
                ('situation_family', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)')], max_length=255, null=True)),
                ('situation_professionnelle', models.CharField(blank=True, choices=[('etudiant', 'Etudiant(e)'), ('salarié', 'Salarié(e)'), ('employeur', 'Employeur'), ('sans_emploi', 'Sans emploi')], max_length=255, null=True)),
                ('post_occupe', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('is_entreprise', models.BooleanField(default=False)),
                ('etat', models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('en_attente', 'En attente'), ('inscrit', 'Inscrit'), ('rejete', 'Rejeté')], default='visiteur', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
            },
        ),
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(blank=True, choices=[('week', 'Week-End'), ('jour', 'Cours du jour'), ('soir', 'Cours du soir')], max_length=255, null=True)),
                ('session', models.CharField(blank=True, choices=[('octobre', 'Octobre'), ('mars', 'mars')], max_length=255, null=True)),
                ('etat', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_demande_inscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
            },
        ),
    ]
