# Generated by Django 5.1.4 on 2026-01-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospets',
            name='lead_source',
        ),
        migrations.AlterField(
            model_name='prospets',
            name='contact_situation',
            field=models.CharField(blank=True, choices=[('fist_contact', 'Premier passage'), ('a_appeler', 'Après Appel'), ('est_passer', 'Après visite')], max_length=100, null=True),
        ),
    ]
