# Generated by Django 5.1.4 on 2026-01-12 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_crm', '0001_initial'),
        ('t_formations', '0001_initial'),
        ('t_remise', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeinscription',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.formation'),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_demande_inscription', to='t_formations.promos'),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_demande_inscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='demande_inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.demandeinscription'),
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='id_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.dossierinscription'),
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_fiche_voeux', to='t_formations.promos'),
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialite_fiche_voeux', to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='fiche_voeux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.fichedevoeux'),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_fiche_voeux_secondaire', to='t_formations.promos'),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='fichevoeuxdouble',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_fiche_voeux_double', to='t_formations.promos'),
        ),
        migrations.AddField(
            model_name='fichevoeuxdouble',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='t_formations.doublediplomation'),
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='fiche_voeux_double',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.fichevoeuxdouble'),
        ),
        migrations.AddField(
            model_name='notesprocpects',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notesprocpects',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='fichevoeuxdouble',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_fiche_voeux_double', to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_fiche_voeux', to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='derogations',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='relancesprospet',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='remiseappliquer',
            name='remise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_remise.remises'),
        ),
        migrations.AddField(
            model_name='remiseappliquerline',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='remiseappliquerline',
            name='remise_appliquer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.remiseappliquer'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='visiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.visiteurs'),
        ),
    ]
