# Generated by Django 5.1.4 on 2025-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='first_contact',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='has_aleardy_visited',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='has_already_called',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('viste', 'Visite'), ('appel', 'Appel'), ('prospectus', 'Prospectus')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('autre', 'Autre'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('bouche-a-oreille', 'Bouche à oreille'), ('site', 'Site Web'), ('prospectus', 'Prospectus'), ('pub', 'Publicitée')], max_length=255, null=True),
        ),
    ]
