# Generated by Django 5.1.4 on 2025-02-17 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_nouveauvisiteur_cin'),
        ('t_formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NouveauVisiteur',
            new_name='Visiteurs',
        ),
    ]
