# Generated by Django 5.1.4 on 2025-09-11 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_prospets_first_contact_prospets_has_aleardy_visited_and_more'),
        ('t_formations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichedevoeuxaddiotionnel',
            options={'verbose_name': 'Fiche de Voeux secondaire', 'verbose_name_plural': 'Fiches de Voeux secondaire'},
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='commentaire',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_fiche_voeux_secondaire', to='t_formations.promos'),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='fichedevoeuxaddiotionnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
