# Generated by Django 5.1.4 on 2025-08-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('type_prospect', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], max_length=255, null=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('autre', 'Autre')], max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
            },
        ),
        migrations.CreateModel(
            name='DocumentsDemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.FileField(blank=True, null=True, upload_to='documents/cin/')),
                ('bac', models.FileField(blank=True, null=True, upload_to='documents/bac/')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='documents/diplome/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/photo/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents/cv/')),
                ('demande_inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.demandeinscription')),
            ],
            options={
                'verbose_name': "Documents de la demande d'inscription",
                'verbose_name_plural': "Documents de la demande d'inscription",
            },
        ),
        migrations.CreateModel(
            name='RelancesProspet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relance', models.DateField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('autre', 'Autre')], max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('etat', models.BooleanField(default=False)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
            ],
            options={
                'verbose_name': 'Relance de Prospect',
                'verbose_name_plural': 'Relances de Prospects',
            },
        ),
    ]
