# Generated by Django 5.1.4 on 2025-03-27 21:43

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteurs',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='civilite',
            field=models.CharField(choices=[('monsieur', 'Monsieur'), ('madame', 'Madame')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='lieu_naissance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurs',
            name='type_visiteur',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], max_length=255, null=True),
        ),
    ]
