# Generated by Django 5.1.4 on 2025-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_demandeinscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiteurs',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='visiteurs',
            name='formule',
        ),
        migrations.RemoveField(
            model_name='visiteurs',
            name='session',
        ),
        migrations.RemoveField(
            model_name='visiteurs',
            name='specialite',
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='formule',
            field=models.CharField(blank=True, choices=[('week', 'Week-End'), ('jour', 'Cours du jour'), ('soir', 'Cours du soir')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='session',
            field=models.CharField(blank=True, choices=[('octobre', 'Octobre'), ('mars', 'mars')], max_length=255, null=True),
        ),
    ]
