# Generated by Django 5.1.4 on 2026-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='conseil_pipeline_stage',
            field=models.CharField(blank=True, choices=[('entrant', 'Entrant'), ('contacte', 'Contacté'), ('negociation', 'Négociation'), ('devis_envoye', 'Devis envoyé'), ('en_negociation', 'En Négociation'), ('facture', 'Facturé'), ('recouvrement', 'RECOUVREMENT')], default='entrant', max_length=50, null=True),
        ),
    ]
