# Generated by Django 5.1.4 on 2025-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_alter_fichedevoeuxaddiotionnel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospets',
            name='first_contact',
        ),
        migrations.RemoveField(
            model_name='prospets',
            name='has_aleardy_visited',
        ),
        migrations.RemoveField(
            model_name='prospets',
            name='has_already_called',
        ),
        migrations.AddField(
            model_name='prospets',
            name='contact_situation',
            field=models.CharField(blank=True, choices=[('fist_contact', 'Premiere visiste'), ('a_appeler', 'A déja appeler'), ('est_passer', 'Visiste')], max_length=100, null=True),
        ),
    ]
