# Generated by Django 5.1.4 on 2025-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_prospets_documentsdemandeinscription_relancesprospet'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='nin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
