# Generated by Django 5.1.4 on 2025-02-17 12:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_rename_nouveauvisiteur_visiteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurs',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
