# Generated by Django 5.1.4 on 2025-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_alter_visiteurs_adresse_alter_visiteurs_civilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteurs',
            name='civilite',
            field=models.CharField(choices=[('monsieur', 'Mr.'), ('madame', 'Mme')], max_length=255, null=True),
        ),
    ]
