# Generated by Django 5.1.4 on 2026-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_prospets_conseil_pipeline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='conseil_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Budget Conseil'),
        ),
        migrations.AddField(
            model_name='prospets',
            name='conseil_is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favori Conseil'),
        ),
        migrations.AddField(
            model_name='prospets',
            name='conseil_probability',
            field=models.IntegerField(default=0, verbose_name='Probabilité (%)'),
        ),
    ]
