# Generated by Django 5.1.4 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_alter_prospets_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='canal',
            field=models.CharField(choices=[('web', 'Recherche sur le web'), ('recommandation', 'Recommandation'), ('email', 'Email'), ('telephone', 'Téléphone'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('bouche-a-oreille', 'Bouche à oreille'), ('site', 'Site Web'), ('prospectus', 'Prospectus'), ('pub', 'Publicitée'), ('autre', 'Autre')], max_length=255, null=True),
        ),
    ]
