# Generated by Django 5.1.4 on 2025-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0003_remove_visiteurs_formation_remove_visiteurs_formule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurs',
            name='civilite',
            field=models.CharField(blank=True, choices=[('monsieur', 'Monsieur'), ('madame', 'Madame')], max_length=255, null=True),
        ),
    ]
