# Generated by Django 5.1.4 on 2026-01-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_alter_prospets_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='type_prospect',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], max_length=255, null=True),
        ),
    ]
