# Generated by Django 5.1.4 on 2025-09-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_remove_prospets_first_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='context',
            field=models.CharField(blank=True, choices=[('acc', 'Acceuil'), ('con', 'Conseil')], max_length=100, null=True),
        ),
    ]
