# Generated by Django 5.1.4 on 2026-01-27 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_prospets_conseil_budget_prospets_conseil_is_favorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='conseil_closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de closing prévue'),
        ),
        migrations.AddField(
            model_name='prospets',
            name='conseil_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_conseil', to=settings.AUTH_USER_MODEL, verbose_name='Commercial Conseil'),
        ),
        migrations.AddField(
            model_name='prospets',
            name='conseil_is_active',
            field=models.BooleanField(default=True, verbose_name='Pipeline Actif'),
        ),
    ]
