# Generated by Django 5.1.4 on 2025-08-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_prospets_nin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDeVoeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
            ],
            options={
                'verbose_name': 'Fiche de Voeux',
                'verbose_name_plural': 'Fiches de Voeux',
            },
        ),
    ]
