# Generated by Django 5.1.4 on 2025-03-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_visiteurs_civilite'),
        ('t_formations', '0004_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeinscription',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_demande_inscription', to='t_formations.promos'),
        ),
    ]
