# Generated by Django 5.1.4 on 2025-04-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_alter_visiteurs_civilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté'), ('paiment', 'Procédure de paiement')], default='en_attente', max_length=255, null=True),
        ),
    ]
