# Generated by Django 5.1.4 on 2025-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0004_visiteurs_date_naissance_visiteurs_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurs',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='formule',
            field=models.CharField(blank=True, choices=[('week', 'Week-End'), ('jour', 'Cours du jour'), ('soir', 'Cours du soir')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('9af', '9 AF/ 4 AM'), ('1as', '1 AS/2 AS'), ('ter', 'Terminal'), ('bac', 'Bac'), ('bac+2', 'Bac+2'), ('bac+3', 'Bac+3'), ('bac+4', 'Bac+4'), ('bac+5', 'Bac+5')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='post_occupe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='session',
            field=models.CharField(blank=True, choices=[('octobre', 'Octobre'), ('mars', 'mars')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='situation_family',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='situation_professionnelle',
            field=models.CharField(blank=True, choices=[('etudiant', 'Etudiant(e)'), ('salarié', 'Salarié(e)'), ('employeur', 'Employeur'), ('sans_emploi', 'Sans emploi')], max_length=255, null=True),
        ),
    ]
