# Generated by Django 5.1.4 on 2025-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0005_visiteurs_entreprise_visiteurs_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurs',
            name='is_entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
