# Generated by Django 5.1.4 on 2025-09-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0005_prospets_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemiseAppliquer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
