# Generated by Django 5.1.4 on 2026-01-27 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0005_prospets_conseil_closing_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text="Nom de l'opportunité", max_length=255, null=True)),
                ('stage', models.CharField(choices=[('entrant', 'Entrant'), ('contacte', 'Contacté'), ('negociation', 'Négociation'), ('devis_envoye', 'Devis envoyé'), ('en_negociation', 'En Négociation'), ('facture', 'Facturé'), ('recouvrement', 'RECOUVREMENT')], default='entrant', max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Budget')),
                ('probability', models.IntegerField(default=0, verbose_name='Probabilité (%)')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Date de closing prévue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Pipeline Actif')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_conseil', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='t_crm.prospets')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
            },
        ),
    ]
