# Generated by Django 5.1.4 on 2025-03-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0005_demandeinscription_promo'),
        ('t_formations', '0005_promos_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinscription',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_demande_inscription', to='t_formations.promos'),
        ),
    ]
