# Generated by Django 5.1.4 on 2025-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0005_alter_demandeinscription_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurs',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
