# Generated by Django 5.1.4 on 2025-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0005_fichedevoeux'),
        ('t_formations', '0006_partenaires_etat_partenaires_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='voeux',
            field=models.ManyToManyField(to='t_formations.specialites'),
        ),
    ]
