# Generated by Django 5.1.4 on 2026-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_opportunite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='conseil_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Budget Conseil'),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='conseil_is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Pipeline Actif'),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='conseil_is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Favori Conseil'),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='conseil_probability',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Probabilité (%)'),
        ),
    ]
