# Generated by Django 5.1.4 on 2025-08-20 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_prospets_voeux'),
        ('t_formations', '0006_partenaires_etat_partenaires_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospets',
            name='voeux',
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.specialites'),
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
