# Generated by Django 5.1.4 on 2026-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesprocpects',
            name='tage',
            field=models.CharField(blank=True, choices=[('important', 'Important'), ('a_revoir', 'A revoir'), ('a_contacte', 'À contacter'), ('a_relancer', 'À relancer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='canal',
            field=models.CharField(choices=[('web', 'Recherche sur le web'), ('recommandation', 'Recommandation'), ('email', 'Email'), ('telephone', 'Téléphone'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('bouche-a-oreille', 'Bouche à oreille'), ('site', 'Site Web'), ('prospectus', 'Prospectus'), ('pub', 'Publicité'), ('autre', 'Autre')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('a-', 'A-'), ('a+', 'A+'), ('b+', 'B+'), ('b-', 'B-'), ('ab-', 'AB-'), ('ab+', 'AB+'), ('o-', 'o-'), ('o+', 'o+')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='poste_dans_entreprise',
            field=models.CharField(blank=True, choices=[('salarie', 'Salarié'), ('responsable', 'Responsable'), ('directeur', 'Directeur'), ('gerant', 'Gérant')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='statut',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('prinscrit', 'Pré-inscrit'), ('instance', 'Instance de paiement'), ('convertit', 'Convertit'), ('annuler', 'Inscription Annulée')], default='visiteur', max_length=100, null=True),
        ),
    ]
