# Generated by Django 5.1.4 on 2025-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_visiteurs_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteurs',
            name='etat',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('instance', 'En Instance'), ('en_attente', 'En attente'), ('inscrit', 'Inscrit'), ('rejete', 'Rejeté')], default='visiteur', max_length=255, null=True),
        ),
    ]
