# Generated by Django 5.1.4 on 2025-09-13 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_remiseappliquer'),
        ('t_remise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remiseappliquer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remiseappliquer',
            name='is_approuved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remiseappliquer',
            name='remise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_remise.remises'),
        ),
        migrations.AddField(
            model_name='remiseappliquer',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RemiseAppliquerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
                ('remise_appliquer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.remiseappliquer')),
            ],
        ),
    ]
