# Generated by Django 5.1.4 on 2025-02-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0006_visiteurs_is_entreprise_visiteurs_is_student'),
        ('t_formations', '0011_alter_specialites_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurs',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_formations.specialites'),
        ),
    ]
