# Generated by Django 5.1.4 on 2025-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0007_visiteurs_specialite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiteurs',
            old_name='has_paied',
            new_name='has_completed_documents',
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('inscrit', 'Inscrit'), ('rejete', 'Rejeté')], default='en_attente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='has_paid_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visiteurs',
            name='has_paied_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
