# Generated by Django 5.1.4 on 2025-09-14 17:38

import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0007_remiseappliquer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remiseappliquer',
            name='fichie_justificatif',
            field=models.FileField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path),
        ),
    ]
