# Generated by Django 5.1.4 on 2025-08-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0007_remove_prospets_voeux_fichedevoeux_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=255, null=True),
        ),
    ]
