# Generated by Django 5.1.4 on 2026-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0007_alter_prospets_conseil_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='context',
            field=models.CharField(blank=True, choices=[('acc', 'Acceuil'), ('con', 'Conseil'), ('tre', 'Tresorerie')], max_length=100, null=True),
        ),
    ]
