# Generated by Django 5.1.4 on 2026-03-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0008_alter_prospets_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='art_imp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Article d'imposition"),
        ),
        migrations.AddField(
            model_name='prospets',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='prospets',
            name='nis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIS'),
        ),
        migrations.AddField(
            model_name='prospets',
            name='rc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registre de Commerce'),
        ),
        migrations.CreateModel(
            name='ProspectBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Nom de la banque')),
                ('rib', models.CharField(max_length=100, verbose_name='RIB / Numéro de compte')),
                ('swift', models.CharField(blank=True, max_length=50, null=True, verbose_name='SWIFT / BIC')),
                ('bank_address', models.TextField(blank=True, null=True, verbose_name='Adresse de la banque')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='t_crm.prospets')),
            ],
            options={
                'verbose_name': 'Compte Bancaire Prospect',
                'verbose_name_plural': 'Comptes Bancaires Prospects',
            },
        ),
    ]
