# Generated by Django 5.1.4 on 2025-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0008_prospets_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('autre', 'Autre'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=255, null=True),
        ),
    ]
