# Generated by Django 5.1.4 on 2025-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0008_rename_has_paied_visiteurs_has_completed_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteurs',
            name='etat',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('en_attente', 'En attente'), ('inscrit', 'Inscrit'), ('rejete', 'Rejeté')], default='visiteur', max_length=255, null=True),
        ),
    ]
