# Generated by Django 5.1.4 on 2025-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0008_remiseappliquer_fichie_justificatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='derogations',
            name='date_de_traitement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
