# Generated by Django 5.1.4 on 2025-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0009_derogations_date_de_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='has_special_echeancier',
            field=models.BooleanField(default=False),
        ),
    ]
