# Generated by Django 5.1.4 on 2025-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0009_alter_prospets_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='poste_dans_entreprise',
            field=models.CharField(blank=True, choices=[('salarie', 'Salarié'), ('responsable', 'Résponsable'), ('directeur', 'Directeur'), ('gerant', 'Gérant')], max_length=100, null=True),
        ),
    ]
