# Generated by Django 5.1.4 on 2026-03-17 22:53

import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0009_prospets_art_imp_prospets_nif_prospets_nis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='logo_entreprise',
            field=models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_logos),
        ),
    ]
