# Generated by Django 5.1.4 on 2025-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0010_prospets_has_special_echeancier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='statut',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('prinscrit', 'Pré-inscript'), ('instance', 'Instance de paiement'), ('convertit', 'Convertit')], default='visiteur', max_length=100, null=True),
        ),
    ]
