# Generated by Django 5.1.4 on 2026-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0010_prospets_logo_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
