# Generated by Django 5.1.4 on 2025-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0011_notesprocpects'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancesprospet',
            name='objet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
