# Generated by Django 5.1.4 on 2025-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0011_alter_prospets_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derogations',
            name='date_de_traitement',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
