# Generated by Django 5.1.4 on 2025-09-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0012_alter_derogations_date_de_traitement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichedevoeux',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_fiche_voeux', to='t_crm.prospets'),
        ),
    ]
