# Generated by Django 5.1.4 on 2025-08-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0012_relancesprospet_objet'),
        ('t_formations', '0007_dossierinscription_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsdemandeinscription',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='documentsdemandeinscription',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='documentsdemandeinscription',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='documentsdemandeinscription',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='documentsdemandeinscription',
            name='photo',
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents_demande_inscription/dossiers/'),
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='id_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.dossierinscription'),
        ),
    ]
