# Generated by Django 5.1.4 on 2026-04-07 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0013_alter_demandeinscription_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('visit', 'Visite'), ('call', 'Appel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité CRM',
                'verbose_name_plural': 'Activités CRM',
                'ordering': ['-created_at'],
            },
        ),
    ]
