# Generated by Django 5.1.4 on 2025-09-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0013_alter_fichedevoeux_prospect'),
        ('t_formations', '0009_remove_formation_frais_assurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichedevoeux',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialite_fiche_voeux', to='t_formations.specialites'),
        ),
    ]
