# Generated by Django 5.1.4 on 2026-04-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0014_crmactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='specialite_obtenu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('1_am', '1 AM'), ('2_am', '2 AM'), ('3_am', '3 AM'), ('4_am', '4 AM'), ('1_as', '1 AS'), ('2_as', '2 AS'), ('terminal', 'Terminale'), ('bac1', 'BAC +1'), ('bac2', 'BAC +2'), ('licence', 'BAC +3'), ('m', 'BAC +4'), ('b5', 'BAC +5'), ('b6', 'BAC +6'), ('bp', 'BAC +')], max_length=100, null=True),
        ),
    ]
