# Generated by Django 5.1.4 on 2025-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0014_alter_fichedevoeux_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='has_refund',
            field=models.BooleanField(default=False),
        ),
    ]
