# Generated by Django 5.1.4 on 2025-08-28 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0014_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
