# Generated by Django 5.1.4 on 2025-09-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0015_prospets_has_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='contact_situation',
            field=models.CharField(blank=True, choices=[('fist_contact', 'Premiere visiste'), ('a_appeler', 'Appelle téléphonique'), ('est_passer', 'Visiste')], max_length=100, null=True),
        ),
    ]
