# Generated by Django 5.1.4 on 2026-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0015_prospets_specialite_obtenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='filiere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
