# Generated by Django 5.1.4 on 2025-08-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0016_preinscript'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preinscript',
            new_name='Preinscrits',
        ),
    ]
