# Generated by Django 5.1.4 on 2026-04-11 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0016_prospets_filiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='financial_alert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='financial_alert_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='financial_alert_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_alerts_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospets',
            name='has_financial_alert',
            field=models.BooleanField(default=False),
        ),
    ]
