# Generated by Django 5.1.4 on 2025-09-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0016_alter_prospets_contact_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='statut',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('prinscrit', 'Pré-inscript'), ('instance', 'Instance de paiement'), ('convertit', 'Convertit'), ('annuler', 'Inscription Annulé')], default='visiteur', max_length=100, null=True),
        ),
    ]
