# Generated by Django 5.1.4 on 2025-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0017_rename_preinscript_preinscrits'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='statut',
            field=models.CharField(blank=True, choices=[('visiteur', 'Visiteur'), ('prinscrit', 'Pré-inscript'), ('instance', 'Instance'), ('convertit', 'Convertit')], default='visiteur', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Preinscrits',
        ),
    ]
