# Generated by Django 5.1.4 on 2025-10-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0017_alter_prospets_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='convertit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='instance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='preinscri_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='prospect_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
