# Generated by Django 5.1.4 on 2026-04-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0017_prospets_financial_alert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='related_prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_enrollments', to='t_crm.prospets'),
        ),
    ]
