# Generated by Django 5.1.4 on 2025-10-03 11:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0018_prospets_convertit_date_prospets_instance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='DZ'),
        ),
    ]
