# Generated by Django 5.1.4 on 2025-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0018_prospets_statut_delete_preinscrits'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
