# Generated by Django 5.1.4 on 2025-08-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0019_prospets_motif_rejet'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesprocpects',
            name='context',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notesprocpects',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='context',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
