# Generated by Django 5.1.4 on 2026-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0019_derogations_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='engagement_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='engagement_printed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='has_printed_engagement',
            field=models.BooleanField(default=False),
        ),
    ]
