# Generated by Django 5.1.4 on 2026-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0020_prospets_engagement_printed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('rejete', 'Rejeté'), ('annuler', 'Annuler')], default='en_attente', max_length=255, null=True),
        ),
    ]
