# Generated by Django 5.1.4 on 2025-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0020_notesprocpects_context_notesprocpects_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='has_completed_doc',
            field=models.BooleanField(default=False),
        ),
    ]
