# Generated by Django 5.1.4 on 2025-10-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0020_prospets_indic_prospets_indic1_prospets_indic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='nationnalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospets',
            name='telephone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
