# Generated by Django 5.1.4 on 2026-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0021_alter_prospets_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
