# Generated by Django 5.1.4 on 2025-10-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0021_prospets_nationnalite_alter_prospets_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='remiseappliquer',
            name='is_applicated',
            field=models.BooleanField(default=False),
        ),
    ]
