# Generated by Django 5.1.4 on 2025-08-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0021_prospets_has_completed_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedevoeux',
            name='commentaire',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
