# Generated by Django 5.1.4 on 2025-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0022_fichedevoeux_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('a-', 'A-'), ('a+', 'A+'), ('b+', 'B+'), ('b-', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB+'), ('o-', 'o-'), ('o+', 'o+')], max_length=100, null=True),
        ),
    ]
