# Generated by Django 5.1.4 on 2025-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0022_remiseappliquer_is_applicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='is_affected',
            field=models.BooleanField(default=False),
        ),
    ]
