# Generated by Django 5.1.4 on 2025-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0023_prospets_is_affected'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='matricule_interne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
