# Generated by Django 5.1.4 on 2025-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0023_prospets_groupe_sanguin'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='has_endicap',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('1_am', '1 am'), ('2_am', '2 am'), ('3_am', '3_am'), ('4_am', '4 am'), ('1_as', '1 AS'), ('2_as', '2 AS'), ('terminal', 'Terminal'), ('bac1', 'BAC +1'), ('bac2', 'BAC +2'), ('licence', 'Licence'), ('m', 'Master')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='nom_arabe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='prenom_arabe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='prenom_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='prenom_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospets',
            name='tel_mere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='tel_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='type_handicap',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
