# Generated by Django 5.1.4 on 2025-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0024_prospets_matricule_prospets_matricule_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='annee_inscription',
            field=models.CharField(blank=True, choices=[('1', '1 Année'), ('2', '2 Année'), ('stage', 'Stage')], max_length=100, null=True),
        ),
    ]
