# Generated by Django 5.1.4 on 2025-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0024_prospets_adresse_prospets_has_endicap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
