# Generated by Django 5.1.4 on 2025-09-02 10:14

import django.db.models.deletion
import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0025_prospets_date_naissance_prospets_diplome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets'),
        ),
        migrations.AlterField(
            model_name='documentsdemandeinscription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path),
        ),
    ]
