# Generated by Django 5.1.4 on 2025-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0025_prospets_annee_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesprocpects',
            name='observation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
