# Generated by Django 5.1.4 on 2025-09-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0026_documentsdemandeinscription_prospect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='fiche_voeux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.fichedevoeux'),
        ),
        migrations.AddField(
            model_name='fichedevoeux',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
