# Generated by Django 5.1.4 on 2025-11-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0026_notesprocpects_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='annee_obtention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='indic3',
            field=models.CharField(blank=True, choices=[('+1', '🇺🇸 +1 États-Unis / Canada'), ('+7', '🇷🇺 +7 Russie / Kazakhstan'), ('+20', '🇪🇬 +20 Égypte'), ('+27', '🇿🇦 +27 Afrique du Sud'), ('+30', '🇬🇷 +30 Grèce'), ('+31', '🇳🇱 +31 Pays-Bas'), ('+32', '🇧🇪 +32 Belgique'), ('+33', '🇫🇷 +33 France'), ('+34', '🇪🇸 +34 Espagne'), ('+36', '🇭🇺 +36 Hongrie'), ('+39', '🇮🇹 +39 Italie'), ('+40', '🇷🇴 +40 Roumanie'), ('+41', '🇨🇭 +41 Suisse'), ('+43', '🇦🇹 +43 Autriche'), ('+44', '🇬🇧 +44 Royaume-Uni'), ('+45', '🇩🇰 +45 Danemark'), ('+46', '🇸🇪 +46 Suède'), ('+47', '🇳🇴 +47 Norvège'), ('+48', '🇵🇱 +48 Pologne'), ('+49', '🇩🇪 +49 Allemagne'), ('+51', '🇵🇪 +51 Pérou'), ('+52', '🇲🇽 +52 Mexique'), ('+53', '🇨🇺 +53 Cuba'), ('+54', '🇦🇷 +54 Argentine'), ('+55', '🇧🇷 +55 Brésil'), ('+56', '🇨🇱 +56 Chili'), ('+57', '🇨🇴 +57 Colombie'), ('+58', '🇻🇪 +58 Venezuela'), ('+60', '🇲🇾 +60 Malaisie'), ('+61', '🇦🇺 +61 Australie'), ('+62', '🇮🇩 +62 Indonésie'), ('+63', '🇵🇭 +63 Philippines'), ('+64', '🇳🇿 +64 Nouvelle-Zélande'), ('+65', '🇸🇬 +65 Singapour'), ('+66', '🇹🇭 +66 Thaïlande'), ('+81', '🇯🇵 +81 Japon'), ('+82', '🇰🇷 +82 Corée du Sud'), ('+84', '🇻🇳 +84 Vietnam'), ('+86', '🇨🇳 +86 Chine'), ('+90', '🇹🇷 +90 Turquie'), ('+91', '🇮🇳 +91 Inde'), ('+92', '🇵🇰 +92 Pakistan'), ('+93', '🇦🇫 +93 Afghanistan'), ('+94', '🇱🇰 +94 Sri Lanka'), ('+95', '🇲🇲 +95 Myanmar'), ('+98', '🇮🇷 +98 Iran'), ('+211', '🇸🇸 +211 Soudan du Sud'), ('+212', '🇲🇦 +212 Maroc'), ('+213', '🇩🇿 +213 Algérie'), ('+216', '🇹🇳 +216 Tunisie'), ('+218', '🇱🇾 +218 Libye'), ('+220', '🇬🇲 +220 Gambie'), ('+221', '🇸🇳 +221 Sénégal'), ('+222', '🇲🇷 +222 Mauritanie'), ('+223', '🇲🇱 +223 Mali'), ('+224', '🇬🇳 +224 Guinée'), ('+225', '🇨🇮 +225 Côte d’Ivoire'), ('+226', '🇧🇫 +226 Burkina Faso'), ('+227', '🇳🇪 +227 Niger'), ('+228', '🇹🇬 +228 Togo'), ('+229', '🇧🇯 +229 Bénin'), ('+230', '🇲🇺 +230 Maurice'), ('+231', '🇱🇷 +231 Libéria'), ('+232', '🇸🇱 +232 Sierra Leone'), ('+233', '🇬🇭 +233 Ghana'), ('+234', '🇳🇬 +234 Nigeria'), ('+235', '🇹🇩 +235 Tchad'), ('+236', '🇨🇲 +236 Cameroun'), ('+237', '🇨🇫 +237 République centrafricaine'), ('+238', '🇨🇻 +238 Cap-Vert'), ('+239', '🇸🇹 +239 Sao Tomé et Principe'), ('+240', '🇬🇶 +240 Guinée équatoriale'), ('+241', '🇬🇦 +241 Gabon'), ('+242', '🇨🇬 +242 Congo-Brazzaville'), ('+243', '🇨🇩 +243 République démocratique du Congo'), ('+244', '🇦🇴 +244 Angola'), ('+245', '🇬🇼 +245 Guinée-Bissau'), ('+246', '🇮🇴 +246 Territoire britannique de l’océan Indien'), ('+248', '🇸🇨 +248 Seychelles'), ('+249', '🇸🇩 +249 Soudan'), ('+250', '🇷🇼 +250 Rwanda'), ('+251', '🇪🇹 +251 Éthiopie'), ('+252', '🇸🇴 +252 Somalie'), ('+253', '🇩🇯 +253 Djibouti'), ('+254', '🇰🇪 +254 Kenya'), ('+255', '🇹🇿 +255 Tanzanie'), ('+256', '🇺🇬 +256 Ouganda'), ('+257', '🇧🇮 +257 Burundi'), ('+258', '🇲🇿 +258 Mozambique'), ('+260', '🇿🇲 +260 Zambie'), ('+261', '🇲🇬 +261 Madagascar'), ('+262', '🇷🇪 +262 La Réunion'), ('+263', '🇿🇼 +263 Zimbabwe'), ('+264', '🇳🇦 +264 Namibie'), ('+265', '🇲🇼 +265 Malawi'), ('+266', '🇱🇸 +266 Lesotho'), ('+267', '🇧🇼 +267 Botswana'), ('+268', '🇸🇿 +268 Eswatini'), ('+269', '🇰🇲 +269 Comores'), ('+290', '🇸🇭 +290 Sainte-Hélène'), ('+291', '🇪🇷 +291 Érythrée'), ('+297', '🇦🇼 +297 Aruba'), ('+298', '🇫🇴 +298 Îles Féroé'), ('+299', '🇬🇱 +299 Groenland'), ('+350', '🇬🇮 +350 Gibraltar'), ('+351', '🇵🇹 +351 Portugal'), ('+352', '🇱🇺 +352 Luxembourg'), ('+353', '🇮🇪 +353 Irlande'), ('+354', '🇮🇸 +354 Islande'), ('+355', '🇦🇱 +355 Albanie'), ('+356', '🇲🇹 +356 Malte'), ('+357', '🇨🇾 +357 Chypre'), ('+358', '🇫🇮 +358 Finlande'), ('+359', '🇧🇬 +359 Bulgarie'), ('+370', '🇱🇹 +370 Lituanie'), ('+371', '🇱🇻 +371 Lettonie'), ('+372', '🇪🇪 +372 Estonie'), ('+373', '🇲🇩 +373 Moldavie'), ('+374', '🇦🇲 +374 Arménie'), ('+375', '🇧🇾 +375 Biélorussie'), ('+376', '🇦🇩 +376 Andorre'), ('+377', '🇲🇨 +377 Monaco'), ('+378', '🇸🇲 +378 Saint-Marin'), ('+380', '🇺🇦 +380 Ukraine'), ('+381', '🇷🇸 +381 Serbie'), ('+382', '🇲🇪 +382 Monténégro'), ('+385', '🇭🇷 +385 Croatie'), ('+386', '🇸🇮 +386 Slovénie'), ('+387', '🇧🇦 +387 Bosnie-Herzégovine'), ('+389', '🇲🇰 +389 Macédoine du Nord'), ('+420', '🇨🇿 +420 République tchèque'), ('+421', '🇸🇰 +421 Slovaquie'), ('+423', '🇱🇮 +423 Liechtenstein'), ('+500', '🇫🇰 +500 Îles Malouines'), ('+501', '🇧🇿 +501 Belize'), ('+502', '🇬🇹 +502 Guatemala'), ('+503', '🇸🇻 +503 Salvador'), ('+504', '🇭🇳 +504 Honduras'), ('+505', '🇳🇮 +505 Nicaragua'), ('+506', '🇨🇷 +506 Costa Rica'), ('+507', '🇵🇦 +507 Panama'), ('+508', '🇸🇧 +508 Saint-Pierre-et-Miquelon'), ('+509', '🇭🇹 +509 Haïti'), ('+590', '🇬🇵 +590 Guadeloupe'), ('+591', '🇧🇴 +591 Bolivie'), ('+592', '🇬🇾 +592 Guyana'), ('+593', '🇪🇨 +593 Équateur'), ('+594', '🇬🇫 +594 Guyane française'), ('+595', '🇵🇾 +595 Paraguay'), ('+596', '🇲🇶 +596 Martinique'), ('+597', '🇸🇷 +597 Suriname'), ('+598', '🇺🇾 +598 Uruguay'), ('+599', '🇨🇼 +599 Curaçao')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='tuteur_legal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
