# Generated by Django 5.1.4 on 2025-09-02 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0027_documentsdemandeinscription_fiche_voeux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
