# Generated by Django 5.1.4 on 2025-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0027_prospets_annee_obtention_prospets_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='num_secu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
