# Generated by Django 5.1.4 on 2025-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0028_documentsdemandeinscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
