# Generated by Django 5.1.4 on 2025-11-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0028_prospets_num_secu'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='tel_tuteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
