# Generated by Django 5.1.4 on 2025-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0029_prospets_tel_tuteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='contact_situation',
            field=models.CharField(blank=True, choices=[('fist_contact', 'Premiere visiste'), ('a_appeler', 'Appelle téléphonique'), ('est_passer', "Visiste (Le prospect est déja passer à l'insim)")], max_length=100, null=True),
        ),
    ]
