# Generated by Django 5.1.4 on 2025-09-02 12:14

import t_crm.tenant_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0029_documentsdemandeinscription_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=t_crm.tenant_path.tenant_directory_path_for_image),
        ),
    ]
