# Generated by Django 5.1.4 on 2025-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0030_alter_prospets_contact_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='is_double',
            field=models.BooleanField(default=False),
        ),
    ]
