# Generated by Django 5.1.4 on 2025-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0030_prospets_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
