# Generated by Django 5.1.4 on 2025-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0031_rendezvous_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='has_derogation',
            field=models.BooleanField(default=False),
        ),
    ]
