# Generated by Django 5.1.4 on 2025-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0032_prospets_has_derogation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
