# Generated by Django 5.1.4 on 2025-11-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0032_alter_prospets_indic_alter_prospets_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichevoeuxdouble',
            name='commentaire',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
