# Generated by Django 5.1.4 on 2025-11-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0033_fichevoeuxdouble_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsdemandeinscription',
            name='fiche_voeux_double',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.fichevoeuxdouble'),
        ),
    ]
