# Generated by Django 5.1.4 on 2025-09-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0033_prospets_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('autre', 'Autre'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('bouche-a-oreille', 'Bouche à oreille'), ('site', 'Site Web')], max_length=255, null=True),
        ),
    ]
