# Generated by Django 5.1.4 on 2025-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0034_documentsdemandeinscription_fiche_voeux_double'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
