# Generated by Django 5.1.4 on 2025-09-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0034_alter_prospets_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derogations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.CharField(blank=True, max_length=100, null=True)),
                ('date_de_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_crm.prospets')),
            ],
        ),
    ]
