# Generated by Django 5.1.4 on 2025-12-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0035_prospets_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
