# Generated by Django 5.1.4 on 2025-09-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0036_alter_derogations_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='adresse',
            field=models.CharField(blank=True, null=True),
        ),
    ]
