# Generated by Django 5.1.4 on 2025-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0037_alter_prospets_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospets',
            name='adresse',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
