# Generated by Django 5.1.4 on 2025-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0038_alter_prospets_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='lieu_naissance',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
