# Generated by Django 5.1.4 on 2025-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0039_prospets_lieu_naissance_prospets_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='code_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospets',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
