# Generated by Django 5.1.4 on 2025-09-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0040_prospets_code_zip_prospets_wilaya'),
        ('t_formations', '0007_dossierinscription_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedevoeux',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_formations.promos'),
        ),
    ]
