# Generated by Django 5.1.4 on 2025-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0041_fichedevoeux_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='derogations',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
