# Generated by Django 5.1.4 on 2025-09-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0042_derogations_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derogations',
            name='statut',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=100, null=True),
        ),
    ]
