# Generated by Django 5.1.4 on 2025-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0043_alter_derogations_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='derogations',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
