# Generated by Django 5.1.4 on 2025-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0044_derogations_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('abouti', 'Abouti'), ('nabouti', 'Non abouti')], default='en_attente', max_length=255, null=True),
        ),
    ]
