# Generated by Django 5.1.4 on 2025-09-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0045_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
