# Generated by Django 5.1.4 on 2025-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0046_rendezvous_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='is_ets_prospect',
            field=models.BooleanField(default=False),
        ),
    ]
