# Generated by Django 5.1.4 on 2025-09-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0047_prospets_is_ets_prospect'),
        ('t_formations', '0009_alter_promos_begin_year_alter_promos_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichedevoeux',
            name='promo',
            field=models.ForeignKey(blank=True, limit_choices_to={'etat': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_fiche_voeux', to='t_formations.promos'),
        ),
    ]
