# Generated by Django 5.1.4 on 2025-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0048_alter_fichedevoeux_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_counter', models.DateField(blank=True, null=True)),
                ('visite_counter', models.IntegerField(default=0)),
                ('phone_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
