<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-09-11 12:57
=======
# Generated by Django 5.1.4 on 2025-09-11 07:28
>>>>>>> 2b5654b561d93d67b12e862c037af07767e5bc66

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0049_crmcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDeVoeuxAddiotionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
