# Generated by Django 5.1.4 on 2025-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_crm', '0050_fichedevoeuxaddiotionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospets',
            name='has_second_wish',
            field=models.BooleanField(default=False),
        ),
    ]
