"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1','*','insim360.com']


# Application definition

SHARED_APPS = [
    'django_tenants',
    'app',
   
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.sessions',
    
]

TENANT_APPS = [
    'institut_app',
    't_rh',
    't_formations',
    't_etudiants',
    't_crm',
    't_dashboard',
    't_tresorerie',
    't_stage',
    't_commercial',
    't_config',
    't_groupe',
    't_exam',
    't_conseil',
    't_remise',
    't_communication',
    't_timetable',
    'pdf_editor',
    'taggit',
    'django.contrib.humanize',
    'phonenumber_field',
    'django_countries',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.sessions',

]

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django_tenants.middleware.TenantMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    't_crm.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    
    
]

ROOT_URLCONF = 'app.urls'
PUBLIC_SCHEMA_URLCONF  = "app.urls_public"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'institut_app.permissions.context_processors.module_access',
            ],
        },
    },
]

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'insim',
        'USER': 'postgres',
        'PASSWORD': '1230042690',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

TENANT_MODEL = "app.Institut"  # Modèle Tenant
TENANT_DOMAIN_MODEL = "app.Domaine"  # Modèle Domain


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/



TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = 'fr'
USE_L10N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'
# MEDIA_URL = '/media/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_in_inv')]
# VENV_PATH = os.path.dirname(BASE_DIR)
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
# MEDIA_ROOT = os.path.join(VENV_PATH, 'media_root')

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [BASE_DIR / 'static_in_inv']

STATIC_ROOT = BASE_DIR / 'static'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_MODEL_USER ="app.User"


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL= "/"


#LOGIN_URL = "two_factor:login"
#LOGIN_REDIRECT_URL = "institut_app:index"
#LOGOUT_REDIRECT_URL = "two_factor:login"

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'error',
    messages.SUCCESS : 'success',
    messages.DEBUG : 'debug',
    messages.WARNING : 'warning',
    messages.INFO : 'info',
}


# Configuration TinyMCE
TINYMCE_DEFAULT_CONFIG = {
    'height': 700,
    'width': '100%',
    'mode': 'textareas',
    'theme': 'silver',
    'extended_valid_elements': 'tr[*],td[*],th[*]',
    'plugins': 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
    'toolbar': 'undo redo | formatselect | bold italic underline strikethrough | fontselect fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | print preview | fullscreen | charmap emoticons',
    'toolbar_mode': 'floating',
    'skin': 'oxide',
    'content_css': [
        '/static/css/tinymce_document.css',  # CSS impression
    ],
    'menu': {
        'file': {
            'title': 'File',
            'items': 'newdocument | print preview | exportpdf exportword'
        },
        'edit': {
            'title': 'Edit',
            'items': 'undo redo | cut copy paste pastetext | selectall'
        },
        'view': {
            'title': 'View',
            'items': 'code | visualaid visualchars visualblocks fullscreen'
        },
        'insert': {
            'title': 'Insert',
            'items': 'image link media codesample inserttable | charmap emoticons'
        },
        'format': {
            'title': 'Format',
            'items': 'bold italic underline strikethrough superscript subscript | formats | removeformat'
        },
        'table': {
            'title': 'Table',
            'items': 'inserttable | cell row column | tableprops deletetable'
        }
    },
    'relative_urls': False,
    'convert_urls': False,
    'paste_data_images': True,
    'images_upload_url': '/tinymce/upload/',  # URL pour l'upload d'images
    'automatic_uploads': True,
    'object_resizing' : True,
    'forced_root_block': False,  
}
